"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, FileText, Printer } from "lucide-react";
import { useRouter } from "next/navigation";
import type { WorkOrderIssuedPreviewReadModel } from "@/lib/domain/work-orders/contracts";
import styles from "./IssuedWorkOrderPreview.module.css";

type Envelope={readonly ok:true;readonly data:WorkOrderIssuedPreviewReadModel}|{readonly ok:false;readonly error?:{readonly message?:string}};
const number=new Intl.NumberFormat("ko-KR");
const value=(input:string|null|undefined)=>input?.trim()||"-";
const date=(input:string|null|undefined,timeZone="Asia/Seoul")=>input?new Intl.DateTimeFormat("ko-KR",{timeZone,year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date(input)).replaceAll(". ",".").replace(/\.$/,""):"-";
const unitValue=(quantity:string,unit:string)=>`${quantity} ${unit}`;

function RepeatedHeading({data,title}:{data:WorkOrderIssuedPreviewReadModel;title:string}){return <header className={styles.repeatedHeading}><strong>{data.header.productName}</strong><span>{title}</span><small>{data.document.displayDocumentNumber}</small></header>;}
function MaterialTable({title,rows,data}:{title:string;rows:WorkOrderIssuedPreviewReadModel["materials"]["fabrics"];data:WorkOrderIssuedPreviewReadModel}){if(!rows.length)return null;return <section className={`${styles.page} ${styles.followPage}`}><RepeatedHeading data={data} title={title}/><table><thead><tr><th>품명</th><th>색상·옵션·규격</th><th>사용 부위</th><th>필요 수량</th><th>여유 수량</th><th>메모</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.name}</td><td>{value(row.colorOption)}</td><td>{value(row.usageArea)}</td><td className={styles.numeric}>{unitValue(row.requiredQuantity,row.unitCode)}</td><td className={styles.numeric}>{unitValue(row.allowanceQuantity,row.unitCode)}</td><td>{value(row.memo)}</td></tr>)}</tbody></table><div className={styles.penSpace}/></section>;}

export default function IssuedWorkOrderPreview({workOrderId,revisionId}:{readonly workOrderId:string;readonly revisionId:string}){
  const router=useRouter();const [data,setData]=useState<WorkOrderIssuedPreviewReadModel|null>(null);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{let active=true;fetch(`/api/v2/work-orders/${encodeURIComponent(workOrderId)}/revisions/${encodeURIComponent(revisionId)}/preview`,{cache:"no-store"}).then(async response=>({response,body:await response.json() as Envelope})).then(({response,body})=>{if(!active)return;if(!response.ok||!body.ok)setError(body.ok?"Preview를 불러오지 못했습니다.":body.error?.message||"Preview를 불러오지 못했습니다.");else setData(body.data);}).catch(()=>{if(active)setError("Preview를 불러오지 못했습니다.");});return()=>{active=false};},[workOrderId,revisionId]);
  if(error)return <main className={styles.shell}><div className={styles.message}><FileText aria-hidden="true"/><strong>{error}</strong><button type="button" onClick={()=>router.back()}>돌아가기</button></div></main>;
  if(!data)return <main className={styles.shell}><div className={styles.message}>작업지시서를 불러오는 중입니다.</div></main>;
  const matrix=data.sizeColors;const timeZone=data.layoutMetadata.businessTimezone;
  return <main className={styles.shell}>
    <nav className={styles.toolbar} aria-label="작업지시서 도구"><button type="button" onClick={()=>router.back()} title="돌아가기"><ArrowLeft aria-hidden="true"/><span>돌아가기</span></button><div><span>발행된 작업지시서</span><strong>{data.document.displayDocumentNumber}</strong></div><button type="button" onClick={()=>window.print()} title="인쇄"><Printer aria-hidden="true"/><span>인쇄</span></button></nav>
    <article data-testid="issued-workorder-preview-a4">
      <section className={`${styles.page} ${styles.coverPage}`}>
        <header className={styles.documentHeader}><div><p>작업지시서</p><h1>{data.header.productName}</h1><small>{[data.header.seasonCode,data.header.itemCode].filter(Boolean).join(" · ")}</small></div><dl><div><dt>문서번호</dt><dd>{data.document.displayDocumentNumber}</dd></div><div><dt>개정차수</dt><dd>R{data.document.revisionNumber}</dd></div><div><dt>발행일</dt><dd>{date(data.document.issuedAt,timeZone)}</dd></div><div><dt>납기일</dt><dd>{date(data.header.dueDate,timeZone)}</dd></div><div><dt>발주수량</dt><dd>{number.format(data.header.totalQuantity)}</dd></div></dl></header>
        <section className={styles.sketchSection}><h2>제품 스케치·디자인 자료</h2>{data.assets.length?<div className={styles.sketchGrid}>{data.assets.map((asset,index)=><div key={`${asset.assetType}-${index}`}><FileText aria-hidden="true"/><strong>{asset.filename}</strong><span>{asset.isRepresentative?"대표 자료":asset.assetType==="image"?"이미지":"첨부자료"}</span></div>)}</div>:<p className={styles.empty}>등록된 제품 스케치·디자인 자료가 없습니다.</p>}</section>
        <section className={styles.deliveryMemo}><h2>공장 전달 메모</h2><p>{value(data.header.factoryDeliveryMemo)}</p></section>
        <section className={styles.instructions}><h2>핵심 작업 지시·주의사항</h2><p>{value(data.header.memo)}</p></section>
      </section>
      <MaterialTable title="원단" rows={data.materials.fabrics} data={data}/><MaterialTable title="부자재" rows={data.materials.accessories} data={data}/>
      {(matrix.colors.length&&matrix.sizes.length)?<section className={`${styles.page} ${styles.followPage}`}><RepeatedHeading data={data} title="색상·사이즈 수량"/><div className={styles.tableWrap}><table><thead><tr><th>색상</th>{matrix.sizes.map(size=><th key={size.id}>{size.displayLabel}</th>)}<th>합계</th></tr></thead><tbody>{matrix.colors.map(color=>{const cells=matrix.sizes.map(size=>matrix.quantityCells.find(cell=>cell.colorId===color.id&&cell.sizeRowId===size.id));return <tr key={color.id}><td>{color.displayName}</td>{cells.map((cell,index)=><td className={styles.numeric} key={matrix.sizes[index].id}>{cell?.quantity??"-"}</td>)}<td className={styles.numeric}>{cells.reduce((sum,cell)=>sum+Number(cell?.quantity??0),0)}</td></tr>})}<tr><th>합계</th>{matrix.sizes.map(size=><th className={styles.numeric} key={size.id}>{matrix.quantityCells.filter(cell=>cell.sizeRowId===size.id).reduce((sum,cell)=>sum+Number(cell.quantity),0)}</th>)}<th className={styles.numeric}>{matrix.matrixTotal}</th></tr></tbody></table></div><p className={matrix.totalsMatch?styles.validationOk:styles.validationWarning}>발주수량 대조 · {matrix.matrixTotal} / {matrix.expectedTotal}</p></section>:null}
      {data.sizeSpecifications.sizes.length&&data.sizeSpecifications.pomColumns.length?<section className={`${styles.page} ${styles.followPage}`}><RepeatedHeading data={data} title={`사이즈 스펙 (${data.sizeSpecifications.measurementUnit})`}/><div className={styles.tableWrap}><table><thead><tr><th>측정 부위</th>{data.sizeSpecifications.sizes.map(size=><th key={size.id}>{size.displayLabel}</th>)}</tr></thead><tbody>{data.sizeSpecifications.pomColumns.map(pom=><tr key={pom.id}><td>{pom.displayName}</td>{data.sizeSpecifications.sizes.map(size=>{const cell=data.sizeSpecifications.cells.find(item=>item.sizeRowId===size.id&&item.pomColumnId===pom.id);return <td className={styles.numeric} key={size.id}>{cell?.displayValue??cell?.decimalValue??"-"}</td>})}</tr>)}</tbody></table></div></section>:null}
      {data.processes.length?<section className={`${styles.page} ${styles.followPage}`}><RepeatedHeading data={data} title="제작 공정·추가 공정"/><table><thead><tr><th>순서</th><th>공정명</th><th>업체</th><th>적용 부위</th><th>적용 색상·대상</th><th>수량</th><th>납기</th><th>작업 메모</th></tr></thead><tbody>{data.processes.map((process,index)=><tr key={process.id}><td>{index+1}</td><td>{process.processName}</td><td>{value(process.partnerName)}</td><td>{value(process.applicationArea)}</td><td>{value(process.applicationColorTarget)}</td><td className={styles.numeric}>{unitValue(process.quantity,process.unitCode)}</td><td>{date(process.dueDate,timeZone)}</td><td>{value(process.memo)}</td></tr>)}</tbody></table><div className={styles.penSpace}/></section>:null}
    </article>
  </main>;
}
