"use client";

import { useEffect, useMemo, useState } from "react";

import { AdminButton, AdminLinkButton } from "@/components/admin/common/AdminButton";
import { AdminStatusBadge } from "@/components/admin/common/AdminStatusBadge";
import { WaflInput, WaflTextarea } from "@/components/common/ui";
import SystemShell from "@/components/system/layout/SystemShell";
import { SYSTEM_BODY_TEXT_CLASS, SYSTEM_HEADER_PANEL_CLASS, SYSTEM_PANEL_CLASS, SYSTEM_SUBTITLE_CLASS, SYSTEM_TITLE_CLASS } from "@/components/system/systemSemanticClassNames";
import { waflLegacyApiRequest } from "@/lib/api/waflApiClient";

type Template = { id:string; name:string; templateVersion:number; categoryCode:string|null; genderCode:string|null; sizeSetCode:string|null; isActive:boolean; sizes:readonly {id:string;code:string;label:string;order:number}[]; poms:readonly {id:string;code:string;name:string;measurementType:string;instruction:string|null;order:number}[]; values:readonly {sizeRowId:string;pomColumnId:string;decimalValue:string|null;displayFraction:string|null}[] };
type Draft = { name:string; categoryCode:string; genderCode:string; sizeSetCode:string; structure:string };

function toDraft(template:Template):Draft {
  const sizeCodeById=new Map(template.sizes.map(item=>[item.id,item.code]));
  const pomCodeById=new Map(template.poms.map(item=>[item.id,item.code]));
  return {name:template.name,categoryCode:template.categoryCode??"",genderCode:template.genderCode??"",sizeSetCode:template.sizeSetCode??"",structure:JSON.stringify({sizes:template.sizes.map(({code,label,order})=>({code,label,order})),poms:template.poms.map(({code,name,measurementType,instruction,order})=>({code,name,measurementType,instruction,order})),values:template.values.map(value=>({sizeCode:sizeCodeById.get(value.sizeRowId),pomCode:pomCodeById.get(value.pomColumnId),decimalValue:value.decimalValue===null?null:Number(value.decimalValue),displayFraction:value.displayFraction}))},null,2)};
}

export default function SystemSizeSpecTemplatesPage(){
  const[items,setItems]=useState<readonly Template[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[draft,setDraft]=useState<Draft|null>(null),[message,setMessage]=useState("시스템 완성 치수 템플릿을 불러옵니다."),[busy,setBusy]=useState(false);
  const selected=useMemo(()=>items.find(item=>item.id===selectedId)??null,[items,selectedId]);
  async function load(){setBusy(true);try{const response=await waflLegacyApiRequest<{ok?:boolean;items?:Template[];error?:string}>("/api/system/standards/size-spec-templates",{cache:"no-store"},"완성 치수 템플릿을 불러오지 못했습니다.");if(!response.ok||!response.items)throw new Error(response.error||"조회 실패");setItems(response.items);setMessage(`${response.items.length}개 템플릿을 불러왔습니다.`);}catch(error){setMessage(error instanceof Error?error.message:"조회 실패");}finally{setBusy(false);}}
  useEffect(()=>{let cancelled=false;void waflLegacyApiRequest<{ok?:boolean;items?:Template[];error?:string}>("/api/system/standards/size-spec-templates",{cache:"no-store"},"완성 치수 템플릿을 불러오지 못했습니다.").then(response=>{if(cancelled)return;if(!response.ok||!response.items)throw new Error(response.error||"조회 실패");setItems(response.items);setMessage(`${response.items.length}개 템플릿을 불러왔습니다.`);}).catch(error=>{if(!cancelled)setMessage(error instanceof Error?error.message:"조회 실패");});return()=>{cancelled=true;};},[]);
  async function save(isActive=selected?.isActive){if(!selected||!draft)return;setBusy(true);try{const structure=JSON.parse(draft.structure) as object;const response=await waflLegacyApiRequest<{ok?:boolean;record?:Template;error?:string}>("/api/system/standards/size-spec-templates",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:selected.id,name:draft.name,categoryCode:draft.categoryCode||null,genderCode:draft.genderCode||null,sizeSetCode:draft.sizeSetCode||null,isActive,structure})},"템플릿을 저장하지 못했습니다.");if(!response.ok||!response.record)throw new Error(response.error||"저장 실패");setItems(current=>current.map(item=>item.id===response.record!.id?response.record!:item));setDraft(toDraft(response.record));setMessage(`v${response.record.templateVersion}으로 저장했습니다.`);}catch(error){setMessage(error instanceof Error?error.message:"저장 실패");}finally{setBusy(false);}}
  return <SystemShell><header className={SYSTEM_HEADER_PANEL_CLASS}><h1 className={SYSTEM_TITLE_CLASS}>완성 치수 기준 템플릿</h1><p className={SYSTEM_SUBTITLE_CLASS}>시스템 관리자만 공통 템플릿의 적용 범위, 사이즈, POM, 값을 버전 단위로 관리합니다.</p><div className="mt-4"><AdminLinkButton href="/system/standards">기준정보로 돌아가기</AdminLinkButton></div></header><section className="grid gap-4 lg:grid-cols-[0.75fr_1.25fr]"><article className={SYSTEM_PANEL_CLASS}><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">템플릿 목록</h2><AdminButton disabled={busy} onClick={()=>void load()}>새로고침</AdminButton></div><div className="mt-4 space-y-2">{items.map(item=><button className="flex w-full items-center justify-between rounded-xl border border-stone-200 p-3 text-left" key={item.id} onClick={()=>{setSelectedId(item.id);setDraft(toDraft(item));}} type="button"><span><strong>{item.name}</strong><small className="block text-stone-500">v{item.templateVersion} · {item.sizes.length} sizes · {item.poms.length} POM</small></span><AdminStatusBadge tone={item.isActive?"success":"neutral"}>{item.isActive?"사용":"중지"}</AdminStatusBadge></button>)}</div></article><article className={SYSTEM_PANEL_CLASS}>{selected&&draft?<div className="space-y-3"><h2 className="text-lg font-semibold">템플릿 편집</h2><div className="grid gap-2 md:grid-cols-2"><WaflInput aria-label="템플릿 이름" value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/><WaflInput aria-label="카테고리 코드" placeholder="전체 카테고리는 비움" value={draft.categoryCode} onChange={event=>setDraft({...draft,categoryCode:event.target.value})}/><WaflInput aria-label="성별 코드" placeholder="전체 성별은 비움" value={draft.genderCode} onChange={event=>setDraft({...draft,genderCode:event.target.value})}/><WaflInput aria-label="사이즈 세트 코드" placeholder="선택 사항" value={draft.sizeSetCode} onChange={event=>setDraft({...draft,sizeSetCode:event.target.value})}/></div><label className="block text-sm font-semibold">사이즈 / POM / 값 구조 JSON<WaflTextarea className="mt-2 min-h-80 font-mono text-xs" value={draft.structure} onChange={event=>setDraft({...draft,structure:event.target.value})}/></label><div className="flex gap-2"><AdminButton disabled={busy} onClick={()=>void save()}>새 버전 저장</AdminButton><AdminButton disabled={busy} variant={selected.isActive?"danger":"secondary"} onClick={()=>void save(!selected.isActive)}>{selected.isActive?"비활성화":"활성화"}</AdminButton></div></div>:<p className={SYSTEM_BODY_TEXT_CLASS}>편집할 템플릿을 선택하세요.</p>}</article></section><p className="mt-4 text-sm text-stone-600" role="status">{message}</p></SystemShell>;
}
