export type SignupApplicationApiErrorCode =
  | "SIGNUP_APPLICANT_SESSION_REQUIRED"
  | "SIGNUP_APPLICATION_ID_REQUIRED"
  | "SIGNUP_APPLICATION_NOT_FOUND"
  | "SIGNUP_APPLICATION_CONFLICT"
  | "SIGNUP_DUPLICATE_EMAIL"
  | "SIGNUP_DUPLICATE_GOOGLE_SUB"
  | "SIGNUP_DUPLICATE_BUSINESS_REGISTRATION"
  | "SIGNUP_DUPLICATE_PROVISIONED_RESOURCE"
  | "SIGNUP_CONSENT_REQUIRED"
  | "SIGNUP_PAYLOAD_INVALID"
  | "SIGNUP_CERTIFICATE_UPLOAD_NOT_ALLOWED"
  | "SIGNUP_CERTIFICATE_FILE_REQUIRED"
  | "SIGNUP_CERTIFICATE_MIME_TYPE_UNSUPPORTED"
  | "SIGNUP_CERTIFICATE_EXTENSION_UNSUPPORTED"
  | "SIGNUP_CERTIFICATE_SIGNATURE_UNSUPPORTED"
  | "SIGNUP_CERTIFICATE_SIZE_UNSUPPORTED"
  | "SIGNUP_CERTIFICATE_UPLOAD_NOT_CONFIGURED"
  | "SIGNUP_CERTIFICATE_UPLOAD_FAILED"
  | "SIGNUP_CERTIFICATE_METADATA_SAVE_FAILED"
  | "SIGNUP_CERTIFICATE_NOT_FOUND"
  | "SIGNUP_CERTIFICATE_DELETE_FAILED"
  | "SIGNUP_CERTIFICATE_VIEW_FAILED";

export class SignupApplicationApiError extends Error {
  constructor(
    readonly code: SignupApplicationApiErrorCode,
    readonly status: number,
  ) {
    super(code);
    this.name = "SignupApplicationApiError";
  }
}
