import { APP_VERSION } from "@/lib/constants/version";

import { ROADMAP_0_24_12 } from "./roadmap-0.24.12";
import type { ProductizationRoadmapSummary, RoadmapImpact, RoadmapStatus, RoadmapVersionDetail } from "./types";

export type { ProductizationRoadmapSummary, RoadmapImpact, RoadmapResult, RoadmapStatus, RoadmapVersionDetail } from "./types";

export const ROADMAP_STATUS_LABELS: Record<RoadmapStatus, string> = {
  planned: "예정",
  in_progress: "진행 중",
  implemented: "구현 완료",
  verification_pending: "검증 대기",
  user_test_needed: "사용자 확인 필요",
  user_decision_needed: "사용자 결정 필요",
  completed: "완료",
  paused: "보류",
  canceled: "취소",
};

export const ROADMAP_IMPACT_LABELS: Record<RoadmapImpact, string> = {
  none: "영향 없음",
  read_only: "기존 읽기/동작 유지",
  guarded: "기존 guard 유지",
  pending_decision: "사용자 결정 필요",
};

const completedResult = (commits: string[], verificationResult: string): RoadmapVersionDetail["result"] => ({
  completedSummary: ["구현, 검증, commit, push가 완료된 기준 항목이다."],
  commitHash: commits.join(", "),
  verificationResult,
  remainingIssues: [],
  userConfirmationRequired: false,
  userConfirmationResult: "자동 검증으로 충분한 범위",
});

const ROADMAP_0_24_10: RoadmapVersionDetail = {
  version: "0.24.10",
  title: "시스템 관리자 저장공간과 자동화 기반",
  status: "completed",
  userSummary: [
    "시스템 관리자가 회사별 저장공간 사용량을 DB 기준으로 확인할 수 있게 했다.",
    "Codex가 검증, commit, push를 더 안전하게 진행할 수 있는 PowerShell wrapper를 마련했다.",
  ],
  visibleChanges: [
    "/system/storage-usage가 attachment/trash metadata를 기준으로 저장공간을 집계한다.",
    "PowerShell 메뉴에서 전체 프로젝트 ZIP과 repo-state 전달본을 만들 수 있다.",
  ],
  expectedUi: ["시스템 관리자 저장공간 화면은 조회 중심으로 유지한다.", "일반 사용자 업무 화면은 이 버전에서 바꾸지 않았다."],
  developmentPurpose: ["DB-backed storage usage evidence와 안전한 버전 완료 자동화의 기반을 만든다."],
  developmentUiStructure: ["시스템 storage usage API와 관리자 화면을 기존 system shell 안에서 유지한다."],
  scope: ["storage_usage_snapshots write path 연결", "verify-safe.ps1", "finish-version.ps1", "local repo handoff ZIP/repo-state"],
  outOfScope: ["일반 사용자 workspace UI 변경", "PDF/R2 정책 확정"],
  implementationPrinciples: ["production 접근 없이 dev/test 계약과 repository contract로 검증한다."],
  successConditions: ["Build PASS", "Mutation Audit high-risk 0", "system storage contract PASS"],
  failureConditions: ["DB/R2 production 접근", "package/lockfile 변경", "migration 변경"],
  cautions: ["storage snapshot write는 기존 API 정책 안에서만 사용한다."],
  stopConditions: ["production DB/R2 접근 필요", "schema 변경 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["system administrator guard 유지"],
  dbImpact: "guarded",
  dbImpactNotes: ["DB metadata read와 snapshot insert path가 존재하나 이번 roadmap 화면은 write하지 않는다."],
  r2Impact: "read_only",
  r2ImpactNotes: ["R2 reconciliation은 후속 productization 과제로 남았다."],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["Build", "Mutation Audit", "system-storage-usage-real-data-contract"],
  manualTests: ["시스템 관리자 저장공간 화면 확인"],
  expectedChangeAreas: ["lib/billing/storageUsageRepository.ts", "tools/pipeline/*", "tests/*"],
  recommendedCommitMessage: "feat: add system storage usage automation foundation",
  nextVersionBoundary: ["0.24.11에서 id-control과 roadmap 조회 화면을 정리한다."],
  completionConditions: ["구현 완료", "verify-safe PASS", "commit hash 존재", "push 완료"],
  result: completedResult(
    ["a4c1921d86e68de27e282150b4195cff27d76d0c", "644e8825dafaf38ca0c736eed6c4efcc33fe38d5"],
    "system-admin-storage PASS",
  ),
};

const ROADMAP_0_24_11: RoadmapVersionDetail = {
  version: "0.24.11",
  title: "시스템 관리자 ID 제어와 roadmap 기준판",
  status: "in_progress",
  userSummary: [
    "/id-control에서 dev/test 계정 전환과 원래 세션 복원을 더 명확히 본다.",
    "/roadmap에서 버전별 작업 계획과 검증 상태를 시스템 관리자가 조회한다.",
  ],
  visibleChanges: [
    "/dev/test-console은 guard 통과 후 /id-control로 이동한다.",
    "/roadmap은 시스템 관리자 전용이며 편집, 저장, 삭제 기능 없이 버전 계획을 보여준다.",
  ],
  expectedUi: [
    "/roadmap은 한글 표시를 기본으로 하고 현재 앱 버전, 개발 진척도, 제품화 진척도를 보여준다.",
    "각 버전은 요약과 상세 개발 기준을 함께 제공한다.",
  ],
  developmentPurpose: ["0.24.12 일반 사용자 기능 개발 전에 Codex와 사용자가 같은 개발 기준판을 보게 한다."],
  developmentUiStructure: ["system-admin guard가 있는 read-only Next.js server page", "canonical roadmap data facade"],
  scope: ["/id-control", "/dev/test-console redirect", "/roadmap", "roadmap data/doc sync", "verification fingerprint reuse"],
  outOfScope: ["일반 사용자 기능 구현", "roadmap 편집 UI", "DB/R2 write"],
  implementationPrinciples: ["조회 전용", "한글 표시", "기존 system-admin guard 유지"],
  successConditions: ["route guard contract PASS", "roadmap Korean label contract PASS", "read-only contract PASS"],
  failureConditions: ["편집/저장 action 추가", "DB/R2 write 추가", "production guard 약화"],
  cautions: ["실제 Google 로그인과 계정 전환은 일부 수동 확인이 남는다."],
  stopConditions: ["권한 정책 변경 필요", "production 접근 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["active system administrator만 접근한다."],
  dbImpact: "none",
  dbImpactNotes: ["roadmap 화면 자체는 DB를 읽거나 쓰지 않는다."],
  r2Impact: "none",
  r2ImpactNotes: ["R2 영향 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["id-control-roadmap", "roadmap-development-contract"],
  manualTests: ["system administrator로 /roadmap 접근", "일반 사용자 접근 차단"],
  expectedChangeAreas: ["app/roadmap/page.tsx", "lib/internal/roadmap/*", "docs/productization-roadmap.md", "tools/pipeline/*"],
  recommendedCommitMessage: "feat: expand roadmap into development contract",
  nextVersionBoundary: ["0.24.12부터 일반 사용자 workspace/worker 기능 구현을 시작한다."],
  completionConditions: ["구현 완료", "verify-safe PASS", "commit hash 존재", "push 완료", "4. newest 산출물 생성"],
  result: {
    completedSummary: ["진행 중. 이번 작업에서 roadmap 기준판과 handoff 자동 생성을 구축한다."],
    commitHash: "",
    verificationResult: "",
    remainingIssues: ["작업 완료 후 실제 commit hash와 verification result를 roadmap result에 반영해야 한다."],
    userConfirmationRequired: false,
    userConfirmationResult: "이번 작업은 개발 인프라 구축이며 사용자 수동 UI 판단이 완료 조건은 아니다.",
  },
};

const ROADMAP_0_24_13: RoadmapVersionDetail = {
  version: "0.24.13",
  title: "작업지시서와 발주서 PDF",
  status: "planned",
  userSummary: ["작업지시서와 발주서 PDF 생성, 저장, 재생성 정책을 정한다."],
  visibleChanges: ["PDF 다운로드/인쇄/보관 흐름이 업무 목적별로 정리된다."],
  expectedUi: ["PDF 버튼 위치, 생성 상태, 실패 메시지를 화면과 PDF 결과가 일치하도록 정리한다."],
  developmentPurpose: ["PDF Worker, R2 저장, 임시/최종 PDF 정책을 확정한다."],
  developmentUiStructure: ["workorder PDF와 supplier/material-order PDF를 목적별로 분리한다."],
  scope: ["PDF generation", "Worker/R2 integration", "filename rules", "regeneration policy"],
  outOfScope: ["0.24.12 workspace shell/density 변경"],
  implementationPrinciples: ["사람 눈 PDF 비교가 필요한 항목은 사용자 확인 전 완료하지 않는다."],
  successConditions: ["PDF contract PASS", "manual PDF comparison complete"],
  failureConditions: ["R2 write 정책 미확정 상태에서 production 저장", "화면/PDF 내용 불일치"],
  cautions: ["R2 mutation은 명시 승인 필요"],
  stopConditions: ["PDF 표시 정책 결정 필요", "R2 저장 정책 결정 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["PDF 조회/생성 권한을 업무 권한과 일치시킨다."],
  dbImpact: "pending_decision",
  dbImpactNotes: ["PDF attachment 등록 정책에 따라 DB write가 필요할 수 있다."],
  r2Impact: "pending_decision",
  r2ImpactNotes: ["임시/최종 PDF R2 저장 정책 결정 필요"],
  migrationRequired: false,
  migrationNotes: "기본 전제는 DB Migration 없음",
  automaticTests: ["PDF policy contract", "Worker/R2 adapter contract"],
  manualTests: ["화면/PDF 비교", "다운로드/인쇄 QA"],
  expectedChangeAreas: ["app/api/workorders/*generated*", "cloudflare/pdf-generator-worker/*", "lib/functions/pdfPolicyCatalog.ts"],
  recommendedCommitMessage: "feat: finalize workorder and material order pdf flow",
  nextVersionBoundary: ["0.24.14는 Functions, Simulator, PowerShell 자동화를 다룬다."],
  completionConditions: ["verify-safe PASS", "PDF 수동 확인 완료", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: true, userConfirmationResult: "미확인" },
};

const ROADMAP_0_24_14: RoadmapVersionDetail = {
  version: "0.24.14",
  title: "Functions, Simulator, PowerShell 자동화 정리",
  status: "planned",
  userSummary: ["개발/테스트 도구와 simulator 실행 흐름을 안전하게 정리한다."],
  visibleChanges: ["/functions, /id-control, PowerShell 메뉴에서 테스트 환경 상태를 더 명확히 본다."],
  expectedUi: ["dev/test 도구는 production 차단과 system-admin guard를 계속 유지한다."],
  developmentPurpose: ["Seed/Reset/Cleanup/R2 demo 실행 정책과 dry-run contract를 정리한다."],
  developmentUiStructure: ["PowerShell fixed wrapper와 simulator command를 명확히 분리한다."],
  scope: ["/functions", "Simulator", "PowerShell menus", "contract/E2E/Smoke/Permissions"],
  outOfScope: ["일반 사용자 UI 기능 확장", "PDF 정책 결정"],
  implementationPrinciples: ["execute mode는 명시 승인 없이는 실행하지 않는다."],
  successConditions: ["functions/simulator/pipeline contracts PASS"],
  failureConditions: ["production 접근", "destructive command guard 약화"],
  cautions: ["DB/R2 mutation은 별도 승인 필요"],
  stopConditions: ["Seed/Reset/Cleanup execute 필요", "production binding 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["system-admin/dev-test guard 유지"],
  dbImpact: "guarded",
  dbImpactNotes: ["dry-run과 execute를 분리한다."],
  r2Impact: "guarded",
  r2ImpactNotes: ["R2 demo create/delete는 명시 승인 필요"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["functions contract", "simulator contract", "PowerShell parse"],
  manualTests: ["destructive confirmation flow review", "Playwright report 확인"],
  expectedChangeAreas: ["tools/pipeline/*", "tools/simulator/*", "tests/functions-*"],
  recommendedCommitMessage: "feat: harden functions simulator automation",
  nextVersionBoundary: ["0.24.15는 통합 검증 체크포인트다."],
  completionConditions: ["verify-safe PASS", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: false, userConfirmationResult: "" },
};

const ROADMAP_0_24_15: RoadmapVersionDetail = {
  version: "0.24.15",
  title: "통합 검증 체크포인트",
  status: "verification_pending",
  userSummary: ["출시 전 남은 검증과 사용자 확인 항목을 한 번에 재계산한다."],
  visibleChanges: ["주요 화면, 권한, PDF, responsive, DB/R2 통합 상태가 PASS/미완료로 정리된다."],
  expectedUi: ["사용자 확인이 필요한 UI/PDF/responsive 항목은 완료와 분리해 표시한다."],
  developmentPurpose: ["제품화 readiness를 다시 산정하고 남은 차단 항목을 확정한다."],
  developmentUiStructure: ["검증 결과와 수동 QA 결과를 roadmap result에 반영한다."],
  scope: ["Build", "Mutation Audit", "contract tests", "E2E", "Smoke", "Permissions", "responsive", "PDF", "DB/R2 integration"],
  outOfScope: ["새 기능 추가"],
  implementationPrinciples: ["검증 실패를 숨기지 않고 실패/skip 이유를 분리한다."],
  successConditions: ["필수 자동 검증 PASS", "필수 수동 확인 완료", "origin/master sync"],
  failureConditions: ["검증 실패 은폐", "사용자 확인 전 완료 처리"],
  cautions: ["DB/R2 integration은 승인된 dev/test 대상에서만 수행한다."],
  stopConditions: ["실제 production 접근 필요", "사용자 판단 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["역할별 접근 결과를 구분한다."],
  dbImpact: "guarded",
  dbImpactNotes: ["dev/test 승인 범위 내 read 또는 rollback 가능한 smoke만 허용한다."],
  r2Impact: "guarded",
  r2ImpactNotes: ["R2 실제 작업은 별도 승인 필요"],
  migrationRequired: false,
  migrationNotes: "통합 검증 단계에서 migration이 발견되면 별도 버전으로 분리한다.",
  automaticTests: ["full verify-safe matrix", "E2E", "Smoke", "Permissions"],
  manualTests: ["real Google login", "role QA", "responsive QA", "PDF QA"],
  expectedChangeAreas: ["tests/*", "docs/productization-roadmap.md", "lib/internal/roadmap/*"],
  recommendedCommitMessage: "chore: complete productization validation checkpoint",
  nextVersionBoundary: ["이후 버전은 통합 검증 결과에 따라 결정한다."],
  completionConditions: ["검증 완료", "사용자 확인 완료", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: true, userConfirmationResult: "미확인" },
};

export const PRODUCTIZATION_ROADMAP: ProductizationRoadmapSummary = {
  appVersion: APP_VERSION,
  featureProgressPercent: 93,
  productizationProgressPercent: 77,
  currentWorkVersion: "0.24.11",
  nextWorkVersion: "0.24.12",
  canonicalPolicy:
    "새 버전 기능 작업 전에는 lib/internal/roadmap의 canonical 상세 명세와 docs/codex-current-state.md를 먼저 읽는다. /roadmap은 사용자와 ChatGPT/Codex가 함께 보는 조회 전용 개발 기준판이며, 화면에서 편집·추가·삭제·저장 기능을 제공하지 않는다.",
  statusLabels: ROADMAP_STATUS_LABELS,
  impactLabels: ROADMAP_IMPACT_LABELS,
  versions: [ROADMAP_0_24_10, ROADMAP_0_24_11, ROADMAP_0_24_12, ROADMAP_0_24_13, ROADMAP_0_24_14, ROADMAP_0_24_15],
};

export function getRoadmapVersionAnchor(version: string) {
  return `v-${version.replace(/\./g, "-")}`;
}
