import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_12: RoadmapVersionDetail = {
  version: "0.24.21.12",
  title: "DB Read-only Audit PowerShell Menu",
  status: "verification_pending",
  userSummary: [
    "개발·테스트 DB에서 reconciliation, constraint readiness, index readiness를 안전하게 실행하는 PowerShell 메뉴를 추가했다.",
  ],
  visibleChanges: ["개발/테스트 도구 메뉴 30~32번이 추가된다."],
  expectedUi: ["앱 사용자 화면 변화 없음"],
  developmentPurpose: ["Codex Sprint A 전 실제 DB 상태를 비파괴적으로 확인한다."],
  developmentUiStructure: ["PowerShell 메뉴와 결과 보고서"],
  scope: ["read-only audit runner", "dev/test fingerprint guard", "result files"],
  outOfScope: ["production execution", "schema mutation", "migration"],
  implementationPrinciples: ["SELECT/WITH only", "BEGIN READ ONLY", "approved dev/test DB only"],
  successConditions: ["three menu commands run safely", "report files created"],
  failureConditions: ["production target", "fingerprint mismatch", "mutation SQL token"],
  cautions: ["결과 행에 내부 식별자가 포함될 수 있으므로 외부 공유 금지"],
  stopConditions: ["unexpected schema mismatch", "query permission failure"],
  permissionImpact: "guarded",
  permissionNotes: ["승인된 dev/test DB에서만 실행"],
  dbImpact: "read_only",
  dbImpactNotes: ["DB mutation 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근·변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음 — read-only audit만 실행",
  automaticTests: ["db-readonly-audit-menu-contract", "unicode-encoding-contract"],
  manualTests: ["dev/test에서 메뉴 30, 31, 32 실행", "production 차단 확인", "결과 파일 생성 확인"],
  expectedChangeAreas: [
    "tools/pipeline/peacebypiece-auto-pipeline.ps1",
    "scripts/run-readonly-db-audit.mjs",
    "db/audits/*",
    "tests/db-readonly-audit-menu-contract.mjs",
  ],
  recommendedCommitMessage: "feat: add read-only database audit menus",
  nextVersionBoundary: ["0.24.22 Codex Sprint A 전 read-only DB 감사 결과를 확인한다."],
  completionConditions: [
    "메뉴 30~32 추가",
    "read-only guard 적용",
    "contract 통과",
    "사용자 로컬 build 통과",
  ],
  result: {
    completedSummary: [
      "개발·테스트 DB의 reconciliation, constraint, index 준비도 메뉴를 추가했다.",
      "production·fingerprint mismatch·mutation SQL 차단과 read-only transaction을 적용했다.",
    ],
    commitHash: "",
    verificationResult: "정적 contract 통과; 실제 DB 실행과 사용자 로컬 build 확인 필요",
    remainingIssues: ["dev/test DB 메뉴 실행", "사용자 로컬 TypeScript/build 확인"],
    userConfirmationRequired: true,
    userConfirmationResult: "사용자가 테스트 메뉴 추가를 승인함",
  },
};
