import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_26: RoadmapVersionDetail = {
  version: "0.24.26",
  title: "Public Signup, Verification, Approval, and Trial",
  status: "in_progress",
  userSummary: [
    "Defines the executable roadmap for public signup, verified identity, system-admin approval, and Trial provisioning.",
    "This roadmap records the final owner policy as implementation criteria; it does not start product code in the metadata-only canonicalization step.",
  ],
  visibleChanges: [
    "Public WAFL signup entry and Trial CTA are planned for the next implementation step.",
    "Pending, rejected, and not-yet-approved users will receive limited state screens instead of workspace access.",
  ],
  expectedUi: [
    "Public signup CTA starts Google OAuth and requires an email-verified Google profile.",
    "New company applicants submit required business information, consent evidence, intended plan, and a business certificate.",
    "System administrators review, request correction, reject, or approve the application through an internal queue.",
  ],
  developmentPurpose: [
    "Create the public signup and approval boundary without weakening authenticated workspace, system-admin, tenant, or destructive-action guards.",
    "Provision company, first admin, membership, role/permission, subscription, Trial quota, audit, and business-certificate ownership atomically and idempotently at approval time.",
  ],
  developmentUiStructure: [
    "Public website/app boundary with signup/login entry points.",
    "Authenticated pre-approval state pages for draft, submitted, reviewing, changes_requested, rejected, canceled, and provisioning_failed users.",
    "System-admin review list/detail, approval-only certificate viewer, correction request, rejection, approval, retry, and repair surfaces.",
  ],
  scope: [
    "Public signup CTA and Google OAuth entry.",
    "Google profile email_verified=true enforcement.",
    "Unjoined verified-user state.",
    "New company application creation.",
    "Existing company join path prefers invitation/code over public company search.",
    "Reuse or extend join_requests and invitations where the existing model fits.",
    "System-admin review, correction request, rejection, approval, retry, and repair.",
    "Pending/rejected limited state screens.",
    "Block /workspace and workspace APIs before approval.",
    "Approval-time provisioning of company, user, company_member, role/permission, company_subscription, Trial, storage quota, member limit, audit, and business-certificate ownership link.",
    "Idempotent provisioning and provisioning_failed recovery.",
    "Trial: 7 days, 100MB storage, 3 members.",
    "Trial starts when the system administrator approves the signup.",
    "Business certificate is required for production new-company applications.",
    "Dev/test fixtures may relax certificate requirements only where explicitly guarded.",
    "Approval viewer only for business certificate; no WAFL-provided download path.",
    "Audit trace, IDOR defense, duplicate prevention, email normalization, and signup abuse controls.",
  ],
  outOfScope: [
    "Actual PG payment charge, payment-method registration, payment-reference storage, and subscription operation; this remains 0.24.31.",
    "Storing raw card data, fake card placeholders, fake payment references, or PG-neutral payment references.",
    "System catalog, size, or POM row provisioning; this remains 0.24.27.",
    "Executing DB migrations without explicit user approval or against production.",
    "Production DB/R2 mutation during roadmap creation.",
    "Cloudflare Worker source changes unless a later implementation step explicitly requires them.",
    "0.24.28 PDF/R2 lifecycle product code.",
    "0.24.30 storage enforcement product code.",
  ],
  implementationPrinciples: [
    "Final owner policy documents are the source of truth; this roadmap structures settled policy instead of reopening decisions.",
    "Signup identity, company application, business evidence, and provisioning state must be explicit and auditable.",
    "Approval provisioning must be idempotent and must not expose partially-created companies as active workspaces.",
    "Do not require card registration or payment-method readiness in 0.24.26; payment and payment-reference storage are reserved for 0.24.31.",
    "Do not trust client-public environment variables for server authorization or runtime decisions.",
    "System-admin certificate access is approval-only and viewer-only; general customer business files remain isolated.",
    "Destructive simulator, reset, seed, cleanup, DB/R2 mutation, and migration actions remain separately guarded.",
  ],
  successConditions: [
    "Signup requires a Google profile with email_verified=true.",
    "Unapproved users cannot access /workspace or workspace APIs by direct URL/API call.",
    "Application statuses cover draft, submitted, reviewing, changes_requested, approved, rejected, canceled, and provisioning_failed.",
    "System-admin can approve, reject, and request correction with audit trace.",
    "Approval creates company, first admin, company_member, role/permission, subscription, Trial, quota, audit, and business-certificate ownership link exactly once.",
    "Trial values are 7 days, 100MB, and 3 members, starting at approval time.",
    "Business certificate access is limited to approval viewer and blocks WAFL-provided download.",
    "Duplicate email, company, and business-registration paths are denied or routed to safe review states.",
    "Signup abuse controls include rate limit and a CAPTCHA decision record.",
  ],
  failureConditions: [
    "Public signup allows unverified Google email.",
    "Pending/rejected users can access workspace content or APIs.",
    "Approval can create duplicate active companies, duplicate first admins, or partial active state.",
    "Raw card data, fake payment placeholders, fake payment references, or PG-neutral payment references are stored.",
    "System catalog, size, or POM rows are created in 0.24.26.",
    "Business certificate files become downloadable through a WAFL route.",
    "A DB migration or data mutation is executed without explicit approval, rollback planning, or approved dev/test fingerprint guard.",
    "Trial values regress to legacy 1GB or 5 members.",
  ],
  cautions: [
    "Trial-end read-only/download grace is not a new open decision for normal completed Trial: final policy says no post-Trial read-only grace.",
    "Rate limit/CAPTCHA mechanism is a technical design item and must be recorded before implementation.",
    "Migration may be required for signup request/application state, but creation and execution require separate approval.",
  ],
  stopConditions: [
    "A new DB schema migration or production migration becomes necessary beyond the explicitly approved signup schema migration.",
    "Production DB/R2/PG access or mutation becomes necessary.",
    "A new product-policy decision not covered by documents 26, 31, 20, 21, or 30 is discovered.",
    "Existing public website source cannot be located and implementation would require a new source-structure decision.",
  ],
  permissionImpact: "guarded",
  permissionNotes: [
    "Public routes remain unauthenticated only where explicitly public.",
    "Pending/rejected authenticated users receive limited state access.",
    "System-admin review routes require active system-admin actual session.",
    "Workspace/company APIs require approved company membership and effective-session permissions.",
  ],
  dbImpact: "pending_decision",
  dbImpactNotes: [
    "Signup applications and signup application files were created by the approved dev/test schema migration.",
    "Signup consent evidence now has a separate additive migration, read-only compatibility audit, post-apply audit, and rollback smoke; the consent migration was executed once against the approved dev/test DB fingerprint.",
    "Business certificate metadata, review/audit state, and idempotent provisioning records may still require additional schema work.",
    "Any additional migration must be read-only reconciled and separately approved before execution.",
  ],
  r2Impact: "guarded",
  r2ImpactNotes: [
    "Business certificate upload/storage may use R2 through a narrowly scoped approval-only viewer lifecycle.",
    "No broad customer operational-file access is granted to system-admin.",
    "Actual certificate R2 integration is guarded by a dev/test-only runner, approved DB fingerprint, AND-required Worker URL/host/environment fingerprints, exact confirmation phrase, sanitized manifest cleanup, and residual verification.",
    "Signup certificate R2 keys use the canonical prefix signup-applications/{applicationId}/business-registration/{fileId}.{png|jpg|pdf}; the R2 upload Worker source must explicitly allow this prefix before actual integration can pass.",
    "No R2 mutation is executed without a separate user approval command.",
  ],
  migrationRequired: true,
  migrationNotes:
    "Created signup_applications, signup_application_files, and signup_application_consents and executed the approved signup and consent schema migrations once against the approved dev/test DB fingerprint 01e5dcc7fea3. Production migration and any additional DB mutation remain forbidden without separate approval.",
  automaticTests: [
    "signup email_verified contract",
    "pending/rejected workspace route/API guard contract",
    "system-admin application review contract",
    "business certificate approval viewer no-download contract",
    "R2 upload Worker signup certificate key policy contract",
    "idempotent provisioning contract",
    "Trial policy contract",
    "duplicate email/company/business registration contract",
    "signup audit contract",
    "roadmap contract",
    "roadmap development contract",
    "unicode encoding contract",
    "tsc --noEmit",
    "next build",
  ],
  manualTests: [
    "Public signup CTA and login entry on PC/mobile.",
    "Google OAuth verified-email path and unverified-email rejection.",
    "System-admin review approve/reject/correction flow.",
    "Pending, rejected, changes-requested, approved, and provisioning_failed user screens.",
    "Certificate viewer-only behavior on Vercel PC/mobile.",
    "Workspace/API direct access blocking before approval.",
  ],
  expectedChangeAreas: [
    "public website or public route group after source-location confirmation",
    "auth/session onboarding state",
    "signup application repository/service/API",
    "business certificate upload/viewer API",
    "system-admin onboarding review UI/API",
    "trial/subscription provisioning service",
    "workspace route/API guards",
    "audit and notification scheduling",
    "tests and roadmap docs",
  ],
  futureDependencies: [
    "0.24.28 PDF and R2 Lifecycle: actual R2 lifecycle simulator, valid PNG/JPEG/PDF fixtures, restore/delete/404/orphan/reconcile/rollback coverage, bounded performance fixtures, and production mutation ban.",
    "0.24.30 Storage Enforcement, Termination, and Automatic Deletion: capacity profile 0%, <1%, 10%, 20%, 30%, 50%, 70%, 90%, 99%, 100%, 110%, Trial 100MB linkage, upload preflight, warning/grace/termination/deletion scheduling, and profile apply/verify/restore commands.",
    "0.24.31 PG Billing and Subscription Operations: payment-method registration, PG-neutral payment references, billing keys, Trial-end charging, and subscription operation.",
    "Capacity fixture backlog: H/I/J DB scenario and attachment manifest expectations differ and must be resolved through future profile apply design, not immediate mutation.",
  ],
  userDecisionsRequired: [
    "No settled product policy is reopened in this roadmap.",
    "Technical implementation must still choose the existing public website source location before product code begins.",
    "Technical implementation must choose rate-limit/CAPTCHA mechanism before public signup launch.",
    "Any additional migration scope, production migration, backfill, or provisioning data mutation requires separate explicit approval before DB execution.",
  ],
  preparationHistory: [
    {
      commitHash: "ef0602de1c99fea54cd63cc69c110a3e7ad3a79d",
      summary: [
        "Canonical detailed roadmap file was created and registered.",
        "0.24.28 R2 lifecycle and 0.24.30 storage enforcement reserved dependencies were recorded.",
        "H/I/J capacity fixture mismatch was recorded as backlog without mutation.",
      ],
      verificationResult:
        "PASS: roadmap-0.24.26 contract; roadmap development contract; unicode encoding contract; targeted ESLint; tsc --noEmit; next build; git diff --check; git diff --cached --check.",
    },
    {
      commitHash: "0fadb95e9561fb89d0198b393599d419d121e5bd",
      summary: [
        "Approved dev/test signup migration was applied once after read-only compatibility audit and guard verification.",
        "Post-apply schema audit returned findings 0 and the schema smoke check completed inside a rolled-back transaction.",
        "The milestone is a schema foundation only: production migration, business data mutation, R2 mutation, public signup UI, approval UI, and provisioning execution remained out of scope.",
      ],
      verificationResult:
        "PASS: signup migration apply, post-apply schema audit findings 0, schema smoke rollback, roadmap/update contracts, tsc --noEmit, next build, git diff --check, git diff --cached --check.",
    },
  ],
  recommendedCommitMessage: "0.24.26 공개 가입 승인 Trial 로드맵 정리",
  nextVersionBoundary: [
    "0.24.27 - System Catalog, Sizes, and POM.",
    "0.24.28 - PDF and R2 Lifecycle; reserved R2 lifecycle simulator and bounded performance fixture scope are recorded as future dependencies.",
    "0.24.30 - Storage Enforcement, Termination, and Automatic Deletion; capacity profile and fixture separation are recorded as future dependencies.",
  ],
  completionConditions: [
    "Final policy documents are checked before implementation.",
    "Existing public website source location is confirmed before duplicate implementation.",
    "Migration scope is presented and approved before any migration file or execution.",
    "Contracts, typecheck, build, commit, push, and 4. Newest handoff complete after implementation.",
  ],
  result: {
    completedSummary: [
      "Canonical detailed roadmap and schema/repository preparation design are complete.",
      "Signup product implementation started with a migration-backed schema foundation and TypeScript domain/repository/service contracts.",
      "The approved dev/test signup migration was executed once: preflight compatibility audit PASS, migration apply PASS, post-apply schema audit PASS, schema smoke rollback PASS, and smoke row residue 0.",
      "PostgreSQL signup repository and applicant API/session foundation are wired for draft/create/read/update/submit/status/cancel, applicant ownership checks, duplicate mapping, and compare-and-set status transitions.",
      "Google OAuth preserves email_verified and the signup entry rejects unverified Google profiles without routing existing member/system-admin/invitation login into signup.",
      "Pending signup applicants are blocked from workspace page/API access before approval while actual system-admin internal APIs keep the actual-session boundary.",
      "Normal workspace/system-admin WAFL sessions now take precedence over stale signup applicant cookies, and normal login clears the signup applicant cookie.",
      "Public signup draft/status UI is available through the existing public entry and /pending?type=signup, with draft save, submit/resubmit, status display, cancel, logout, and safe error/loading states.",
      "Signup required consent evidence is implemented as a separate applied dev/test schema migration and API/UI/service foundation; first-click submit creates the draft, stores server-owned consent evidence, and immediately submits.",
      "Signup OAuth callback errors now return safe signup pending error codes instead of leaking raw provider/internal messages into the signup route.",
      "Signup business certificate foundation is implemented as code only: applicant certificate metadata/upload/revoke APIs, public signup upload UI, strict extension/MIME/header validation, active-unique-compatible replacement transaction order, DB-first revoke, exact-key post-commit cleanup attempts, and a system-admin approval-only inline viewer foundation.",
      "R2/Worker cleanup and certificate viewer failure logs are sanitized to safe operation/reason/status/retryable/presence fields without raw Worker body, signed URL/query, secret, raw storage key, or provider message logging.",
      "A guarded dev/test certificate R2 integration harness and PowerShell menus 44/45 are implemented; preflight is an explicit read-only transaction with rollback, actual execution requires all DB/R2 fingerprints to match, and the runner separates actual upload/replace/revoke/residual results from validation-only and static/mock checks.",
      "Production API and the integration runner share the certificate upload/delete orchestration module; runner-specific SQL is limited to dedicated fixture application setup, residual checks, and exact cleanup.",
      "Certificate preflight PASS was confirmed with runtime development and approved DB/Worker fingerprints. The earlier actual integration attempt failed at stage png-worker-put with safe code R2_WORKER_REQUEST_FAILED_400, residual DB rows 0, residual R2 objects 0, and tracked R2 keys 0.",
      "The direct cause of the HTTP 400 was the deployed R2 upload Worker key allowlist missing the canonical signup-applications/{applicationId}/business-registration/{fileId}.{png|jpg|pdf} prefix. The Worker source is patched to version 0.13.70 and the dev/test Worker deployment is now reflected by the passing integration fingerprints.",
      "The PostgreSQL 42702 ambiguous_column failure after PDF replacement was fixed by qualifying certificate JOIN SELECT columns in both the production repository and integration adapter while keeping mapper aliases stable; the runner now records active-certificate-before-revoke/lookup before revoke delete diagnostics.",
      "Actual certificate R2 integration PASS was confirmed once after the 42702 fix: PNG upload PASS, JPEG replacement PASS, PDF replacement PASS, revoke PASS, residual cleanup PASS, residual DB rows 0, residual R2 objects 0, production mutation false, and schema migration false.",
      "System-admin signup review list/detail foundation is implemented with actual-active-system-admin route/API guards, bounded pagination, consent evidence display, certificate inline viewer wiring, safe detail fields, and submitted/reviewing correction/rejection transition APIs.",
      "Review transitions are limited to submitted -> reviewing, submitted/reviewing -> changes_requested, and submitted/reviewing -> rejected with compare-and-set status checks, reason validation for terminal/correction actions, same-origin mutation guards, safe error codes, and no approve/provisioning execution.",
      "Orphan cleanup backlog table was not added, and broad orphan/reconciliation/range/stream/performance verification remains reserved for 0.24.28.",
      "Repo-state/build-result metadata now distinguishes DB Migration Applied, previous DB Schema Mutation, Schema Migration This Run, Dev/Test DB Test-Data Mutation, Dev/Test R2 Mutation, Production Mutation, and Production Migration; schema mutation remains tied to the previously approved dev/test signup and consent schema migrations while certificate integration records dev/test DB/R2 fixture mutation with residual DB/R2 0.",
      "The draft requires explicit email_verified evidence, normalized 10-digit business registration matching, application-owned certificate files, and provisioning failure handling through the approval operation.",
      "0.24.28 and 0.24.30 reserved dependency notes remain recorded in roadmap/backlog docs.",
    ],
    commitHash: "0fadb95e9561fb89d0198b393599d419d121e5bd",
    verificationResult:
      "Foundation verification PASS so far: runtime development, approved DB fingerprint 01e5dcc7fea3, signup migration SHA-256 b0f83b1026891099a65ae1b8e57f6269db52e00d1d9c6066b1b227039f16a395, consent migration SHA-256 7b6f1f7f220925b0090c6765222d0805b5a9cfd40615c4648dbae2f9f3fe5eea, preflight findings 0, migration apply PASS, post-apply findings 0, rollback smoke residual rows 0, certificate integration PASS, PNG/JPEG/PDF/revoke PASS, residual DB rows 0, residual R2 objects 0, production mutation false, schema migration this run false.",
    remainingIssues: [
      "Decide technical rate-limit/CAPTCHA mechanism during implementation planning.",
      "Continue approval/provisioning, notification email, Trial workspace/session linkage, and remaining live viewer verification after the certificate + review foundation is committed/pushed.",
      "Production migration and any additional DB schema/data/R2 mutation require separate explicit approval.",
    ],
    userConfirmationRequired: true,
    userConfirmationResult:
      "Production migration, public signup UI/OAuth callback changes, API wiring, and provisioning execution require later explicit work steps.",
  },
};
