import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_20: RoadmapVersionDetail = {
  version: "0.24.20",
  title: "Functions/Simulator/PowerShell 자동화 확장",
  status: "planned",
  userSummary: ["Functions 구조를 실제 자동화와 더 강하게 연결해 QA 실행 흐름을 정리한다."],
  visibleChanges: ["/functions와 PowerShell 메뉴/profile/report가 seed/reset/cleanup/reconcile/test scenario launcher 상태를 더 일관되게 보여준다."],
  expectedUi: ["위험 실행은 계속 dev/test 전용, dry-run/confirmation 기준으로 제한된다."],
  developmentPurpose: ["0.24.14에서 정리한 functions 구조를 PowerShell menu/profile/report와 Simulator launcher에 연결한다."],
  developmentUiStructure: ["/functions catalog, PowerShell report, Simulator scenario launcher가 같은 상태 언어를 사용하도록 맞춘다."],
  scope: ["PowerShell menu/profile/report 연동", "seed/reset/cleanup/reconcile launcher 정리", "test scenario launcher 정리", "Functions catalog와 자동화 결과 연결"],
  outOfScope: ["실제 destructive execute", "PDF 정책 변경", "대형 UI 리팩터링", "DB schema 변경"],
  implementationPrinciples: ["실행 권한과 표시 권한을 분리하고, 위험 명령은 확인 없이는 실행하지 않는다."],
  successConditions: ["pipeline/functions/simulator contracts PASS", "report와 catalog 상태 일치", "destructive 실행 없음"],
  failureConditions: ["confirmation 우회", "production 접근", "manual git/npm 우회로 wrapper 계약 훼손"],
  cautions: ["PowerShell 변경은 parse와 contract를 함께 검증한다."],
  stopConditions: ["Seed/Reset/Cleanup execute 필요", "production binding 필요", "dependency 변경 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["system-admin/dev-test/action guard 유지"],
  dbImpact: "guarded",
  dbImpactNotes: ["dry-run/report 중심. execute는 별도 승인 필요"],
  r2Impact: "guarded",
  r2ImpactNotes: ["R2 create/delete 실행 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["PowerShell parse", "approved workflow contract", "functions/simulator automation contract"],
  manualTests: ["PowerShell menu와 /functions 표시 일치 검토"],
  expectedChangeAreas: ["tools/pipeline/*", "tools/simulator/*", "lib/functions/*", "tests/*"],
  recommendedCommitMessage: "feat: connect functions simulator pipeline automation",
  nextVersionBoundary: ["0.24.21은 고객 테스트 전 통합 검증 체크포인트다."],
  completionConditions: ["automation 확장 완료", "required tests PASS", "destructive 실행 없음", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: false, userConfirmationResult: "" },
};
