import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_25_4: RoadmapVersionDetail = {
  version: "0.24.25.4",
  title: "Policy Mismatch Correction for System-admin Boundary, Certificate Viewer, and Trial",
  status: "user_test_needed",
  userSummary: [
    "Corrects the 0.24.25 policy audit mismatches before starting 0.24.26.",
    "Keeps active system-admin internal APIs based on the actual signed-in actor while workspace APIs keep using the effective impersonated role.",
  ],
  visibleChanges: [
    "/id-control no longer gets stuck on a loading state when the options API fails.",
    "System-admin business certificate viewing remains viewer-only; application-provided download requests are blocked.",
  ],
  expectedUi: [
    "/id-control shows a safe error state with retry and a system dashboard link when target options cannot be loaded.",
    "Business certificate approval files remain available only through the approval viewer path.",
  ],
  developmentPurpose: [
    "Align the implemented 0.24.25 authorization/runtime boundary with the final owner policy documents.",
    "Remove implementation mismatches before the Public Signup, Verification, Approval, and Trial sprint begins.",
  ],
  developmentUiStructure: [
    "Use actual auth session for system-admin internal APIs.",
    "Keep effective session for workspace/customer role testing.",
    "Keep certificate access narrow to the approval viewer route and block app-provided download mode.",
  ],
  scope: [
    "System-admin actual/effective session boundary",
    "Business certificate approval viewer download blocking",
    "Trial policy constants: 7 days, 100MB, 3 members",
    "/id-control options loading/error UX",
    "Contracts and release documentation",
  ],
  outOfScope: [
    "0.24.26 Public Signup, Verification, Approval, and Trial implementation",
    "Public signup UI/API",
    "DB migration or DB/R2 mutation",
    "Cloudflare Worker code changes",
    "Dependency or lockfile changes",
  ],
  implementationPrinciples: [
    "Final owner policy documents are the source of truth when implementation and older roadmap text conflict.",
    "System-admin internal APIs use the actual signed-in active system administrator.",
    "Customer workspace APIs continue to use the effective impersonated session for role and permission checks.",
    "Business certificate download paths are blocked by the server, not only hidden in UI.",
    "Trial provisioning constants must match the canonical 7 day, 100MB, 3 member policy.",
  ],
  successConditions: [
    "Actual system-admin can call system APIs while impersonating a customer role.",
    "General customers and inactive/non-allowlisted system-admin users remain blocked from system APIs.",
    "Certificate viewer requests work for active system-admins but download query requests are blocked.",
    "Trial policy constants expose 7 days, 100MB, and 3 members.",
    "/id-control options failures render an error state instead of infinite loading.",
  ],
  failureConditions: [
    "System-admin internal APIs depend on the effective customer role.",
    "A business certificate approval route exposes app-provided download mode.",
    "Trial provisioning uses legacy 1GB or 5 member values.",
    "/id-control options failures remain stuck in loading.",
  ],
  cautions: [
    "Browser save behavior for an already displayed inline file cannot be fully controlled; this version blocks WAFL-provided download paths.",
    "Destructive Seed, Reset, Cleanup, DB/R2 mutation, migration, and purge safety boundaries are unchanged.",
  ],
  stopConditions: [
    "A DB migration becomes required.",
    "Production DB/R2 access or mutation becomes required.",
    "A policy decision outside the final owner documents becomes necessary.",
  ],
  permissionImpact: "guarded",
  permissionNotes: [
    "System-admin API scope now validates the actual auth session and active system-admin allowlist.",
    "Workspace permission checks remain effective-session based.",
  ],
  dbImpact: "read_only",
  dbImpactNotes: [
    "System-admin allowlist and existing metadata are read for guards.",
    "No schema or data mutation is included.",
  ],
  r2Impact: "read_only",
  r2ImpactNotes: [
    "Certificate viewer may create a read redirect through existing Worker URL creation.",
    "No R2 object creation, deletion, mutation, or Worker source change is included.",
  ],
  migrationRequired: false,
  migrationNotes: "DB migration none. Existing schema/defaults already use the 100MB and 3 member trial defaults.",
  automaticTests: [
    "targeted ESLint",
    "tsc --noEmit",
    "system-admin actual/effective session contract",
    "system-admin internal access contract",
    "certificate approval viewer no-download contract",
    "trial policy contract",
    "dev-test-context system-admin contract",
    "id-control error-state contract",
    "authorization runtime boundary contract",
    "workspace member session guard contract",
    "unicode encoding contract",
    "next build",
    "git diff --check",
    "git diff --cached --check",
  ],
  manualTests: [
    "Active system-admin: open /id-control, switch to a seed customer role, then verify system internal pages and APIs still work.",
    "Customer direct login: verify system internal pages and APIs remain blocked.",
    "System-admin certificate approval viewer: verify normal view works and download query is blocked.",
  ],
  expectedChangeAreas: [
    "lib/system/sessionScope.ts",
    "app/api/system/companies/onboarding/files/[fileId]/view/route.ts",
    "lib/billing/companyTrialPolicy.ts",
    "app/dev/test-console/DevTestConsoleClient.tsx",
    "tests/*",
    "docs/*",
    "lib/internal/roadmap/*",
    "lib/constants/version.ts",
  ],
  recommendedCommitMessage: "0.24.25.4 정책 불일치 보정",
  nextVersionBoundary: [
    "0.24.26 - Public Signup, Verification, Approval, and Trial",
    "Do not start public signup implementation in this correction version.",
  ],
  completionConditions: [
    "Implementation complete",
    "Required verification PASS or blockers reported",
    "Commit and push complete",
    "4. Newest contains only latest ZIP and matching repo-state",
  ],
  result: {
    completedSummary: [
      "System-admin API scope was corrected to validate the actual auth session.",
      "Business certificate approval viewer download requests were blocked.",
      "Trial constants were aligned to 7 days, 100MB, and 3 members.",
      "/id-control options loading now has a safe error/retry state.",
    ],
    commitHash: "7162f1a95b73cc1f995b47675d38337527c255cb",
    verificationResult:
      "PASS: targeted ESLint; tsc --noEmit; system-admin actual/effective session contract; system internal access contracts; certificate approval viewer no-download contract; Trial policy contract; dev-test-context system-admin contract; id-control error-state contract; authorization runtime boundary contract; workspace member session guard contract; unicode encoding contract; next build; git diff --check; git diff --cached --check.",
    remainingIssues: [
      "Vercel PC/mobile actual/effective session manual QA.",
      "/id-control switch/restore manual QA.",
      "Direct customer login system-route blocking manual QA.",
      "Business certificate inline viewer and download=1 blocking manual QA.",
      "Trial 7 days, 100MB, 3 members UI display manual QA.",
    ],
    userConfirmationRequired: true,
    userConfirmationResult:
      "Automatic contracts and build passed, but real-device UI and Vercel production/preview behavior still require manual confirmation.",
  },
};
