import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_15: RoadmapVersionDetail = {
  version: "0.24.15",
  title: "전체 화면/소스 리팩터링 감사",
  status: "planned",
  userSummary: ["모든 주요 화면과 소스를 감사해 공통화와 리팩터링 후보를 찾는다."],
  visibleChanges: ["사용자 화면을 크게 바꾸지 않고, 감사 결과와 수정 우선순위를 문서화한다."],
  expectedUi: ["대규모 UI 변경은 하지 않으며, 필요한 경우 후속 버전에 사용자 확인 필요 항목으로 넘긴다."],
  developmentPurpose: ["app/features/components 화면 소스를 분석해 WAFL 공통 컴포넌트 미적용, hardcoding, inline style, 중복 className, i18n 누락, 대형 파일 분리 후보를 찾는다."],
  developmentUiStructure: ["감사 중심 버전으로 코드 구조와 화면 컴포넌트 사용 현황을 분류한다."],
  scope: ["모든 app/features/components 화면 소스 분석", "WAFL 공통 컴포넌트 미적용 화면 찾기", "hardcoding/inline style/중복 className/i18n 누락 찾기", "util/common module 후보 정리", "대형 파일 분리 후보 정리"],
  outOfScope: ["대규모 실제 수정", "공통 컴포넌트 교체", "PDF/R2/Simulator 기능 구현"],
  implementationPrinciples: ["감사 버전과 실제 수정 버전을 분리한다."],
  successConditions: ["감사 범위와 발견 항목 문서화", "후속 0.24.16/0.24.17 수정 후보 분리", "build 또는 contract PASS"],
  failureConditions: ["감사 중 대형 리팩터링 수행", "기능 동작 변경", "사용자 확인 필요한 UI 변경을 완료 처리"],
  cautions: ["자동 변경은 최소화하고 발견 사항은 근거 파일과 함께 기록한다."],
  stopConditions: ["대규모 수정 필요", "제품 정책 결정 필요", "권한/데이터 shape 변경 필요"],
  permissionImpact: "none",
  permissionNotes: ["권한 동작 변경 없음"],
  dbImpact: "none",
  dbImpactNotes: ["DB 접근 또는 변경 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근 또는 변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["Build", "roadmap-development-contract"],
  manualTests: ["감사 결과 목록과 우선순위 검토"],
  expectedChangeAreas: ["docs/audits/*", "docs/productization-roadmap.md", "lib/internal/roadmap/*"],
  recommendedCommitMessage: "docs: audit screen source refactoring candidates",
  nextVersionBoundary: ["0.24.16은 감사 결과 중 반복 UI 구조를 WAFL 컴포넌트로 안전하게 교체한다."],
  completionConditions: ["감사 문서 완료", "대형 수정 없음", "required tests PASS", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: false, userConfirmationResult: "" },
};
