import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_11: RoadmapVersionDetail = {
  version: "0.24.21.11",
  title: "Database Source-of-Truth and Safe Migration Design",
  status: "verification_pending",
  userSummary: [
    "0.24.21.10 감사 결과를 바탕으로 DB source-of-truth, reconciliation, safe constraint/index, migration, dry-run, rollback 설계를 확정한다.",
  ],
  visibleChanges: ["앱 UI 변화 없음"],
  expectedUi: ["사용자 화면 변화 없음"],
  developmentPurpose: [
    "0.24.22 Codex Sprint A 전에 membership, billing, workorder, file lifecycle, tenant 권한의 안전한 정리 순서를 마련한다.",
  ],
  developmentUiStructure: ["canonical 설계 문서와 실행 금지 상태의 audit/dry-run SQL 초안만 추가"],
  scope: [
    "domain별 canonical source-of-truth matrix",
    "중복·고아·충돌 탐지용 read-only reconciliation SQL",
    "PK/FK/unique/check/timestamp/ID 정책",
    "실제 query predicate 기반 index 유지·검토·추가 후보",
    "membership/billing/workorder/file lifecycle 단계적 migration과 rollback",
    "RLS 도입 전제와 stop condition",
    "결제·삭제·사이즈/POM·PDF 신규 구조 DDL 초안",
  ],
  outOfScope: [
    "SQL 실행",
    "migration 적용",
    "DB/R2 mutation",
    "테이블·컬럼·index 삭제",
    "production 접근",
    "package/lockfile 변경",
  ],
  implementationPrinciples: [
    "모든 destructive 변경 전에 reconciliation 결과가 0건이어야 한다.",
    "새 constraint는 NOT VALID 또는 staged backfill 후 VALIDATE 순서를 우선한다.",
    "index는 실제 query predicate와 EXPLAIN evidence 없이 추가하지 않는다.",
    "RLS는 application tenant guard를 대체하지 않고 defense in depth로 도입한다.",
    "rollback은 schema와 application compatibility window를 함께 보장한다.",
  ],
  successConditions: [
    "canonical source-of-truth matrix 완성",
    "read-only reconciliation SQL 제공",
    "safe DDL draft와 migration/rollback 단계 문서화",
    "0.24.22 구현 전 stop/go 기준 확정",
  ],
  failureConditions: [
    "실데이터 확인 없이 destructive migration 확정",
    "기존 index 중복을 확인하지 않고 추가",
    "RLS 존재를 근거 없이 가정",
    "SQL/DB/R2 실행",
  ],
  cautions: [
    "DDL 초안은 실행용 migration이 아니라 검토용 설계다.",
    "deployed DB schema/RLS drift와 실데이터 충돌은 dev/test에서 별도 확인해야 한다.",
  ],
  stopConditions: [
    "reconciliation query가 충돌·고아 데이터를 반환",
    "deployed schema가 full_reset.sql과 다름",
    "외부 job/writer가 legacy table을 사용",
    "production 데이터 접근이 필요",
  ],
  permissionImpact: "read_only",
  permissionNotes: ["권한 코드는 변경하지 않고 RLS/tenant 계획만 설계한다."],
  dbImpact: "read_only",
  dbImpactNotes: ["SQL 파일을 생성하지만 실행하지 않는다."],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근·변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음 — migration 설계와 dry-run 초안만 제공",
  automaticTests: ["db-safe-migration-design-contract", "unicode-encoding-contract"],
  manualTests: ["source-of-truth matrix, reconciliation SQL, stop condition 검토"],
  expectedChangeAreas: [
    "docs/project/28-database-source-of-truth-safe-migration-design.md",
    "db/audits/0.24.21.11-reconciliation-readonly.sql",
    "db/audits/0.24.21.11-safe-ddl-draft.sql",
    "lib/internal/roadmap/*",
  ],
  recommendedCommitMessage: "docs: design database source of truth and safe migrations",
  nextVersionBoundary: [
    "0.24.22 Codex Sprint A actual implementation boundary를 유지한다.",
    "실제 DB migration은 reconciliation과 사용자 승인 후 별도 버전에서만 수행한다.",
  ],
  completionConditions: [
    "canonical 설계 문서 생성",
    "read-only reconciliation SQL 생성",
    "safe DDL draft 생성",
    "contract PASS",
    "commit/push 완료",
  ],
  result: {
    completedSummary: [
      "membership, billing, workorder, attachment lifecycle의 canonical source-of-truth를 정의했다.",
      "충돌·고아 탐지 SQL과 staged constraint/index/RLS/migration/rollback 원칙을 작성했다.",
    ],
    commitHash: "",
    verificationResult: "정적 설계 및 SQL 구문 검토 완료; DB/R2/production 실행 없음",
    remainingIssues: [
      "deployed DB schema/RLS drift 확인",
      "dev/test 실데이터 reconciliation 실행",
      "query plan EXPLAIN evidence 확보",
      "실제 migration은 별도 승인 필요",
    ],
    userConfirmationRequired: false,
    userConfirmationResult: "사용자가 0.24.21.10/11 선행 DB 감사·설계 순서를 승인함",
  },
};
