import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_29: RoadmapVersionDetail = {
  version: "0.24.29",
  title: "Integrated Productization Checkpoint",
  status: "completed",
  userSummary: [
    "Integrates the completed 0.24.26 signup/provisioning, 0.24.27 system catalog, and 0.24.28 PDF/R2 lifecycle work into one QA-ready productization checkpoint.",
    "This version verifies the real user flow and release evidence before 0.24.30; it is not a new large feature sprint.",
  ],
  visibleChanges: [
    "System signup review list/detail copy is readable Korean and safer on narrow screens.",
    "System and company catalog pages use QA-ready Korean labels and responsive wrapping.",
    "A manual PC/mobile QA checklist is available for Vercel deployment validation.",
  ],
  expectedUi: [
    "Public signup and pending pages remain available through the existing Google signup flow.",
    "System-admin signup review, catalog, company catalog settings, workorder, and generated PDF viewer routes remain reachable through their existing navigation and guards.",
    "Manual QA status remains PENDING_USER_QA until the user validates real devices.",
  ],
  developmentPurpose: [
    "Confirm the end-to-end productization path from signup to approved workspace, company catalog, workorder, generated PDF, and inline viewer.",
    "Package verification metadata so repo-state reflects actual checkpoint evidence instead of repeated generic contract labels.",
  ],
  developmentUiStructure: [
    "Reuse existing public, system-admin, workspace, catalog, and workorder shells.",
    "Keep UI changes limited to direct checkpoint paths and avoid broad dashboard redesign.",
  ],
  scope: [
    "Version sync to APP_VERSION 0.24.29.",
    "Signup/provisioning regression using the existing guarded dev/test fixture runner.",
    "System catalog regression using the existing guarded dev/test fixture runner.",
    "PDF/R2 regression using 0.24.28 live integration evidence plus static/read-only policy regression.",
    "Responsive and copy cleanup for direct signup review and catalog QA surfaces.",
    "Mock/hardcoded production-path scan and backlog classification.",
    "Mutation audit with high-risk count recorded.",
    "Vercel readiness audit by source/config inspection without production mutation.",
    "Manual QA checklist document for PC/iPhone/iPad/Android validation.",
  ],
  outOfScope: [
    "Storage Capacity Profiles and Trial quota enforcement.",
    "PG/billing/payment method work.",
    "Notification email sending.",
    "Kakao external API sending.",
    "Customer dashboard redesign or /workers density redesign.",
    "New PDF/R2 lifecycle features beyond regression and QA readiness.",
    "System catalog model redesign or existing-company backfill.",
  ],
  implementationPrinciples: [
    "Do not infer unexecuted live tests as PASS.",
    "Use rollback/exact-cleanup dev/test fixtures only when integration is required.",
    "Keep raw DB URLs, Worker URLs, R2 keys, signed URLs, tokens, and secrets out of logs, client UI, docs, and repo-state.",
    "Keep actual/effective system-admin boundaries and tenant-scoped workspace permissions intact.",
  ],
  successConditions: [
    "Signup/provisioning, catalog, PDF/R2, authorization, route/navigation, responsive, and Vercel readiness contracts pass.",
    "Mutation audit reports high-risk 0 or all high-risk findings are fixed before commit.",
    "ESLint, typecheck, build, git diff checks, commit, push, and 4. Newest handoff complete.",
    "Manual QA checklist exists and repo-state records PENDING_USER_QA.",
  ],
  failureConditions: [
    "Production DB/R2/Worker mutation is required or detected.",
    "Residual dev/test fixture DB or R2 rows/objects are not 0 after an executed integration.",
    "A destructive migration or broad backfill is required.",
    "0.24.30 storage capacity work becomes necessary to finish the checkpoint.",
  ],
  cautions: [
    "0.24.29 is a user-confirmed checkpoint, not the previously listed historical Company-wide Export item.",
    "Manual visual/device QA is still user-owned and must not be marked complete by automated tests.",
  ],
  stopConditions: [
    "Worker fingerprint mismatch blocks a required live integration.",
    "Mutation audit finds a real high-risk production mutation path.",
    "Commit or push fails after successful validation.",
  ],
  permissionImpact: "guarded",
  permissionNotes: [
    "System signup review remains actual active system-admin only.",
    "Workspace catalog and workorder PDF paths remain effective company-role and tenant scoped.",
    "Applicant and regular customer users remain blocked from system routes.",
  ],
  dbImpact: "guarded",
  dbImpactNotes: [
    "No DB migration is added in 0.24.29.",
    "Dev/test integration runners may create fixture rows only under existing approval/fingerprint guards and must clean residual rows to 0.",
  ],
  r2Impact: "guarded",
  r2ImpactNotes: [
    "No new Worker source change is expected.",
    "0.24.28 PDF/R2 live integration evidence is reused unless PDF/R2 source changes require a minimal regression run.",
  ],
  migrationRequired: false,
  migrationNotes: "No schema migration is required for the integrated productization checkpoint.",
  automaticTests: [
    "0.24.29 integrated checkpoint contract",
    "signup/provisioning contracts and guarded integration",
    "system catalog contracts and guarded integration",
    "PDF/R2 policy, viewer, Worker signature, and lifecycle regression contracts",
    "authorization/runtime/session guard contracts",
    "route/navigation and responsive contracts",
    "mutation audit",
    "targeted ESLint",
    "tsc --noEmit",
    "next build",
    "git diff --check",
  ],
  manualTests: [
    "PC Chrome public signup, system review, catalog, workorder, and PDF viewer.",
    "iPhone Safari/Chrome signup pending and responsive review.",
    "iPad Safari workspace catalog and workorder PDF flow.",
    "Android Chrome workorder due-date and PDF viewer smoke.",
  ],
  expectedChangeAreas: [
    "lib/constants/version.ts",
    "app/layout.tsx",
    "components/system/signup/*",
    "app/(system)/system/catalog/page.tsx",
    "app/(workspace)/workspace/settings/catalog/page.tsx",
    "components/catalog/CompanyCatalogSettingsClient.tsx",
    "lib/internal/roadmap/*",
    "docs/codex-current-state.md",
    "docs/productization-roadmap.md",
    "docs/qa/0.24.29-integrated-productization-checkpoint.md",
    "tests/*0.24.29*",
    "tools/pipeline/peacebypiece-auto-pipeline.ps1",
  ],
  futureDependencies: ["0.24.30 Storage Capacity Profiles starts only after user QA feedback for this checkpoint."],
  recommendedCommitMessage: "0.24.29 가입 카탈로그 PDF 통합 체크포인트 완료",
  nextVersionBoundary: ["0.24.30 - Storage Capacity Profiles."],
  completionConditions: [
    "APP_VERSION 0.24.29",
    "Integrated checkpoint contracts and required regression checks pass.",
    "Mutation audit high-risk 0 is recorded.",
    "Commit/push complete and 4. Newest contains exactly the latest source ZIP and matching repo-state.",
    "Manual QA checklist is published with status PENDING_USER_QA.",
  ],
  result: {
    completedSummary: [
      "Signup review and catalog QA surfaces were cleaned up for readable Korean copy and narrow-screen wrapping.",
      "0.24.26 signup/provisioning, 0.24.27 catalog, and 0.24.28 PDF/R2 lifecycle evidence were integrated into a single checkpoint contract and verification metadata path.",
      "Manual QA checklist was created for PC, iPhone, iPad, and Android validation after Vercel deployment.",
    ],
    commitHash: "pending-final-commit",
    verificationResult: "pending final validation",
    remainingIssues: ["Manual real-device QA remains pending user validation."],
    userConfirmationRequired: true,
    userConfirmationResult: "PENDING_USER_QA",
  },
};
