import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_18: RoadmapVersionDetail = {
  version: "0.24.18",
  title: "제품화 기준 문서 확정",
  status: "completed",
  userSummary: ["제품화, 아키텍처, WAFL 컴포넌트, 출시 준비 기준을 네 개의 canonical 문서로 확정한다."],
  visibleChanges: ["사용자 화면과 기능 동작은 변경하지 않는다."],
  expectedUi: ["UI 변경 없음"],
  developmentPurpose: ["26일 이후 Codex 구현 Sprint가 동일한 제품화·아키텍처·QA 기준에서 시작하도록 한다."],
  developmentUiStructure: ["docs/project 아래 canonical 제품화 문서를 유지하고 /roadmap 계약과 버전을 동기화한다."],
  scope: ["Productization Bible", "Architecture Guide", "WAFL Component Standard", "Release Readiness Matrix", "버전 및 roadmap 동기화"],
  outOfScope: ["런타임 코드 변경", "PDF/R2 구현", "DB schema/migration", "permission policy 변경", "package/lockfile 변경"],
  implementationPrinciples: ["현재 구현을 사실대로 기록하고 미완료 항목은 readiness matrix에서 숨기지 않는다."],
  successConditions: ["네 문서 생성", "APP_VERSION/roadmap/current-state 일치", "roadmap contract 검증 가능"],
  failureConditions: ["구현되지 않은 기능을 완료로 표기", "운영 secret/binding 포함", "DB/R2 mutation"],
  cautions: ["Release Readiness Matrix의 Blocked/In Progress 항목은 후속 PB와 연결한다."],
  stopConditions: ["제품 정책 결정이 필요한 항목을 임의 확정해야 하는 경우"],
  permissionImpact: "none",
  permissionNotes: ["권한 코드와 정책 변경 없음"],
  dbImpact: "none",
  dbImpactNotes: ["DB 접근 및 변경 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근 및 변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["roadmap-development-contract", "TypeScript/build는 사용자 로컬 적용 후 확인"],
  manualTests: ["문서 내용과 release status의 제품 판단 검토"],
  expectedChangeAreas: ["docs/project/*", "docs/codex-current-state.md", "docs/README.md", "README.md", "lib/constants/version.ts", "lib/internal/roadmap/*"],
  recommendedCommitMessage: "docs: establish productization canonical standards",
  nextVersionBoundary: ["0.24.19는 PDF Specification, R2 Storage Policy, 관리자 운영 설계를 확정한다."],
  completionConditions: ["canonical docs 작성", "version sync", "DB/R2 mutation 없음", "patch 적용 후 build/contract PASS"],
  result: {
    completedSummary: [
      "Productization Bible을 추가해 제품화 원칙, PB lifecycle, release gate와 역할을 확정했다.",
      "Architecture Guide를 추가해 app/features/components/lib/tools 계층과 runtime, permission, PDF/R2 경계를 정의했다.",
      "WAFL Component Standard를 추가해 공통 component family, interaction, accessibility, adoption 기준을 정의했다.",
      "Release Readiness Matrix를 추가해 release blocking 영역과 required evidence를 명시했다.",
    ],
    commitHash: "patch 적용 및 commit 후 기록",
    verificationResult: "문서/roadmap 패치 생성 완료. build와 roadmap contract는 적용 환경에서 확인 필요.",
    remainingIssues: ["PDF/R2/관리자 운영 정책은 0.24.19에서 구체화한다.", "Browser/device/Playwright 세부 matrix는 0.24.20에서 확정한다."],
    userConfirmationRequired: true,
    userConfirmationResult: "제품화 canonical 기준과 readiness 상태 검토 필요",
  },
};
