import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_20: RoadmapVersionDetail = {
  version: "0.24.20",
  title: "Release Engineering 및 QA 기준",
  status: "verification_pending",
  userSummary: ["릴리스 완료 조건과 자동·수동 QA 범위, Playwright 확대 순서, 브라우저·실기기 기준을 canonical 문서로 정한다."],
  visibleChanges: ["사용자 업무 UI 변경 없이 release/QA 기준 문서와 roadmap 상태만 갱신된다."],
  expectedUi: ["후속 구현 버전부터 변경 위험도에 맞는 PC·모바일·태블릿 QA와 자동화 증적을 남긴다."],
  developmentPurpose: ["master/Vercel QA 흐름, release gate, QA risk tier, Playwright suite, browser/device coverage를 하나의 제품화 계약으로 고정한다."],
  developmentUiStructure: ["릴리스 화면과 QA 보고서는 문서의 gate/evidence 구조를 소비하며 임의의 ready 토글을 기준으로 삼지 않는다."],
  scope: ["Release Engineering", "QA Matrix", "Playwright 확대 계획", "Browser/Device Matrix", "0.24.19 정책 문서의 기존 결정값 정정"],
  outOfScope: ["실제 Playwright 테스트 코드 확대", "PDF/R2 엔진 구현", "production mutation", "DB schema 또는 dependency 변경"],
  implementationPrinciples: ["변경 위험도에 따라 자동/수동 증거를 차등 적용한다.", "Vercel은 1.0 전 실기기 QA 배포이며 production approval과 분리한다.", "정책 미결정은 실패를 숨기지 않고 affected feature blocker로 표시한다."],
  successConditions: ["release gate와 evidence 계약 존재", "QA risk tier/role/responsive/data matrix 존재", "Playwright suite/fixture/flake 정책 존재", "P0 browser/device baseline 존재", "0.24.19 기존 정책값과 실제 미결정 항목이 분리됨"],
  failureConditions: ["미검증 commit을 release-ready로 표시", "실기기 QA 없이 지원 완료 처리", "production mutation 실행", "사용자 결정값 임의 확정"],
  cautions: ["브라우저 current 버전은 실제 QA 시 OS/browser 버전을 기록해야 한다.", "binary PDF visual fidelity는 자동 계약만으로 완료 처리하지 않는다."],
  stopConditions: ["dependency/CI provider 변경 필요", "production release authority 변경 필요", "DB/R2 execute 필요"],
  permissionImpact: "none",
  permissionNotes: ["문서/roadmap 변경이며 permission guard를 변경하지 않는다."],
  dbImpact: "none",
  dbImpactNotes: ["DB read/write 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 read/write 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["TypeScript/build", "roadmap-development-contract", "문서 경로/version 계약", "Flat ZIP 무결성"],
  manualTests: ["docs index 링크", "/roadmap 현재 0.24.20/다음 0.24.21 표시", "release/QA 문서 상호 모순 검토"],
  expectedChangeAreas: ["docs/project/09-15", "docs/README.md", "docs/codex-current-state.md", "lib/constants/version.ts", "lib/internal/roadmap/*", "pending-tests.md"],
  recommendedCommitMessage: "docs: establish release engineering and qa standards",
  nextVersionBoundary: ["0.24.21은 PB Breakdown, Codex Ready Queue, Sprint Queue를 확정한다."],
  completionConditions: ["canonical 문서 작성", "0.24.19 정책 정정", "roadmap/version 동기화", "required checks PASS", "commit/push 완료"],
  result: {
    completedSummary: [
      "Release Engineering, QA Matrix, Playwright Plan, Browser/Device Matrix를 canonical 문서로 추가했다.",
      "기존 정책에서 확인된 plan quota, 80% warning/100% upload block, trash 30일, audited support access를 0.24.19 canonical 문서에 반영했다.",
    ],
    commitHash: "",
    verificationResult: "수동 패치 생성 완료; 적용 후 roadmap-development-contract와 build 확인 필요",
    remainingIssues: [
      "실제 Playwright suite 확대와 CI 실행",
      "계정 종료 export/grace 기간",
      "PDF final/superseded retention 기간",
      "four-eyes 필수 명령 목록",
      "최종 workorder/supplier PDF 생성 가능 상태",
      "고객 공개 audit 범위와 production incident escalation owner",
    ],
    userConfirmationRequired: true,
    userConfirmationResult: "정책상 실제 미결정 항목만 후속 사용자 결정 대기",
  },
};
