import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_15: RoadmapVersionDetail = {
  version: "0.24.15",
  title: "WAFL Productization Audit",
  status: "verification_pending",
  userSummary: [
    "기존 전체 화면/소스 리팩터링 감사를 제품화 감사로 확장한다.",
    "실제 대형 수정 전에 Productization Audit Report와 PB backlog를 만든다.",
  ],
  visibleChanges: [
    "사용자 업무 화면의 동작은 바꾸지 않는다.",
    "제품화 감사 결과와 PB-001 이후 우선순위 backlog가 문서로 추가된다.",
  ],
  expectedUi: [
    "이번 버전은 문서/감사 중심이므로 UI 변경은 없다.",
    "후속 UI 변경은 0.24.16 이후 사용자 확인 필요 항목으로 다룬다.",
  ],
  developmentPurpose: [
    "WAFL Component, UI Consistency, Source Quality, Common Module, i18n, Runtime/Permission, Functions, Product Cleanup, Performance, Release Readiness를 한 번에 감사한다.",
    "감사 결과를 PB backlog로 변환해 0.24.16~0.24.21 제품화 작업의 기준으로 삼는다.",
  ],
  developmentUiStructure: ["감사 중심 버전으로 코드 구조와 화면 컴포넌트 사용 현황을 분류한다."],
  scope: [
    "WAFL Component Audit",
    "UI Consistency Audit",
    "Source Quality Audit",
    "Common Module Audit",
    "i18n Audit",
    "Runtime/Permission Audit",
    "Functions Audit",
    "Product Cleanup Audit",
    "Performance Audit",
    "Release Readiness Audit",
    "Productization Audit Report 생성",
    "Productization Backlog(PB-001...) 생성",
  ],
  outOfScope: [
    "대규모 실제 수정",
    "공통 컴포넌트 교체",
    "권한 정책 변경",
    "DB/R2/Seed/Reset/Cleanup 실행",
    "PDF/R2/Simulator 기능 구현",
    "package/lockfile 변경",
  ],
  implementationPrinciples: [
    "감사 버전과 실제 수정 버전을 분리한다.",
    "발견 사항은 PB 항목으로 추적하고 임의 화면 수정으로 확장하지 않는다.",
    "정책/권한/DB/R2 영향은 문서화만 하고 별도 승인 없이 실행하지 않는다.",
  ],
  successConditions: [
    "10개 제품화 감사 영역 문서화",
    "PB-001 이후 backlog 생성",
    "후속 0.24.16/0.24.17/0.24.18/0.24.19/0.24.20/0.24.21 연결",
    "APP_VERSION, README, roadmap, current-state 동기화",
    "대형 UI/권한/DB/R2 수정 없음",
  ],
  failureConditions: [
    "감사 중 대형 리팩터링 수행",
    "기능 동작 변경",
    "DB/R2/Seed/Reset/Cleanup 실행",
    "사용자 확인 필요한 UI 변경을 완료 처리",
  ],
  cautions: [
    "자동 변경은 최소화하고 발견 사항은 근거 영역과 함께 기록한다.",
    "PB Critical이라도 정책 결정 또는 데이터 shape 변경이 필요하면 구현하지 않고 사용자 결정 항목으로 전환한다.",
  ],
  stopConditions: ["대규모 수정 필요", "제품 정책 결정 필요", "권한/데이터 shape 변경 필요", "production DB/R2 접근 필요"],
  permissionImpact: "none",
  permissionNotes: ["권한 동작 변경 없음", "runtime/permission은 감사와 backlog 생성만 포함"],
  dbImpact: "none",
  dbImpactNotes: ["DB 접근 또는 변경 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근 또는 변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["roadmap-development-contract", "repository-cleanup 또는 documentation contract", "manual static audit review"],
  manualTests: ["Productization Audit Report 검토", "Productization Backlog 우선순위 검토", "0.24.16 시작 항목 확인"],
  expectedChangeAreas: [
    "docs/audits/productization-audit-report-0.24.15.md",
    "docs/productization-backlog.md",
    "docs/productization-roadmap.md",
    "docs/codex-current-state.md",
    "README.md",
    "lib/internal/roadmap/*",
  ],
  recommendedCommitMessage: "docs: add wafl productization audit backlog",
  nextVersionBoundary: [
    "0.24.16은 PB Critical/High 중 WAFL component와 UI consistency에 관련된 낮은 위험 항목부터 처리한다.",
    "권한 의미 변경, DB/R2 실행, PDF 정책 결정은 후속 전용 버전으로 넘긴다.",
  ],
  completionConditions: ["감사 문서 완료", "PB backlog 완료", "대형 수정 없음", "required tests PASS", "commit/push 완료"],
  result: {
    completedSummary: [
      "0.24.15에서 10개 제품화 감사 영역을 문서화했다.",
      "Productization Backlog를 PB-001부터 PB-017까지 생성했다.",
      "후속 0.24.16~0.24.21 제품화 작업의 기준을 audit/backlog 중심으로 재정렬했다.",
    ],
    commitHash: "",
    verificationResult: "ChatGPT static audit only; local build/contract verification required after patch apply.",
    remainingIssues: ["실제 npm build와 PowerShell verify는 사용자의 로컬 환경에서 실행해야 한다.", "UI/responsive/PDF/R2 완료 판단은 후속 수동 QA가 필요하다."],
    userConfirmationRequired: false,
    userConfirmationResult: "감사/문서 중심 작업이며 UI 동작 변경 없음",
  },
};
