import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_31: RoadmapVersionDetail = {
  version: "0.24.31",
  title: "Canonical Policy Conformance Remediation and PG-neutral Billing Foundation",
  status: "completed",
  userSummary: [
    "Audits the current signup, catalog, PDF/R2, storage, export, termination, and billing implementation against the final owner policy documents.",
    "Adds provider-neutral billing, payment readiness, retry, termination/recovery, company-wide export, and notification outbox foundation without connecting a real PG provider.",
  ],
  visibleChanges: [
    "Workspace subscription policy remains provider-neutral and does not collect raw card data.",
    "Workorder create and workflow growth transitions are now blocked by the shared storage quota guard when a company is already at capacity.",
    "System documentation records the canonical mismatch audit and follow-up boundaries for actual PG, scheduler, migration, and production launch work.",
  ],
  expectedUi: [
    "Company admins still see the existing subscription page; actual card entry and real PG operations stay unavailable until provider selection.",
    "Storage-full customers can read, delete, export, and recover space, but cannot create new workorders or advance workflow states that increase operational load.",
  ],
  developmentPurpose: [
    "Convert confirmed billing policy into deterministic domain constants and simulator-safe pure functions.",
    "Restore roadmap visibility for export, termination/recovery/deletion, notification outbox, and storage full-block coverage.",
  ],
  developmentUiStructure: [
    "Reuse the existing workspace subscription and system billing surfaces.",
    "Avoid customer dashboard redesign and avoid any PG-specific SDK or merchant configuration.",
  ],
  scope: [
    "APP_VERSION 0.24.31 and roadmap/current-state synchronization.",
    "Canonical policy conformance audit document.",
    "Pricing policy for Trial, Lite, Flow, Studio, Custom, VAT included amounts, and storage add-on price.",
    "PG-neutral payment method reference policy, raw-card-data exclusion, and fake dev/test reference production block.",
    "Trial billing notice, retry schedule, upgrade proration, downgrade eligibility/refund quote, cancel/termination/recovery foundation.",
    "Company-wide export foundation with seven-day access, split-ZIP readiness, exact-key manifest policy, and over-quota export allowance.",
    "Notification outbox template and safe payload policy without actual email delivery.",
    "Signup correction deadline auto-rejection policy foundation.",
    "Storage full-block coverage for workorder creation and workflow growth transitions.",
  ],
  outOfScope: [
    "Actual PG provider selection, SDK, merchant secret, billing key issuance, production webhook, real charge, or real refund.",
    "Actual email provider integration or external email sending.",
    "Production company export, production deletion, broad R2 prefix deletion, or real customer data mutation.",
    "DB migration execution or destructive schema changes.",
    "0.24.32 or later feature implementation.",
  ],
  implementationPrinciples: [
    "Money is stored and calculated as integer KRW with VAT-included pricing.",
    "Custom plan remains negotiated; Studio-sized technical fallback is not a formal Custom price.",
    "Provider-neutral adapters and simulator contracts must not store raw provider payloads, raw card data, or secrets.",
    "Scheduler, export, and deletion jobs are idempotent foundations until a guarded dev/test runner or production deployment is explicitly approved.",
  ],
  successConditions: [
    "Canonical audit classifies MATCH/PARTIAL/MISSING/MISMATCH/DEFERRED/LEGAL_REVIEW and records source documents.",
    "Pricing, payment security, retry, proration, downgrade, termination/recovery, export, notification, correction deadline, and storage full-block contracts pass.",
    "Regression contracts for signup/provisioning, catalog, storage, PDF/R2, authorization, roadmap, repo-state, PowerShell encoding, and Unicode pass.",
    "Targeted ESLint, tsc --noEmit, next build, mutation audit, git diff checks, commit, push, and 4. Newest handoff complete.",
  ],
  failureConditions: [
    "A real PG provider or merchant secret is required.",
    "Production DB/R2/Worker mutation is required or detected.",
    "A destructive migration, real customer backfill, broad R2 deletion, or production scheduler deployment is required.",
    "Canonical documents conflict on confirmed price or lifecycle policy.",
  ],
  cautions: [
    "0.24.31 is PG-neutral foundation, not live payment processing.",
    "DB persistence tables for full billing operations remain a follow-up migration unless explicitly approved.",
    "Actual scheduler/outbox delivery/export/deletion execution remains separately guarded work.",
  ],
  stopConditions: [
    "Production access or production mutation is needed.",
    "Actual PG merchant credential, webhook secret, or email provider secret is needed.",
    "Worker source change and redeployment becomes necessary.",
  ],
  permissionImpact: "guarded",
  permissionNotes: [
    "Company-admin billing operations remain tenant scoped.",
    "System-admin billing review remains actual system-admin scoped.",
    "Storage quota checks use the effective company boundary.",
  ],
  dbImpact: "guarded",
  dbImpactNotes: [
    "No DB migration is executed in this version.",
    "Provider-neutral persistence schema is documented as follow-up unless approved as additive migration work.",
  ],
  r2Impact: "guarded",
  r2ImpactNotes: [
    "No Worker source change or Worker deployment is required.",
    "Company-wide export foundation requires exact-key manifests and no raw R2 URL exposure.",
  ],
  migrationRequired: false,
  migrationNotes: "No migration is executed for the PG-neutral billing foundation.",
  automaticTests: [
    "canonical policy conformance audit contract",
    "billing pricing and security contracts",
    "subscription lifecycle contract",
    "company export foundation contract",
    "notification outbox contract",
    "storage full-block coverage contract",
    "signup correction deadline contract",
    "roadmap 0.24.31 contract",
    "roadmap development contract",
    "mutation audit",
    "targeted ESLint",
    "tsc --noEmit",
    "next build",
    "git diff --check",
  ],
  manualTests: [
    "Vercel QA for subscription page copy and storage-full workorder creation/stage blocking.",
    "Future PG provider QA after merchant/provider selection.",
  ],
  expectedChangeAreas: [
    "lib/billing/*",
    "lib/signup/signupCorrectionPolicy.ts",
    "lib/workorder/api/workOrderRouteHandlers.ts",
    "lib/internal/roadmap/*",
    "docs/audits/0.24.31-canonical-policy-conformance-audit.md",
    "docs/codex-current-state.md",
    "docs/productization-roadmap.md",
    "tests/*billing*",
    "tests/*0.24.31*",
  ],
  futureDependencies: [
    "Actual PG provider adapter, additive billing schema migration, webhook verification, scheduler deployment, email provider, export execution, and deletion execution remain future approved work.",
  ],
  recommendedCommitMessage: "0.24.31 canonical 정책 감사와 PG-neutral billing foundation 완료",
  nextVersionBoundary: ["0.24.32 - Launch hardening, live provider decisions, or next canonical roadmap item after user approval."],
  completionConditions: [
    "APP_VERSION 0.24.31",
    "Canonical policy audit and provider-neutral billing contracts pass.",
    "Mutation audit high-risk 0 is recorded.",
    "Commit/push complete and 4. Newest contains exactly the latest source ZIP and matching repo-state.",
  ],
  result: {
    completedSummary: [
      "Canonical policy conformance audit was recorded from final owner documents.",
      "PG-neutral billing, payment readiness, retry, termination/recovery, export, notification, and signup correction foundations were added without real PG/email integration.",
      "Storage full-block coverage now includes workorder creation and workflow growth transitions.",
    ],
    commitHash: "recorded in final report after commit",
    verificationResult: "Pending final verification.",
    remainingIssues: [
      "Actual PG provider, additive billing persistence schema, scheduler execution, real email delivery, full company export execution, and production deletion remain deferred/approved follow-up work.",
    ],
    userConfirmationRequired: true,
    userConfirmationResult: "PENDING_PROVIDER_AND_SCHEDULER_APPROVAL",
  },
};
