import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21: RoadmapVersionDetail = {
  version: "0.24.21",
  title: "PB Breakdown 및 Codex Ready Queue",
  status: "verification_pending",
  userSummary: ["제품화 PB를 실제 구현 단위로 분해하고 0.24.22 Codex Sprint #2의 범위와 순서를 확정한다."],
  visibleChanges: ["사용자 업무 UI 변경 없이 PB 상태, Codex Ready Queue, Sprint Queue와 roadmap 기준이 갱신된다."],
  expectedUi: ["후속 Sprint에서 관리자 주요 화면과 worker density, Functions 안전 UX가 우선 개선된다."],
  developmentPurpose: ["정책 미결정 항목과 바로 구현 가능한 PB를 분리하고 Codex가 한 번의 큰 Sprint로 안전하게 실행할 queue를 만든다."],
  developmentUiStructure: ["PB 문서는 목적·범위·의존성·위험도·완료 조건을 제공하고 roadmap은 현재/다음 Sprint 경계를 표시한다."],
  scope: ["PB Breakdown", "PB 상태/우선순위 정리", "Codex Ready Queue", "Sprint Queue", "0.24.22 Productization Sprint #2 범위"],
  outOfScope: ["실제 UI/Functions 구현", "Playwright 코드 확대", "PDF/R2 엔진", "production mutation", "DB schema/dependency 변경"],
  implementationPrinciples: ["Ready/Conditional/Blocked를 구분한다.", "사용자 결정이 필요한 정책을 구현 queue에 넣지 않는다.", "작은 단편 작업보다 검증 가능한 Sprint 묶음을 우선한다."],
  successConditions: ["PB별 목적·범위·의존성·위험도·완료 조건 존재", "Codex Ready Queue 우선순위 존재", "0.24.22 필수/선택/제외 범위 존재", "통합 QA 체크포인트가 후속 Sprint로 보존됨"],
  failureConditions: ["미결정 정책을 Ready로 표시", "production mutation을 Sprint에 포함", "기존 PB를 근거 없이 삭제", "후속 구현 범위가 광범위하고 검증 불가능함"],
  cautions: ["PB 상태는 구현 완료가 아니라 실행 준비도를 의미한다.", "UI/반응형 완료는 후속 실기기 확인이 필요하다."],
  stopConditions: ["권한 의미 변경 필요", "production DB/R2 실행 필요", "사용자 정책 결정 없이 final PDF 동작 확정 필요"],
  permissionImpact: "none",
  permissionNotes: ["문서/roadmap 변경이며 permission guard를 변경하지 않는다."],
  dbImpact: "none",
  dbImpactNotes: ["DB read/write 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 read/write 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["TypeScript/build", "roadmap-development-contract", "문서 경로/version 계약", "Flat ZIP 무결성"],
  manualTests: ["docs index의 16~18 링크", "/roadmap 현재 0.24.21/다음 0.24.22 표시", "PB Ready/Conditional 구분 검토"],
  expectedChangeAreas: ["docs/project/16-18", "docs/productization-backlog.md", "docs/productization-roadmap.md", "docs/codex-current-state.md", "lib/constants/version.ts", "lib/internal/roadmap/*", "pending-tests.md"],
  recommendedCommitMessage: "docs: define pb breakdown and codex sprint queue",
  nextVersionBoundary: ["0.24.22는 PB-005/006/010 중심 Productization Sprint #2 실제 구현을 수행한다."],
  completionConditions: ["PB/queue 문서 작성", "roadmap/version 동기화", "required checks PASS", "commit/push 완료"],
  result: {
    completedSummary: ["PB를 Ready/Conditional/Blocked 기준으로 분해하고 Codex Ready Queue와 Sprint Queue를 확정했다."],
    commitHash: "",
    verificationResult: "수동 패치 생성 완료; 적용 후 roadmap-development-contract와 build 확인 필요",
    remainingIssues: ["0.24.22 실제 구현", "사용자 결정 대기 중인 PDF/retention/four-eyes 정책", "후속 실기기 통합 QA"],
    userConfirmationRequired: false,
    userConfirmationResult: "문서/계획 패치이며 미결정 정책은 보류 상태로 유지",
  },
};
