import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_19: RoadmapVersionDetail = {
  version: "0.24.19",
  title: "PDF/R2 정책 및 PDF 생성 구조",
  status: "planned",
  userSummary: ["작업지시서와 발주서 PDF의 임시본/최종본, 저장, 삭제, 생성 시점 정책을 정한다."],
  visibleChanges: ["PDF 버튼, 생성 상태, 다운로드/인쇄 결과가 화면 데이터와 일치하도록 정리된다."],
  expectedUi: ["PDF 출력 화면과 실제 PDF 파일을 비교해 사람이 확인할 수 있는 QA 항목을 남긴다."],
  developmentPurpose: ["작업지시서 PDF 임시본/최종본 정책, 발주서 PDF 생성 시점, R2 저장 경로와 삭제 정책, 화면/PDF 일치성 검증을 정리한다."],
  developmentUiStructure: ["workorder PDF와 supplier/material-order PDF를 목적별로 분리하고 생성/저장 상태를 명시한다."],
  scope: ["작업지시서 PDF 임시본/최종본 정책", "발주서 PDF 생성 시점", "PDF R2 저장 경로와 삭제 정책", "PDF 출력 화면과 실제 PDF 파일 일치성 검증"],
  outOfScope: ["R2/Simulator fixture 기반 재정의", "Functions/Simulator 자동화 확장", "운영 R2 mutation"],
  implementationPrinciples: ["PDF와 R2는 수동 QA가 필요한 항목으로 완료 조건을 분리한다."],
  successConditions: ["PDF policy contract PASS", "화면/PDF 비교 기준 문서화", "R2 저장/삭제 정책 명확화"],
  failureConditions: ["R2 정책 미확정 상태에서 실제 저장", "화면/PDF 내용 불일치", "사용자 확인 전 완료 처리"],
  cautions: ["PDF 생성 결과는 visual/manual QA 필요 항목이다."],
  stopConditions: ["R2 저장 정책 사용자 결정 필요", "실제 R2 mutation 승인 필요", "PDF 법적/업무 정책 결정 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["PDF 생성/조회 권한은 업무 권한과 일치시킨다."],
  dbImpact: "pending_decision",
  dbImpactNotes: ["PDF attachment 등록 방식에 따라 DB write가 필요할 수 있다."],
  r2Impact: "pending_decision",
  r2ImpactNotes: ["R2 저장/삭제 정책 결정과 별도 승인 필요"],
  migrationRequired: false,
  migrationNotes: "기본 전제는 DB Migration 없음. attachment schema 변경이 필요하면 별도 버전으로 분리한다.",
  automaticTests: ["PDF policy contract", "Worker/R2 adapter contract", "permission guard contract"],
  manualTests: ["화면/PDF 비교", "다운로드/인쇄 QA", "파일명/재생성/R2 경로 검토"],
  expectedChangeAreas: ["app/api/workorders/*generated*", "cloudflare/pdf-generator-worker/*", "lib/functions/pdfPolicyCatalog.ts", "tests/*pdf*"],
  recommendedCommitMessage: "feat: define pdf r2 generation policy",
  nextVersionBoundary: ["0.24.20은 Functions/Simulator/PowerShell 자동화를 확장한다."],
  completionConditions: ["policy/code 정리 완료", "required tests PASS", "PDF 수동 확인 항목 기록", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: true, userConfirmationResult: "미확인" },
};
