import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_23: RoadmapVersionDetail = {
  version: "0.24.23",
  title: "Source Architecture Cleanup",
  status: "user_decision_needed",
  userSummary: [
    "기능 확장 전에 대형 소스 파일과 중복 책임 경계를 다시 측정하고, 안전한 범위부터 책임 단위로 분리한다.",
    "이번 버전은 drawing editor의 canvas primitive/helper를 분리하고, 나머지 대형 파일과 PDF Worker/logger/fallback 경계를 감사 증거로 고정한다.",
  ],
  visibleChanges: ["고객 업무 UI의 의도적 변경 없음", "drawing modal 동작, 권한, 저장 흐름 유지"],
  expectedUi: ["기존 workorder drawing modal과 관리자/사용자 화면 동작 유지", "0.24.24 UI Foundation으로 자동 진입하지 않음"],
  developmentPurpose: [
    "대형 파일의 단순 줄 수 축소가 아니라 책임 단위로 나누는 첫 cleanup을 적용한다.",
    "후속 WaflUiCatalogPage, AdminSettingsHub, joinRequestRepository, i18n, PDF Worker cleanup을 측정 근거 위에서 진행하게 한다.",
  ],
  developmentUiStructure: [
    "drawing canvas primitive/helper module",
    "source architecture audit report",
    "PDF Worker boundary contract",
    "logger/redaction baseline contract",
  ],
  scope: [
    "실제 대형 파일 크기와 책임 집중 영역 측정",
    "drawing editor helper/type/icon/canvas primitive 분리",
    "중복 repository/service/route/helper 후보 추적",
    "dead route/component/helper 후보와 production mock/demo/fallback 경로 점검",
    "legacy PDF Worker와 현재 external PDF generator 경계 확인",
    "TypeScript/API/DB 계약 불일치 위험 기록",
    "중앙 logger와 민감정보 로그 상태 확인",
    "APP_VERSION, roadmap, current-state, audit 문서 갱신",
  ],
  outOfScope: [
    "0.24.24 WAFL UI Foundation 시작",
    "권한, tenant, workflow, DB, R2, PDF 정책 변경",
    "deprecated Cloudflare PDF Worker 삭제",
    "joinRequestRepository approval semantics 변경",
    "package/lockfile 변경",
    "DB schema migration 또는 production DB/R2 mutation",
  ],
  implementationPrinciples: [
    "새 50KB 이상 파일을 만들지 않는다.",
    "기존 import 경로가 필요한 public type은 re-export로 유지한다.",
    "production fallback을 새로 만들거나 조용히 유지하는 방향으로 바꾸지 않는다.",
    "삭제는 참조, 테스트, 배포 근거가 모두 있을 때만 별도 단계로 수행한다.",
  ],
  successConditions: [
    "WorkOrderDrawingCanvasEditor가 50KB 미만으로 내려가고 새 primitive 파일도 50KB 미만",
    "source architecture audit가 대형 파일, 중복 경계, dead/mock/fallback, PDF Worker, logger 상태를 기록",
    "source architecture cleanup contract PASS",
    "build, mutation audit, source architecture cleanup verification PASS",
    "package/lockfile, DB schema, migration, production DB/R2 변경 없음",
  ],
  failureConditions: [
    "drawing editor 열기/그리기/undo/redo/draft 동작 변경",
    "권한 또는 tenant 경계 변경",
    "deprecated PDF Worker 삭제 또는 runtime fallback 변경",
    "새 50KB 이상 파일 생성",
    "schema migration 또는 production DB/R2 접근 필요",
  ],
  cautions: [
    "WaflUiCatalogPage와 admin i18n은 여전히 대형 파일이며 후속 cleanup 대상이다.",
    "joinRequestRepository는 DB/permission/company provisioning 책임이 강해 route contract 없이 분리하면 위험하다.",
    "logger 중앙화는 운영 로그 정책과 연결되므로 이번 버전에서는 baseline만 확인한다.",
  ],
  stopConditions: [
    "소스 분리가 runtime behavior 또는 data semantics 변경을 요구함",
    "dead path로 보이는 항목이 active production reference를 가짐",
    "schema migration, package/lockfile 변경, production DB/R2 접근이 필요함",
    "PDF renderer 선택이나 fallback 정책 결정을 새로 해야 함",
  ],
  permissionImpact: "none",
  permissionNotes: ["권한 흐름과 route guard를 변경하지 않는다."],
  dbImpact: "none",
  dbImpactNotes: ["DB 접근 또는 schema 변경 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근 또는 object lifecycle 변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: [
    "source-architecture-cleanup-contract",
    "source-architecture-cleanup verify profile",
    "TypeScript and production build",
    "mutation audit",
    "unicode-encoding-contract",
    "pipeline-powershell-encoding-contract",
  ],
  manualTests: [
    "workorder drawing modal 열기/그리기/undo/redo/저장/닫기 동작 확인",
    "PDF Worker deploy 기준 문서 확인",
    "0.24.24 시작 전 사용자 승인",
  ],
  expectedChangeAreas: [
    "components/workorder/drawing/*",
    "docs/audits/source-architecture-cleanup-0.24.23.md",
    "tests/source-architecture-cleanup-contract.mjs",
    "tools/pipeline/verify-safe.ps1",
    "tools/pipeline/approved-workflow.ps1",
    "lib/internal/roadmap/*",
    "docs/codex-current-state.md",
    "docs/productization-roadmap.md",
  ],
  recommendedCommitMessage: "Source architecture cleanup의 첫 책임 분리와 감사 경계를 확정한다.",
  nextVersionBoundary: [
    "사용자 승인 후 0.24.24 WAFL UI Foundation으로 이동",
    "추가 source cleanup이 필요하면 0.24.24 전에 별도 0.24.23.x patch로 분리",
  ],
  completionConditions: [
    "source cleanup contract PASS",
    "approved workflow Verify/Plan/Finish PASS",
    "commit/push 완료",
    "4. Newest handoff 생성",
    "0.24.24 자동 진입 금지",
  ],
  result: {
    completedSummary: [
      "drawing editor의 canvas primitive/helper/type/icon 책임을 별도 모듈로 분리했다.",
      "0.24.23 source architecture audit로 대형 파일, 중복 repository/service 경계, dead/mock/fallback, legacy PDF Worker, logger/redaction 상태를 기록했다.",
      "권한, tenant, workflow, DB, R2, PDF 정책, package/lockfile은 변경하지 않았다.",
    ],
    commitHash: "0e21685b1cdff4c94957d8c6639bd63ed89e422c",
    verificationResult: "approved workflow Verify source-architecture-cleanup PASS; build PASS; mutation audit 162 findings, 0 high-risk; source architecture cleanup contract PASS; roadmap-development-contract PASS; functions PDF contract PASS",
    remainingIssues: [
      "WaflUiCatalogPage, AdminSettingsHub, joinRequestRepository, admin i18n split은 후속 cleanup으로 남김",
      "deprecated PDF Worker 삭제는 배포 검증 전 보류",
      "중앙 logger/correlation ID/retention class는 별도 정책 구현 필요",
    ],
    userConfirmationRequired: true,
    userConfirmationResult: "0.24.24 시작 전 사용자 승인 필요",
  },
};
