import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_14: RoadmapVersionDetail = {
  version: "0.24.14",
  title: "Functions 90% 구현/검증 정리",
  status: "planned",
  userSummary: ["/functions에서 실제 실행 가능 항목과 자동화 상태를 더 믿을 수 있게 정리한다."],
  visibleChanges: ["/functions catalog가 seed/reset/cleanup/reconcile 명령과 PowerShell profile 연결 상태를 더 명확히 보여준다."],
  expectedUi: ["위험 기능은 계속 dry-run/confirmation 기준을 유지하고, 실행 불가 사유를 숨기지 않는다."],
  developmentPurpose: ["Functions catalog와 PowerShell profile, 자동화 상태 표시를 연결해 functions 테스트 coverage 90%를 목표로 한다."],
  developmentUiStructure: ["/functions read/view 화면과 catalog 데이터를 중심으로 정리한다."],
  scope: ["/functions catalog 실제 실행 가능 항목 정리", "자동화 상태와 PowerShell profile 연결", "seed/reset/cleanup/reconcile 명령 표시 정리", "functions 테스트 coverage 90% 목표"],
  outOfScope: ["destructive DB/R2 실행", "Simulator fixture 확장", "PDF/R2 정책 결정", "대형 UI 리팩터링"],
  implementationPrinciples: ["위험 기능은 dry-run과 명시 confirmation을 유지한다."],
  successConditions: ["functions contract PASS", "위험 명령 guard 유지", "coverage 목표 또는 미달 사유 기록"],
  failureConditions: ["Seed/Reset/Cleanup execute 실행", "production 접근", "confirmation 약화"],
  cautions: ["실제 DB/R2 mutation은 별도 승인 없이는 실행하지 않는다."],
  stopConditions: ["destructive 실행 필요", "production binding 필요", "권한 정책 변경 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["system-admin guard와 action별 dev/test guard 유지"],
  dbImpact: "guarded",
  dbImpactNotes: ["dry-run/read-only 기준으로 정리하고 실제 mutation은 금지"],
  r2Impact: "guarded",
  r2ImpactNotes: ["R2 create/delete는 이 버전에서 실행하지 않는다."],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["functions contract", "PowerShell profile contract", "system-admin-internal-access"],
  manualTests: ["/functions catalog 표시와 위험 버튼 비활성/확인 흐름 검토"],
  expectedChangeAreas: ["lib/functions/*", "app/functions/*", "tools/pipeline/*", "tests/functions-*"],
  recommendedCommitMessage: "test: align functions catalog automation coverage",
  nextVersionBoundary: ["0.24.15는 전체 화면/소스 리팩터링 감사를 수행하며 대규모 수정은 하지 않는다."],
  completionConditions: ["functions 정리 완료", "required tests PASS", "destructive 실행 없음", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: false, userConfirmationResult: "" },
};
