import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_19: RoadmapVersionDetail = {
  version: "0.24.19",
  title: "PDF/R2 정책 및 PDF 생성 구조",
  status: "verification_pending",
  userSummary: ["작업지시서와 발주서 PDF의 임시본/최종본, 저장, 삭제, 생성 시점 정책을 정한다."],
  visibleChanges: ["PDF 버튼, 생성 상태, 다운로드/인쇄 결과가 화면 데이터와 일치하도록 정리된다."],
  expectedUi: ["PDF 출력 화면과 실제 PDF 파일을 비교해 사람이 확인할 수 있는 QA 항목을 남긴다."],
  developmentPurpose: ["작업지시서 PDF 임시본/최종본 정책, 발주서 PDF 생성 시점, R2 저장 경로와 삭제 정책, 화면/PDF 일치성 검증을 정리한다."],
  developmentUiStructure: ["workorder PDF와 supplier/material-order PDF를 목적별로 분리하고 생성/저장 상태를 명시한다."],
  scope: ["작업지시서 PDF 임시본/최종본 정책", "발주서 PDF 생성 시점", "PDF R2 저장 경로와 삭제 정책", "PDF 출력 화면과 실제 PDF 파일 일치성 검증"],
  outOfScope: ["R2/Simulator fixture 기반 재정의", "Functions/Simulator 자동화 확장", "운영 R2 mutation"],
  implementationPrinciples: ["PDF는 versioned document model을 사용하고 R2는 tenant-safe namespace와 분리된 lifecycle/quota 계약을 따른다.", "관리자 운영은 company administrator와 system administrator 경계를 분리하고 민감·파괴 작업을 별도 승인한다."],
  successConditions: ["PDF 사양, R2 저장 정책, 관리자 운영 설계가 canonical 문서로 존재", "화면/PDF 비교 기준 문서화", "R2 namespace/quota/lifecycle/reconciliation 정책 명확화", "관리자 역할과 운영 action class/감사 경계 명확화"],
  failureConditions: ["R2 정책 미확정 상태에서 실제 저장", "화면/PDF 내용 불일치", "사용자 확인 전 완료 처리"],
  cautions: ["PDF 생성 결과는 visual/manual QA 필요 항목이다."],
  stopConditions: ["R2 저장 정책 사용자 결정 필요", "실제 R2 mutation 승인 필요", "PDF 법적/업무 정책 결정 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["PDF 생성/조회 권한은 업무 권한과 일치시킨다."],
  dbImpact: "pending_decision",
  dbImpactNotes: ["PDF attachment 등록 방식에 따라 DB write가 필요할 수 있다."],
  r2Impact: "pending_decision",
  r2ImpactNotes: ["R2 저장/삭제 정책 결정과 별도 승인 필요"],
  migrationRequired: false,
  migrationNotes: "기본 전제는 DB Migration 없음. attachment schema 변경이 필요하면 별도 버전으로 분리한다.",
  automaticTests: ["TypeScript/build", "roadmap-development-contract", "문서 경로/version 계약"],
  manualTests: ["화면/PDF 비교", "다운로드/인쇄 QA", "파일명/재생성/R2 경로 검토"],
  expectedChangeAreas: ["docs/project/09-pdf-specification.md", "docs/project/10-r2-storage-policy.md", "docs/project/11-admin-operations-design.md", "lib/internal/roadmap/*"],
  recommendedCommitMessage: "docs: define pdf r2 and admin operations policy",
  nextVersionBoundary: ["0.24.20은 Functions/Simulator/PowerShell 자동화를 확장한다."],
  completionConditions: ["canonical policy 문서 작성 완료", "roadmap/version 동기화", "required checks PASS", "commit/push 완료", "실제 PDF/R2 구현과 정책 결정 잔여 항목은 후속 PB로 유지"],
  result: { completedSummary: ["PDF 사양, R2 저장 정책, 회사/시스템 관리자 운영 경계를 canonical 문서로 정리했다."], commitHash: "", verificationResult: "수동 패치 생성 완료; 적용 후 roadmap-development-contract 및 build 확인 필요", remainingIssues: ["PDF 엔진/템플릿 구현", "production R2 binding 및 reconciliation 구현", "요금제별 용량·보존기간·support access·four-eyes 정책 사용자 결정"], userConfirmationRequired: true, userConfirmationResult: "상업/운영 정책 결정 대기" },
};
