import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_22: RoadmapVersionDetail = {
  version: "0.24.22",
  title: "DB Foundation and Authority Alignment",
  status: "planned",
  userSummary: [
    "기능 확장 전에 고객사 멤버십·구독·작업지시서·첨부파일의 DB 기준을 하나로 정리한다.",
    "실제 migration을 서두르지 않고 코드의 읽기·쓰기 경로, 배포 DB drift, RLS와 제약조건 근거를 먼저 확정한다.",
  ],
  visibleChanges: ["고객 업무 UI의 의도적 변경 없음", "필요한 경우 내부 감사 보고서와 read-only 검증 결과만 추가"],
  expectedUi: ["기존 화면과 권한 동작 유지", "DB 조사 때문에 고객 화면을 임의 변경하지 않음"],
  developmentPurpose: [
    "users/company_users/company_members와 plans/subscriptions/assignments의 source of truth를 확정한다.",
    "후속 가입·PDF·Export·삭제·결제 Sprint가 중복 스키마와 불명확한 tenant authority 위에 구현되지 않게 한다.",
  ],
  developmentUiStructure: ["read-only DB audit", "repository/query authority matrix", "migration/backfill/rollback proposal", "RLS/tenant contract evidence"],
  scope: [
    "멤버십·역할·회사 소속 read/write 경로 전수 추적",
    "요금제·Trial·구독·용량 source-of-truth와 중복 컬럼 분류",
    "workorder 내부 PK와 opaque public URL ID 전환 설계",
    "attachments·trash·delete queue·R2 lifecycle 책임 분리 설계",
    "tenant 테이블 목록과 실제 배포 DB RLS/정책 drift 확인",
    "FK·unique·check·nullable·timestamp와 인덱스의 쿼리 근거 점검",
    "충돌 데이터 reconciliation, staged backfill, dry-run, rollback, GO/STOP 문서화",
    "후속 기능별 필요한 신규 DB 구조와 migration 분리 경계 확정",
  ],
  outOfScope: [
    "production DB destructive mutation",
    "승인 없는 migration 적용",
    "테이블 즉시 삭제·rename",
    "PG 결제 구현",
    "UI Foundation과 대형 소스 리팩터링",
    "package/lockfile 변경",
  ],
  implementationPrinciples: [
    "evidence-first: schema·query·runtime 사용 근거 없이 authority를 바꾸지 않는다.",
    "현재 master를 단일 개발/QA branch로 유지한다.",
    "read-only 감사와 dry-run을 먼저 수행하고 실제 변경은 별도 버전·확인·rollback 경계로 분리한다.",
    "application tenant guard와 DB RLS를 상호 보완하며 어느 하나만 신뢰하지 않는다.",
    "새 compatibility layer는 종료 조건과 제거 버전을 함께 기록한다.",
  ],
  successConditions: [
    "핵심 테이블별 canonical owner와 read/write authority matrix 확정",
    "실제 코드 쿼리와 배포 DB schema/RLS drift 보고서 확보",
    "데이터 충돌·orphan·duplicate·nullable 위반 수치화",
    "migration 후보별 dry-run·backfill·rollback·중단 조건 작성",
    "후속 Sprint가 사용할 안정된 repository/API 계약 정의",
    "roadmap·문서·PowerShell 후속 검증 항목 동기화",
  ],
  failureConditions: [
    "production 데이터에 승인 없이 write",
    "근거 없이 기존 테이블/컬럼 삭제",
    "tenant/RLS 문제를 UI 숨김만으로 처리",
    "reconciliation 결과 없이 unique/FK/check 강제",
    "migration과 source 리팩터링을 한 번에 광범위 적용",
  ],
  cautions: [
    "현재 read-only 감사가 0건이어도 배포 DB drift와 application query authority는 별도 확인해야 한다.",
    "인덱스는 개수 증가가 목표가 아니라 실제 쿼리와 중복·비사용 근거가 기준이다.",
    "RLS DDL이 저장소에 없으면 배포 환경만의 설정으로 간주하지 말고 재현 가능한 계약을 마련한다.",
  ],
  stopConditions: [
    "production DB/R2 write 또는 destructive operation이 필요함",
    "사용자 정책 결정 없이 source of truth를 선택해야 함",
    "데이터 손실 가능성이 있는 migration만으로 해결 가능함",
    "실제 secret/binding이 없어 증거를 확인할 수 없음",
    "package/lockfile 변경이 필요함",
  ],
  permissionImpact: "guarded",
  permissionNotes: ["기존 role/tenant 의미를 유지하며 서버 route와 repository의 company scope를 조사한다.", "IDOR/RLS 계약 약화 금지"],
  dbImpact: "read_only",
  dbImpactNotes: ["기본 범위는 read-only 감사와 설계다. 실제 migration은 별도 버전·승인·dry-run·rollback 조건을 만족할 때만 수행한다."],
  r2Impact: "read_only",
  r2ImpactNotes: ["attachment metadata와 R2 object lifecycle의 reconciliation 근거만 확인하며 object mutation은 하지 않는다."],
  migrationRequired: false,
  migrationNotes: "0.24.22 자체 기본 계약은 migration 없음. 조사 결과 필요한 migration은 별도 patch/version으로 분리하고 dev/test dry-run과 명시적 확인 후 진행한다.",
  automaticTests: [
    "DB reconciliation read-only audit",
    "constraint readiness read-only audit",
    "index readiness read-only audit",
    "tenant/permission/IDOR contract",
    "roadmap-development-contract",
    "TypeScript and production build",
    "Unicode and secret scan",
  ],
  manualTests: [
    "source-of-truth matrix와 실제 repository/query 근거 검토",
    "migration 후보별 영향·rollback·중단 조건 검토",
    "PowerShell 메뉴 30~32 read-only 결과 확인",
    "신규 감사 메뉴가 생기면 번호·safe/dry-run/destructive·환경 제한 확인",
    "commit/push 후 Vercel QA에서 기존 화면·권한 회귀 없음 확인",
  ],
  expectedChangeAreas: [
    "docs/project/27-database-schema-query-permission-audit.md",
    "docs/project/28-database-source-of-truth-safe-migration-design.md",
    "docs/project/31-pre-codex-integrated-master-plan.md",
    "db/schema/* and db/migrations/* (proposal only unless separately approved)",
    "lib/** repositories and app/api/** routes (evidence/compatibility scope only)",
    "tools/pipeline/* and tests/* for read-only audit contracts",
  ],
  recommendedCommitMessage: "DB source of truth와 안전한 migration 경계를 근거 기반으로 확정한다.",
  nextVersionBoundary: [
    "DB authority matrix·drift·reconciliation·migration 경계가 승인되면 0.24.23 Source Architecture Cleanup으로 이동",
    "실제 migration이 필요하면 0.24.23 전에 별도 migration patch/version을 삽입",
  ],
  completionConditions: [
    "read-only 감사와 계약 테스트 PASS",
    "source-of-truth 및 migration/rollback 문서 승인",
    "production mutation 0건",
    "build PASS",
    "master commit/push와 Vercel QA 완료",
  ],
  result: {
    completedSummary: [],
    commitHash: "",
    verificationResult: "",
    remainingIssues: ["실행 전 계획 상태"],
    userConfirmationRequired: true,
    userConfirmationResult: "DB authority와 migration 후보는 조사 결과 보고 후 사용자 확인 필요",
  },
};
