import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_26: RoadmapVersionDetail = {
  version: "0.24.26",
  title: "Public Signup, Verification, Approval, and Trial",
  status: "in_progress",
  userSummary: [
    "Defines the executable roadmap for public signup, verified identity, system-admin approval, and Trial provisioning.",
    "This roadmap records the final owner policy as implementation criteria; it does not start product code in the metadata-only canonicalization step.",
  ],
  visibleChanges: [
    "Public WAFL signup entry and Trial CTA are planned for the next implementation step.",
    "Pending, rejected, and not-yet-approved users will receive limited state screens instead of workspace access.",
  ],
  expectedUi: [
    "Public signup CTA starts Google OAuth and requires an email-verified Google profile.",
    "New company applicants submit required business information, consent evidence, intended plan, and a business certificate.",
    "System administrators review, request correction, reject, or approve the application through an internal queue.",
  ],
  developmentPurpose: [
    "Create the public signup and approval boundary without weakening authenticated workspace, system-admin, tenant, or destructive-action guards.",
    "Provision company, first admin, membership, role/permission, subscription, Trial quota, audit, and business-certificate ownership atomically and idempotently at approval time.",
  ],
  developmentUiStructure: [
    "Public website/app boundary with signup/login entry points.",
    "Authenticated pre-approval state pages for draft, submitted, reviewing, changes_requested, rejected, canceled, and provisioning_failed users.",
    "System-admin review list/detail, approval-only certificate viewer, correction request, rejection, approval, retry, and repair surfaces.",
  ],
  scope: [
    "Public signup CTA and Google OAuth entry.",
    "Google profile email_verified=true enforcement.",
    "Unjoined verified-user state.",
    "New company application creation.",
    "Existing company join path prefers invitation/code over public company search.",
    "Reuse or extend join_requests and invitations where the existing model fits.",
    "System-admin review, correction request, rejection, approval, retry, and repair.",
    "Pending/rejected limited state screens.",
    "Block /workspace and workspace APIs before approval.",
    "Approval-time provisioning of company, user, company_member, role/permission, company_subscription, Trial, storage quota, member limit, audit, and business-certificate ownership link.",
    "Idempotent provisioning and provisioning_failed recovery.",
    "Trial: 7 days, 100MB storage, 3 members.",
    "Trial starts when the system administrator approves the signup.",
    "Business certificate is required for production new-company applications.",
    "Dev/test fixtures may relax certificate requirements only where explicitly guarded.",
    "Approval viewer only for business certificate; no WAFL-provided download path.",
    "Audit trace, IDOR defense, duplicate prevention, email normalization, and signup abuse controls.",
  ],
  outOfScope: [
    "Actual PG payment charge, payment-method registration, payment-reference storage, and subscription operation; this remains 0.24.31.",
    "Storing raw card data, fake card placeholders, fake payment references, or PG-neutral payment references.",
    "System catalog, size, or POM row provisioning; this remains 0.24.27.",
    "Executing DB migrations without explicit user approval or against production.",
    "Production DB/R2 mutation during roadmap creation.",
    "Cloudflare Worker source changes unless a later implementation step explicitly requires them.",
    "0.24.28 PDF/R2 lifecycle product code.",
    "0.24.30 storage enforcement product code.",
  ],
  implementationPrinciples: [
    "Final owner policy documents are the source of truth; this roadmap structures settled policy instead of reopening decisions.",
    "Signup identity, company application, business evidence, and provisioning state must be explicit and auditable.",
    "Approval provisioning must be idempotent and must not expose partially-created companies as active workspaces.",
    "Do not require card registration or payment-method readiness in 0.24.26; payment and payment-reference storage are reserved for 0.24.31.",
    "Do not trust client-public environment variables for server authorization or runtime decisions.",
    "System-admin certificate access is approval-only and viewer-only; general customer business files remain isolated.",
    "Destructive simulator, reset, seed, cleanup, DB/R2 mutation, and migration actions remain separately guarded.",
  ],
  successConditions: [
    "Signup requires a Google profile with email_verified=true.",
    "Unapproved users cannot access /workspace or workspace APIs by direct URL/API call.",
    "Application statuses cover draft, submitted, reviewing, changes_requested, approved, rejected, canceled, and provisioning_failed.",
    "System-admin can approve, reject, and request correction with audit trace.",
    "Approval creates company, first admin, company_member, role/permission, subscription, Trial, quota, audit, and business-certificate ownership link exactly once.",
    "Trial values are 7 days, 100MB, and 3 members, starting at approval time.",
    "Business certificate access is limited to approval viewer and blocks WAFL-provided download.",
    "Duplicate email, company, and business-registration paths are denied or routed to safe review states.",
    "Signup abuse controls include rate limit and a CAPTCHA decision record.",
  ],
  failureConditions: [
    "Public signup allows unverified Google email.",
    "Pending/rejected users can access workspace content or APIs.",
    "Approval can create duplicate active companies, duplicate first admins, or partial active state.",
    "Raw card data, fake payment placeholders, fake payment references, or PG-neutral payment references are stored.",
    "System catalog, size, or POM rows are created in 0.24.26.",
    "Business certificate files become downloadable through a WAFL route.",
    "A DB migration or data mutation is executed without explicit approval, rollback planning, or approved dev/test fingerprint guard.",
    "Trial values regress to legacy 1GB or 5 members.",
  ],
  cautions: [
    "Trial-end read-only/download grace is not a new open decision for normal completed Trial: final policy says no post-Trial read-only grace.",
    "Rate limit/CAPTCHA mechanism is a technical design item and must be recorded before implementation.",
    "Migration may be required for signup request/application state, but creation and execution require separate approval.",
  ],
  stopConditions: [
    "A new DB schema migration or production migration becomes necessary beyond the explicitly approved signup schema migration.",
    "Production DB/R2/PG access or mutation becomes necessary.",
    "A new product-policy decision not covered by documents 26, 31, 20, 21, or 30 is discovered.",
    "Existing public website source cannot be located and implementation would require a new source-structure decision.",
  ],
  permissionImpact: "guarded",
  permissionNotes: [
    "Public routes remain unauthenticated only where explicitly public.",
    "Pending/rejected authenticated users receive limited state access.",
    "System-admin review routes require active system-admin actual session.",
    "Workspace/company APIs require approved company membership and effective-session permissions.",
  ],
  dbImpact: "pending_decision",
  dbImpactNotes: [
    "Signup applications, consent evidence, business certificate metadata, review/audit state, and idempotent provisioning records may require schema work.",
    "Migration design must be read-only reconciled and separately approved before execution.",
  ],
  r2Impact: "guarded",
  r2ImpactNotes: [
    "Business certificate upload/storage may use R2 through a narrowly scoped approval-only viewer lifecycle.",
    "No broad customer operational-file access is granted to system-admin.",
    "No R2 mutation is part of roadmap creation.",
  ],
  migrationRequired: true,
  migrationNotes:
    "Created signup_applications and signup_application_files and executed the approved migration once against the approved dev/test DB fingerprint 01e5dcc7fea3. Production migration and any additional DB mutation remain forbidden without separate approval.",
  automaticTests: [
    "signup email_verified contract",
    "pending/rejected workspace route/API guard contract",
    "system-admin application review contract",
    "business certificate approval viewer no-download contract",
    "idempotent provisioning contract",
    "Trial policy contract",
    "duplicate email/company/business registration contract",
    "signup audit contract",
    "roadmap contract",
    "roadmap development contract",
    "unicode encoding contract",
    "tsc --noEmit",
    "next build",
  ],
  manualTests: [
    "Public signup CTA and login entry on PC/mobile.",
    "Google OAuth verified-email path and unverified-email rejection.",
    "System-admin review approve/reject/correction flow.",
    "Pending, rejected, changes-requested, approved, and provisioning_failed user screens.",
    "Certificate viewer-only behavior on Vercel PC/mobile.",
    "Workspace/API direct access blocking before approval.",
  ],
  expectedChangeAreas: [
    "public website or public route group after source-location confirmation",
    "auth/session onboarding state",
    "signup application repository/service/API",
    "business certificate upload/viewer API",
    "system-admin onboarding review UI/API",
    "trial/subscription provisioning service",
    "workspace route/API guards",
    "audit and notification scheduling",
    "tests and roadmap docs",
  ],
  futureDependencies: [
    "0.24.28 PDF and R2 Lifecycle: actual R2 lifecycle simulator, valid PNG/JPEG/PDF fixtures, restore/delete/404/orphan/reconcile/rollback coverage, bounded performance fixtures, and production mutation ban.",
    "0.24.30 Storage Enforcement, Termination, and Automatic Deletion: capacity profile 0%, <1%, 10%, 20%, 30%, 50%, 70%, 90%, 99%, 100%, 110%, Trial 100MB linkage, upload preflight, warning/grace/termination/deletion scheduling, and profile apply/verify/restore commands.",
    "0.24.31 PG Billing and Subscription Operations: payment-method registration, PG-neutral payment references, billing keys, Trial-end charging, and subscription operation.",
    "Capacity fixture backlog: H/I/J DB scenario and attachment manifest expectations differ and must be resolved through future profile apply design, not immediate mutation.",
  ],
  userDecisionsRequired: [
    "No settled product policy is reopened in this roadmap.",
    "Technical implementation must still choose the existing public website source location before product code begins.",
    "Technical implementation must choose rate-limit/CAPTCHA mechanism before public signup launch.",
    "Any additional migration scope, production migration, backfill, or provisioning data mutation requires separate explicit approval before DB execution.",
  ],
  preparationHistory: [
    {
      commitHash: "ef0602de1c99fea54cd63cc69c110a3e7ad3a79d",
      summary: [
        "Canonical detailed roadmap file was created and registered.",
        "0.24.28 R2 lifecycle and 0.24.30 storage enforcement reserved dependencies were recorded.",
        "H/I/J capacity fixture mismatch was recorded as backlog without mutation.",
      ],
      verificationResult:
        "PASS: roadmap-0.24.26 contract; roadmap development contract; unicode encoding contract; targeted ESLint; tsc --noEmit; next build; git diff --check; git diff --cached --check.",
    },
  ],
  recommendedCommitMessage: "0.24.26 공개 가입 승인 Trial 로드맵 정리",
  nextVersionBoundary: [
    "0.24.27 - System Catalog, Sizes, and POM.",
    "0.24.28 - PDF and R2 Lifecycle; reserved R2 lifecycle simulator and bounded performance fixture scope are recorded as future dependencies.",
    "0.24.30 - Storage Enforcement, Termination, and Automatic Deletion; capacity profile and fixture separation are recorded as future dependencies.",
  ],
  completionConditions: [
    "Final policy documents are checked before implementation.",
    "Existing public website source location is confirmed before duplicate implementation.",
    "Migration scope is presented and approved before any migration file or execution.",
    "Contracts, typecheck, build, commit, push, and 4. Newest handoff complete after implementation.",
  ],
  result: {
    completedSummary: [
      "Canonical detailed roadmap and schema/repository preparation design are complete.",
      "Signup product implementation started with a migration-backed schema foundation and TypeScript domain/repository/service contracts.",
      "The approved dev/test signup migration was executed once: preflight compatibility audit PASS, migration apply PASS, post-apply schema audit PASS, schema smoke rollback PASS, and smoke row residue 0.",
      "The draft requires explicit email_verified evidence, normalized 10-digit business registration matching, application-owned certificate files, and provisioning failure handling through the approval operation.",
      "0.24.28 and 0.24.30 reserved dependency notes remain recorded in roadmap/backlog docs.",
    ],
    commitHash: "implementation working tree pending; latest preparation commit 23d325e3771abff066f3bdc715f07b204013f210",
    verificationResult:
      "DB migration verification PASS: runtime development, approved DB fingerprint 01e5dcc7fea3, migration SHA-256 b0f83b1026891099a65ae1b8e57f6269db52e00d1d9c6066b1b227039f16a395, preflight findings 0, post-apply findings 0, smoke rollback complete, R2 mutation 0.",
    remainingIssues: [
      "Wire the signup repository to the database after the approved dev/test migration foundation.",
      "Implement actual pending user middleware/page/API/repository guards after this foundation step.",
      "Decide technical rate-limit/CAPTCHA mechanism during implementation planning.",
      "Public signup UI/API/OAuth callback, system-admin approval UI, and actual company/user/member/subscription provisioning remain unimplemented.",
    ],
    userConfirmationRequired: true,
    userConfirmationResult:
      "Production migration, public signup UI/OAuth callback changes, API wiring, and provisioning execution require later explicit work steps.",
  },
};
