import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_34_5: RoadmapVersionDetail = {
  version: "0.24.34.5",
  title: "Live Workorder, Signup, System UI, and PDF Review Checkpoint",
  status: "user_test_needed",
  userSummary: [
    "공장 전달 PDF는 기존 표 형식 양식으로 재정리하고 금액 정보를 제외한다.",
    "치수 기준정보, 가입 재방문 상태, 고객사 운영 대시보드 정책을 0.24.35 전에 확정·구현한다.",
    "실제 dev/test 작업지시서 목록, 상세, 공장 전달사항 저장, PDF 생성/보기 흐름을 localhost 브라우저 evidence로 검증한다.",
    "공개 가입 정책 모달, system-admin 대시보드, 가입 심사, 고객 운영 화면을 screenshot evidence로 정리한다.",
    "이번 버전은 0.24.35를 시작하지 않는 제품 QA checkpoint이며, commit/push 전 사용자 검토가 남아 있다.",
  ],
  visibleChanges: [
    "공장 전달 PDF는 대표 디자인, 공장 전달사항, 원단·부자재·공정 생산 정보, 한글 치수표 중심으로 재구성된다.",
    "고객사 메인 대시보드의 큰 PLAN AND STORAGE 섹션은 compact summary로 축소되고 업무 큐가 우선된다.",
    "기존 작업지시서를 선택해도 상세 화면이 무한 로딩에 묶이지 않고 안전한 상세/오류 상태로 전환된다.",
    "실제 dev/test 작업지시서의 공장 전달사항 저장, reload 후 persistence, PDF 생성, server-proxied viewer가 동작한다.",
    "공개 가입 화면에서 약관/개인정보처리방침 본문을 WAFL modal로 확인할 수 있다.",
    "system-admin 가입 심사 화면과 고객 운영 화면의 문구를 운영자 관점으로 정리한다.",
  ],
  expectedUi: [
    "작업지시서: 목록, 상세, 공장 전달사항, 치수, PDF 상태가 입력 loading/error 상태를 가진다.",
    "PDF: workorder PDF viewer는 raw R2 URL 또는 signed URL을 브라우저에 노출하지 않고 inline PDF를 제공한다.",
    "System: /system, /system/signup-applications, /system/companies는 운영자가 이해할 수 있는 가입/고객 운영 문구를 사용한다.",
  ],
  developmentPurpose: [
    "0.24.34.4의 fixture 중심 evidence 이후 실제 사용 경로에서 발견된 runtime/PDF/system UX gap을 보정한다.",
    "자동 검증은 계속 수행하되, 최종 제품 완료 표현은 사용자 PDF/화면 검토 전까지 사용하지 않는다.",
  ],
  developmentUiStructure: [
    "Workorder runtime: components/workorder/* and lib/hooks/workorder/*",
    "Factory instruction: components/workorder/factoryInstruction/WorkOrderFactoryInstructionPanel.tsx",
    "PDF viewer: app/api/workorders/[workOrderId]/generated/*/[attachmentId]/view/route.ts",
    "Signup/system: components/signup/*, app/(public)/signup/page.tsx, components/system/signup/*",
  ],
  scope: [
    "공장 전달 PDF 최종 정책 문서화와 기존 표 형식 PDF 양식 기반 재구성",
    "금액·원가·로스·마진 정보를 공장 전달 PDF에서 제외",
    "시스템 기준 치수정보 snapshot과 한글 치수표 정책 확정",
    "치수 입력 UI의 WAFL 공통 측정 입력 패턴 정리",
    "고객사 메인 대시보드 PLAN AND STORAGE 축소와 태블릿 가로 검증",
    "APP_VERSION 0.24.34.5 갱신",
    "기존 작업지시서 선택 시 상세 무한 로딩 방지",
    "작업지시서 opaque ID가 실제 dev/test ID 형식인 wo-...도 허용하도록 보정",
    "공장 전달사항 404/customer-safe error 처리",
    "실제 workorder PDF 생성/viewer 복구와 PDF page PNG evidence 생성",
    "동일 Google 계정 재방문 가입 상태 검토 경로 정리",
    "가입 약관/개인정보처리방침 canonical modal 통합",
    "system signup review action 문구 단순화",
    "system dashboard와 system companies 역할 정리",
    "QA evidence ZIP과 요구사항 대조표 생성",
  ],
  outOfScope: [
    "0.24.35 Company-wide Export Execution",
    "production DB/R2/Worker mutation",
    "Full Reset",
    "destructive migration",
    "actual PG/email provider",
    "commit/push before user review",
  ],
  implementationPrinciples: [
    "0.24.34.5의 남은 작업은 docs/project/33-workorder-pdf-size-dashboard-finalization.md를 canonical 기준으로 삼아 나눠 진행한다.",
    "공장 전달 PDF는 생산 정보 중심이며 내부 비용 정보를 노출하지 않는다.",
    "Mock fixture PASS만으로 완료하지 않고 실제 dev/test browser evidence를 분리 기록한다.",
    "오류는 영역별 loading/error/retry로 분리하고 raw DB/R2/Worker 문구를 고객 UI에 노출하지 않는다.",
    "PDF 시각 품질은 PNG evidence를 만들되 사용자 검토 전 최종 완료로 표현하지 않는다.",
  ],
  successConditions: [
    "workorder list/detail/factory/pdf runtime evidence가 desktop/mobile/iPad에서 생성된다.",
    "PDF visual evidence package가 생성된다.",
    "signup/system 화면 screenshot과 요구사항 대조표가 생성된다.",
    "build/typecheck/targeted ESLint/contracts/git diff --check가 PASS한다.",
    "메뉴 7 dirty snapshot이 생성되고 4. Newest는 ZIP 1개와 repo-state 1개만 유지한다.",
  ],
  failureConditions: [
    "Full Reset이나 destructive migration이 필요하다.",
    "production DB/R2/Worker 접근이 필요하다.",
    "사용자 확인 없이 PDF 형식을 최종 확정해야 한다.",
    "0.24.35 범위가 필요하다.",
  ],
  cautions: [
    "이번 버전은 checkpoint이므로 사용자 검토 전 commit/push하지 않는다.",
    "evidence ZIP은 4. Newest가 아니라 QA_Evidence 폴더에 저장한다.",
    "브라우저 병렬 PDF 생성은 dev/test fixture 한계가 있어 최종 evidence는 browser별 개별 PASS로 기록한다.",
  ],
  stopConditions: [
    "기준 HEAD/working tree 불일치",
    "production 감지",
    "destructive migration 필요",
    "R2 exact cleanup 불가",
    "Google CAPTCHA/2FA 자동화 차단",
    "PDF renderer 보안/인프라 변경 필요",
  ],
  permissionImpact: "guarded",
  permissionNotes: ["기존 workspace, system-admin, applicant 권한 경계를 유지한다."],
  dbImpact: "guarded",
  dbImpactNotes: [
    "실제 dev/test 작업지시서의 공장 전달사항 저장과 PDF 생성 검증은 수행했다.",
    "production mutation은 금지했다.",
  ],
  r2Impact: "guarded",
  r2ImpactNotes: [
    "dev/test workorder PDF 생성/읽기 evidence를 만들었다.",
    "production R2 mutation은 금지했다.",
  ],
  migrationRequired: false,
  migrationNotes: "0.24.34.5에는 DB migration이 없다.",
  automaticTests: [
    "targeted ESLint",
    "tsc --noEmit",
    "next build",
    "workorder live browser E2E",
    "product screenshot browser E2E",
    "PDF visual evidence renderer",
    "roadmap/contracts/unicode/PowerShell encoding",
    "git diff --check",
  ],
  manualTests: [
    "factory-delivery PDF table-style visual review",
    "Galaxy Tab landscape customer workspace dashboard review",
    "incomplete PDF visual review",
    "final PDF visual review",
    "desktop/mobile/iPad screen review",
    "system-admin signup review UX review",
    "same Google account returning-applicant production-like OAuth round trip",
  ],
  expectedChangeAreas: [
    "components/workorder/*",
    "lib/hooks/workorder/*",
    "lib/responsive/*",
    "lib/routing/*",
    "lib/workorder/*",
    "components/signup/*",
    "components/system/signup/*",
    "app/api/workorders/*",
    "tests/e2e/*",
    "tools/pipeline/*",
    "docs/*",
    "lib/internal/roadmap/*",
  ],
  recommendedCommitMessage: "0.24.34.5 실제 작업지시서와 PDF 제품 QA 체크포인트",
  nextVersionBoundary: ["0.24.35 Company-wide Export Execution remains NOT_STARTED in this checkpoint."],
  completionConditions: [
    "code/static/runtime evidence complete",
    "PDF/browser evidence package complete",
    "PRODUCT_QA_INCOMPLETE until user review",
    "menu 7 dirty snapshot",
    "commit/push NOT_RUN",
  ],
  result: {
    completedSummary: [
      "desktop/mobile/iPad localhost workorder runtime evidence PASS",
      "workorder summary/detail/factory save/reload/PDF viewer evidence PASS",
      "signup policy modal and system screens screenshot evidence PASS",
      "first runtime failure root cause fixed: wo- ID validation and server-side Worker PDF viewer",
    ],
    commitHash: "NOT_RUN - checkpoint stops before commit/push",
    verificationResult: "PRODUCT_QA_INCOMPLETE - automated evidence exists, user visual/product review remains",
    remainingIssues: [
      "user PDF visual review remains",
      "same Google returning-applicant OAuth round trip remains manual/blocked in local automation",
      "consent hash persistence remains blocked without schema change",
      "parallel browser PDF generation against shared dev/test fixture is not treated as final PASS",
    ],
    userConfirmationRequired: true,
    userConfirmationResult: "PRODUCT_QA_INCOMPLETE",
  },
};
