import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_16: RoadmapVersionDetail = {
  version: "0.24.21.16",
  title: "Pre-Codex Integrated Master Plan",
  status: "verification_pending",
  userSummary: [
    "최종 정책, DB 감사, 소스 감사, 미구현 기능, 운영·보안·QA 준비를 하나의 Codex 실행계획으로 통합했다.",
    "0.24.22를 UI Sprint가 아니라 DB Foundation으로 재배치하고 전체 의존 순서를 확정했다.",
  ],
  visibleChanges: ["/roadmap에 0.24.21.16 통합 계획과 0.24.22 DB Foundation 경계를 표시"],
  expectedUi: ["고객 업무 UI 변경 없음", "문서와 roadmap의 실행 순서만 최신화"],
  developmentPurpose: [
    "Codex가 DB 기반, 소스 구조, 제품 기능, 운영 안정화를 빠뜨리거나 잘못된 순서로 구현하지 않도록 단일 실행계획을 고정한다.",
  ],
  developmentUiStructure: ["canonical policy", "integrated Sprint plan", "DB/source audit inputs", "cross-Sprint verification gate"],
  scope: [
    "DB Foundation Sprint 추가",
    "Source Architecture Cleanup Sprint 추가",
    "UI·권한·가입·분류·PDF·Export·삭제·결제·운영 Sprint 재정렬",
    "각 Sprint 완료·중단·검증 조건 명시",
  ],
  outOfScope: ["runtime feature implementation", "schema migration execution", "DB/R2/PG mutation", "production environment creation"],
  implementationPrinciples: [
    "DB authority를 기능 확장보다 먼저 정리한다.",
    "소스 구조 부채를 UI·상업 기능 확장 전에 줄인다.",
    "migration과 destructive operation은 별도 승인 경계로 분리한다.",
    "각 Sprint는 commit/push와 Vercel 실기기 QA까지 완료한다.",
  ],
  successConditions: [
    "31번 통합 Master Plan 존재",
    "23·26·30 문서가 새 실행 순서를 가리킴",
    "APP_VERSION/roadmap/current-state/docs index가 0.24.21.16으로 일치",
    "다음 버전이 0.24.22 DB Foundation으로 표시",
  ],
  failureConditions: [
    "UI-first 0.24.22 계획이 canonical로 남음",
    "DB 또는 소스 감사 항목 누락",
    "미구현 상업·운영 기능 누락",
    "문서 작업 중 runtime/schema mutation 발생",
  ],
  cautions: ["실제 DB migration은 0.24.22 계획 검증 후에도 별도 안전 경계가 필요하다."],
  stopConditions: ["문서 정리 범위를 넘어 runtime 구현, DB 연결, migration 적용이 필요하면 중단"],
  permissionImpact: "none",
  permissionNotes: ["권한 구현 변경 없음"],
  dbImpact: "none",
  dbImpactNotes: ["DB 감사 결과를 계획에 반영하지만 DB에는 연결하거나 변경하지 않음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근·변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음. 후속 Sprint에서 필요한 migration은 별도 버전과 승인 경계로 분리한다.",
  automaticTests: ["roadmap type/build contract", "document link/version scan", "unicode encoding contract"],
  manualTests: [
    "docs/project/31 전체 Sprint 순서 검토",
    "docs/project/23·26·30의 supersede/link 확인",
    "/roadmap 현재 0.24.21.16·다음 0.24.22 확인",
    "npm run build",
  ],
  expectedChangeAreas: [
    "docs/project/23,26,30,31",
    "docs/README.md",
    "docs/codex-current-state.md",
    "docs/productization-roadmap.md",
    "lib/internal/roadmap/*",
    "lib/constants/version.ts",
    "commit-meta.md",
    "pending-tests.md",
  ],
  recommendedCommitMessage: "Codex 시작 전 DB·소스·미구현 기능을 통합한 최종 Sprint 계획을 확정한다.",
  nextVersionBoundary: ["검증과 push 완료 후 0.24.22 DB Foundation Sprint 시작"],
  completionConditions: ["통합 계획 문서화", "버전/roadmap 동기화", "build/contract PASS", "commit/push 완료"],
  result: {
    completedSummary: ["Codex 전체 제품화 실행 순서를 통합하고 누락된 DB·소스 감사 작업을 선행 Sprint로 반영했다."],
    commitHash: "",
    verificationResult: "정적 문서·roadmap 검사 완료; 사용자 로컬 build/contract 확인 필요",
    remainingIssues: ["PG/provider, analytics/cookie, Instagram, final legal/vendor wording remain deferred"],
    userConfirmationRequired: true,
    userConfirmationResult: "사용자가 모든 준비 내용을 포함한 최종 계획 최신화를 승인했다.",
  },
};
