import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_16: RoadmapVersionDetail = {
  version: "0.24.16",
  title: "Codex/GPT 제품화 운영 문맥 구축",
  status: "implemented",
  userSummary: ["Codex와 ChatGPT가 같은 기준으로 제품화 Sprint를 이어갈 수 있도록 프로젝트 운영 문서를 고정한다."],
  visibleChanges: ["사용자 화면 변경 없음. 개발/문서 기준만 정리된다."],
  expectedUi: ["UI 변경 없음"],
  developmentPurpose: ["0.24.15 Productization Audit 이후 Codex/GPT가 같은 문맥으로 PB 구현을 시작하도록 운영 문서를 만든다."],
  developmentUiStructure: ["docs/project 문서 체계와 README/roadmap/current-state 연결"],
  scope: ["Codex Context 문서", "Project Decisions 문서", "Productization Guide 문서", "Release Checklist 문서", "README/docs/roadmap/current-state 연결"],
  outOfScope: ["화면 UI 변경", "소스 유틸 대형 리팩터링", "PDF/R2 정책", "Functions/Simulator 자동화 확장", "DB/R2/Seed/Reset/Cleanup 실행"],
  implementationPrinciples: ["문서는 적게 만들고 역할을 명확히 나눈다.", "AGENTS.md는 실행 규칙, docs/project는 프로젝트 문맥과 의사결정 기록을 담당한다."],
  successConditions: ["docs/project 4개 기준 문서 생성", "README/docs index/roadmap/current-state 연결", "DB/R2/package/UI 변경 없음"],
  failureConditions: ["운영 문서 중복 과다", "AGENTS.md와 docs/project 책임 혼선", "기능/UI 변경이 섞임"],
  cautions: ["이번 버전은 구현 Sprint 준비 작업이며 PB 구현 완료로 과장하지 않는다."],
  stopConditions: ["정책 변경 필요", "DB/R2/권한 의미 변경 필요"],
  permissionImpact: "read_only",
  permissionNotes: ["기존 UI affordance와 API guard 의미 유지"],
  dbImpact: "read_only",
  dbImpactNotes: ["기존 read/write 흐름을 변경하지 않는다."],
  r2Impact: "none",
  r2ImpactNotes: ["R2 영향 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["문서/버전 파일 변경 검토", "git diff --check"],
  manualTests: ["수동 UI 테스트 불필요 — 화면 동작 변경 없음"],
  expectedChangeAreas: ["docs/project/*", "README.md", "docs/README.md", "docs/codex-current-state.md", "docs/productization-roadmap.md", "docs/productization-backlog.md", "AGENTS.md", "lib/internal/roadmap/roadmap-0.24.16.ts", "lib/constants/version.ts"],
  recommendedCommitMessage: "docs: establish codex productization context",
  nextVersionBoundary: ["다음 구현 Sprint는 docs/project 문서를 먼저 읽고 PB-001/PB-005/PB-006 등 낮은 blast radius 항목부터 시작한다."],
  completionConditions: ["운영 문서 생성", "README/docs/roadmap/current-state 연결", "commit/push 완료"],
  result: { completedSummary: ["Codex/GPT 제품화 운영 문맥 문서 4개를 생성했다.", "README, docs index, current-state, productization roadmap, PB backlog를 새 문서 체계와 연결했다.", "0.24.16은 기능/UI 변경 없이 후속 PB 구현 Sprint의 기준을 고정했다."], commitHash: "pending", verificationResult: "ChatGPT patch generation only; local git diff/build not executed", remainingIssues: ["패치 적용 후 로컬에서 git diff --check 및 필요한 문서 검증을 실행해야 한다."], userConfirmationRequired: false, userConfirmationResult: "수동 UI 확인 불필요 — 화면 변경 없음" },
};
