import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_13: RoadmapVersionDetail = {
  version: "0.24.21.13",
  title: "Roadmap Type Contract Build Fix",
  status: "verification_pending",
  userSummary: ["0.24.21.12 roadmap 객체를 RoadmapVersionDetail 정식 타입 계약에 맞게 수정했다."],
  visibleChanges: ["앱 사용자 화면 변화 없음"],
  expectedUi: ["/roadmap에 0.24.21.13 빌드 수정 항목 표시"],
  developmentPurpose: ["Next.js TypeScript build 실패를 제거하고 DB 감사 메뉴 작업을 그대로 유지한다."],
  developmentUiStructure: ["roadmap metadata와 버전 메타데이터만 수정"],
  scope: ["roadmap type mismatch fix", "version bump", "build regression metadata"],
  outOfScope: ["DB 실행", "migration", "R2 변경", "기능 범위 확대"],
  implementationPrinciples: ["기존 RoadmapVersionDetail 타입을 변경하지 않는다.", "0.24.21.12 기능을 회귀시키지 않는다."],
  successConditions: ["dbNotes/storageImpact/testPlan/files 타입 오류 제거", "정식 필드로 치환"],
  failureConditions: ["roadmap type 우회", "any 사용", "DB 감사 메뉴 회귀"],
  cautions: ["사용자 로컬에서 next build 재확인 필요"],
  stopConditions: ["추가 TypeScript 오류 발견 시 해당 로그 기준 후속 수정"],
  permissionImpact: "none",
  permissionNotes: ["권한 변화 없음"],
  dbImpact: "none",
  dbImpactNotes: ["DB 접근·변경 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근·변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["TypeScript shape inspection", "db-readonly-audit-menu-contract"],
  manualTests: ["npm run build", "/roadmap 현재·다음 버전 확인"],
  expectedChangeAreas: ["lib/internal/roadmap/*", "lib/constants/version.ts", "commit-meta.md", "pending-tests.md"],
  recommendedCommitMessage: "fix: align DB audit roadmap metadata with type contract",
  nextVersionBoundary: ["빌드 통과 후 0.24.22 Codex Sprint A로 진행"],
  completionConditions: ["사용자 로컬 build 통과", "commit/push 완료"],
  result: {
    completedSummary: ["0.24.21.12 roadmap 객체의 잘못된 필드를 정식 타입 필드로 교체했다."],
    commitHash: "",
    verificationResult: "정적 타입 구조 점검 완료; 사용자 로컬 build 재확인 필요",
    remainingIssues: ["사용자 로컬 npm run build"],
    userConfirmationRequired: true,
    userConfirmationResult: "빌드 실패 로그에 따라 수정 요청됨",
  },
};
