import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_24: RoadmapVersionDetail = {
  version: "0.24.24",
  title: "WAFL UI Foundation",
  status: "verification_pending",
  userSummary: [
    "고객사 관리자 메인, worker, workspace 화면에 기존 WAFL 공통 UI 문법을 더 일관되게 적용한다.",
    "저장공간 사용량, 요금제/구성원 상태, empty/loading/error 상태, 반응형 카드 밀도를 실제 주요 화면에서 정리한다.",
  ],
  visibleChanges: [
    "고객사 관리자 메인의 요금제/저장공간/구성원 요약이 더 조밀하고 수치 중심으로 보인다.",
    "/workspace 바로가기 카드의 높이와 태블릿 컬럼 밀도가 줄어든다.",
    "파일 저장공간 카드와 관리자 메인이 같은 WAFL storage usage meter를 사용한다.",
  ],
  expectedUi: [
    "desktop에서는 주요 행동과 요약이 한 화면에서 더 잘 스캔된다.",
    "mobile/tablet에서는 카드가 과도하게 길어지지 않고 기존 drawer/modal/workorder 흐름을 유지한다.",
    "UI 확인이 필요한 버전이므로 사용자 실제 기기 확인 전까지 다음 버전으로 진행하지 않는다.",
  ],
  developmentPurpose: [
    "0.24.23 source cleanup 이후 첫 UI Foundation 적용 범위를 실제 주요 화면에 작게 고정한다.",
    "화면별 중복 storage progress, oversized cards, local empty state를 공통 WAFL 컴포넌트 쪽으로 당긴다.",
  ],
  developmentUiStructure: [
    "common WaflStorageUsageMeter",
    "admin operations dashboard storage summary",
    "workspace dashboard card density",
    "file storage summary plan card",
    "WAFL state panel contract for worker/workorder",
  ],
  scope: [
    "고객사 관리자 메인 화면의 요금제, 저장공간, 구성원 요약 UI Foundation 적용",
    "/workspace 바로가기 카드의 정보 밀도와 태블릿 컬럼 기준 조정",
    "저장공간 사용량 표시를 공통 storage usage meter로 통일",
    "empty/loading/error 상태가 WAFL state panel을 쓰는지 계약으로 확인",
    "APP_VERSION, roadmap, README, current-state 갱신",
  ],
  outOfScope: [
    "WaflUiCatalogPage 전체 분리",
    "AdminSettingsHub 전체 분리",
    "joinRequestRepository 재설계",
    "admin i18n 전체 분리",
    "deprecated PDF Worker 삭제",
    "중앙 logger 전체 도입",
    "DB schema, API authority, permission, tenant, package/lockfile 변경",
  ],
  implementationPrinciples: [
    "기존 WAFL 공통 컴포넌트를 우선 사용하고 화면별 중복 스타일을 새로 만들지 않는다.",
    "backend가 없는 미구현 결제, 가입, PDF, Export 기능을 가짜 완료 UI로 만들지 않는다.",
    "권한, tenant, workflow, route, repository, DB/R2 동작은 변경하지 않는다.",
    "새 50KB 이상 파일을 만들지 않는다.",
  ],
  successConditions: [
    "고객사 관리자 메인과 파일 저장공간 화면이 공통 WaflStorageUsageMeter를 사용",
    "/workspace 카드 밀도와 태블릿 컬럼 기준이 과도한 3컬럼 강제를 피함",
    "/worker의 기존 WorkOrderWorkspace 기능과 WAFL empty/loading state 계약 유지",
    "build, workspace-commonization, WAFL UI foundation contract, mutation audit PASS",
    "package/lockfile, DB migration, production DB/R2 변경 없음",
  ],
  failureConditions: [
    "UI 수정에 DB/API authority 변경이 필요함",
    "권한 또는 tenant 동작이 불명확해짐",
    "공통화가 대규모 화면 재작성으로 확대됨",
    "package 추가 또는 lockfile 변경 필요",
    "신규 50KB 이상 파일 생성",
  ],
  cautions: [
    "AdminSettingsHub는 이미 큰 파일이므로 이번 버전에서 전체 분리하지 않는다.",
    "시각/반응형 품질은 자동 테스트만으로 완료 판정하지 않고 사용자 확인이 필요하다.",
    "저장공간 수치는 기존 DB 기준 usage/quota 계약을 그대로 사용한다.",
  ],
  stopConditions: [
    "권한, tenant, API, repository, DB/R2 policy 변경이 필요함",
    "현재 route와 문서 정책이 충돌함",
    "build 또는 계약 실패를 범위 안에서 안전하게 해결할 수 없음",
    "사용량이나 문맥 부족으로 PC/mobile/tablet 품질 판단이 어려움",
  ],
  permissionImpact: "none",
  permissionNotes: ["UI 표시 구조만 조정하고 permission guard를 변경하지 않는다."],
  dbImpact: "none",
  dbImpactNotes: ["기존 저장공간 DB 조회 결과를 표시만 하며 DB write나 schema 변경은 없다."],
  r2Impact: "none",
  r2ImpactNotes: ["R2 object lifecycle, PDF, storage policy는 변경하지 않는다."],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: [
    "workspace-commonization verify profile",
    "wafl-ui-foundation-contract",
    "customer-workspace-compact-dashboard-contract",
    "roadmap-development-contract",
    "approved-workflow-contract",
    "unicode-encoding-contract",
    "pipeline-powershell-encoding-contract",
  ],
  manualTests: [
    "PC /workspace 관리자 메인: 요금제, 저장공간, 구성원, 작업 queue, 바로가기 스캔 확인",
    "모바일 /worker: drawer 배경 스크롤 차단, 닫은 뒤 스크롤 위치 유지, 모달 내부 스크롤 확인",
    "태블릿 /workspace: 카드 폭과 컬럼 균형, table/card overflow 확인",
    "/workspace/files: storage meter 수치와 기존 storage summary 비교",
  ],
  expectedChangeAreas: [
    "components/common/ui/WaflStorageUsageMeter.tsx",
    "components/admin/dashboard/AdminOperationsDashboard.tsx",
    "components/admin/dashboard/AdminConsoleSections.tsx",
    "components/admin/files/summary/PlanUsageCard.tsx",
    "tests/wafl-ui-foundation-contract.mjs",
    "tests/customer-workspace-compact-dashboard-contract.mjs",
    "tools/pipeline/verify-safe.ps1",
    "lib/internal/roadmap/*",
    "docs/codex-current-state.md",
    "docs/productization-roadmap.md",
  ],
  recommendedCommitMessage: "WAFL UI Foundation을 관리자 메인과 저장공간 요약에 적용한다.",
  nextVersionBoundary: [
    "사용자 UI/반응형 확인 후 0.24.25 Authorization, Runtime Boundary, and Opaque Routing으로 이동",
    "추가 UI 수정이 필요하면 0.24.24 follow-up으로 처리하고 0.24.25 자동 진입 금지",
  ],
  completionConditions: [
    "workspace-commonization Verify PASS",
    "APP_VERSION/docs/roadmap 동기화",
    "commit/push 완료",
    "4. Newest handoff 생성",
    "사용자 확인 전 0.24.25 자동 진입 금지",
  ],
  result: {
    completedSummary: [
      "공통 WaflStorageUsageMeter를 추가하고 관리자 메인/파일 저장공간 카드에 적용했다.",
      "/workspace 바로가기 카드 밀도와 태블릿 컬럼 기준을 조정했다.",
      "권한, tenant, workflow, API, DB, R2, package/lockfile은 변경하지 않았다.",
    ],
    commitHash: "",
    verificationResult: "verification pending",
    remainingIssues: [
      "PC/mobile/tablet 실제 화면 확인은 사용자 확인 필요",
      "AdminSettingsHub 전체 UI Foundation 적용은 후속 cleanup으로 남김",
      "0.24.25 Authorization/Runtime/Opaque Routing은 사용자 승인 전 시작하지 않음",
    ],
    userConfirmationRequired: true,
    userConfirmationResult: "0.24.25 시작 전 사용자 승인 필요",
  },
};
