import type { RoadmapVersionDetail } from './types';
export const ROADMAP_0_24_21_12: RoadmapVersionDetail = {
  version: '0.24.21.12',
  title: 'DB Read-only Audit PowerShell Menu',
  status: 'completed',
  userSummary: ['개발·테스트 DB에서 reconciliation, constraint readiness, index readiness를 안전하게 실행하는 PowerShell 메뉴를 추가했다.'],
  visibleChanges: ['개발/테스트 도구 메뉴 30~32번이 추가된다.'],
  expectedUi: ['앱 사용자 화면 변화 없음'],
  developmentPurpose: ['Codex Sprint A 전 실제 DB 상태를 비파괴적으로 확인한다.'],
  developmentUiStructure: ['PowerShell menu and result reports'],
  scope: ['read-only audit runner','dev/test fingerprint guard','result files'],
  outOfScope: ['production execution','schema mutation','migration'],
  implementationPrinciples: ['SELECT/WITH only','BEGIN READ ONLY','approved dev/test DB only'],
  successConditions: ['three menu commands run safely','report files created'],
  failureConditions: ['production target','fingerprint mismatch','mutation SQL token'],
  cautions: ['result rows may include internal identifiers; do not share externally'],
  stopConditions: ['unexpected schema mismatch','query permission failure'],
  permissionImpact: 'guarded',
  permissionNotes: ['dev/test approved DB only'],
  dbImpact: 'read_only',
  dbNotes: ['No mutation'],
  storageImpact: 'none',
  storageNotes: [],
  testPlan: ['node tests/db-readonly-audit-menu-contract.mjs','run menu 30,31,32 in dev/test'],
  files: ['tools/pipeline/peacebypiece-auto-pipeline.ps1','scripts/run-readonly-db-audit.mjs','db/audits/0.24.21.12-constraint-readiness-readonly.sql','db/audits/0.24.21.12-index-readiness-readonly.sql'],
  relatedDocs: ['docs/project/28-database-source-of-truth-safe-migration-design.md'],
};
