import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_13: RoadmapVersionDetail = {
  version: "0.24.13",
  title: "문서/폴더 정리 2차",
  status: "planned",
  userSummary: ["기능 개발을 더 이어가기 전에 Codex가 읽는 문서와 폴더 기준을 다시 정리한다."],
  visibleChanges: ["사용자 화면 기능은 바꾸지 않고, 현재 기준 문서와 보관 문서의 위치와 역할을 명확히 한다."],
  expectedUi: ["`/roadmap`에는 1.0 전 품질 확보를 위한 의도적 재배치로 표시된다."],
  developmentPurpose: ["root 문서, docs 보관문서, current-state, ZIP/repo-state/Vercel QA 흐름의 기준을 정리해 Codex 검색 노이즈를 줄인다."],
  developmentUiStructure: ["UI 구현 없이 문서 index와 roadmap contract만 갱신한다."],
  scope: [
    "root 문서 정리 기준 확정",
    "docs 보관문서/legacy/history 위치 정리 기준 확정",
    "Codex 검색 노이즈를 줄이는 현재 기준 문서 매니페스트 보강",
    "docs index, 현재기준, 보관문서 기준 명확화",
    "ZIP/repo-state/Vercel QA 흐름 문서화",
  ],
  outOfScope: ["APP_VERSION 변경", "기능 코드 수정", "대형 파일 이동/삭제", "PDF/R2/Simulator 기능 구현"],
  implementationPrinciples: ["기존 roadmap 취소가 아니라 1.0 전 제품화 품질을 높이기 위한 재배치로 기록한다."],
  successConditions: ["roadmap 문서와 internal contract 일치", "docs/current-state 기준이 Codex 시작점으로 충분함", "roadmap contract PASS"],
  failureConditions: ["기존 roadmap 항목 삭제", "APP_VERSION 변경", "보관 기준 없이 파일 이동"],
  cautions: ["문서 이동이나 삭제가 필요하면 참조를 먼저 확인하고 별도 사용자 확인을 받는다."],
  stopConditions: ["대량 파일 이동/삭제 필요", "기능 개발 범위로 확대 필요"],
  permissionImpact: "none",
  permissionNotes: ["권한 정책 변경 없음"],
  dbImpact: "none",
  dbImpactNotes: ["DB 접근 또는 변경 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근 또는 변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["roadmap-development-contract", "internal-system-routes-contract"],
  manualTests: ["문서 index와 current-state 기준을 사람이 읽어 모순이 없는지 확인"],
  expectedChangeAreas: ["docs/productization-roadmap.md", "docs/README.md", "docs/codex-current-state.md", "lib/internal/roadmap/*"],
  recommendedCommitMessage: "docs: reorganize productization roadmap documentation",
  nextVersionBoundary: ["0.24.14는 Functions catalog와 자동화 상태 정리를 다룬다."],
  completionConditions: ["문서/contract 정리 완료", "roadmap contract PASS", "APP_VERSION 0.24.12 유지", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: false, userConfirmationResult: "" },
};
