import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_17: RoadmapVersionDetail = {
  version: "0.24.21.17",
  title: "Pre-Codex Authority and Document Consistency Gate",
  status: "verification_pending",
  userSummary: [
    "Codex가 과거 UI-first 계획을 현재 지시로 오인하지 않도록 문서 authority를 단일화했다.",
    "공개 사이트, /id-control 보존, PowerShell 후속 메뉴 추적을 최종 Master Plan에 보강했다.",
  ],
  visibleChanges: ["/roadmap 현재 버전과 다음 DB Foundation 경계 최신화"],
  expectedUi: ["고객 업무 UI 변경 없음", "문서·roadmap authority만 정리"],
  developmentPurpose: ["0.24.22 DB Foundation을 추가 계획 재작성 없이 안전하게 시작할 수 있는 최종 문서 게이트를 만든다."],
  developmentUiStructure: ["active authority manifest", "historical/superseded boundary", "PowerShell follow-up registry"],
  scope: [
    "README·current-state·roadmap 버전/authority 정합성",
    "문서 19·23·28의 UI-first 충돌 제거 또는 historical 격리",
    "문서 31에 공개 사이트·id-control·PowerShell 추적 보강",
    "문서 32 authority consistency gate 추가",
  ],
  outOfScope: ["runtime 기능 구현", "DB migration 실행", "DB/R2/PG mutation", "package 변경"],
  implementationPrinciples: [
    "31번 문서만 active Sprint authority로 사용한다.",
    "과거 계획은 삭제보다 historical 표기를 우선한다.",
    "0.24.22는 evidence-first DB Foundation으로 유지한다.",
  ],
  successConditions: [
    "README/current-state/roadmap가 0.24.21.17과 0.24.22 DB Foundation을 표시",
    "active manifest에 UI-first 0.24.22 지시가 없음",
    "문서 31에 공개 사이트, id-control, PowerShell 메뉴 추적이 포함",
    "문서 32 GO/STOP authority gate 존재",
  ],
  failureConditions: ["과거 UI-first 계획이 active 지시로 남음", "runtime/schema mutation 발생", "active authority가 둘 이상 존재"],
  cautions: ["과거 버전 기록의 역사적 문장은 삭제하지 않고 superseded로 해석한다."],
  stopConditions: ["문서 정리를 넘어 실제 DB 연결·migration·기능 구현이 필요하면 중단"],
  permissionImpact: "none",
  permissionNotes: ["권한 구현 변경 없음"],
  dbImpact: "none",
  dbImpactNotes: ["DB 계획 문서만 정리하며 연결·실행하지 않음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 영향 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["roadmap/version static contract", "document authority scan", "unicode filename contract"],
  manualTests: ["README/current-state/roadmap 확인", "문서 31·32 GO/STOP 검토", "/roadmap 현재 0.24.21.17·다음 0.24.22 확인", "npm run build"],
  expectedChangeAreas: ["README.md", "docs/codex-current-state.md", "docs/productization-roadmap.md", "docs/project/19,23,28,31,32", "lib/internal/roadmap/*"],
  recommendedCommitMessage: "Codex 시작 전 문서 authority와 DB Foundation 진입 기준을 최종 정리한다.",
  nextVersionBoundary: ["검증과 push 완료 후 0.24.22 DB Foundation 시작"],
  completionConditions: ["authority 충돌 정리", "버전/roadmap 동기화", "build/contract PASS", "commit/push 완료"],
  result: {
    completedSummary: ["Codex 시작 문서의 현재/과거 계획을 분리하고 단일 active execution authority를 확정했다."],
    commitHash: "",
    verificationResult: "정적 문서·roadmap 검사 완료; 사용자 로컬 build/contract 확인 필요",
    remainingIssues: ["PG/provider, analytics/cookie, Instagram, final legal/vendor wording remain deferred"],
    userConfirmationRequired: false,
    userConfirmationResult: "문서 정합성 정리 범위이며 제품 정책 추가 결정은 필요하지 않다.",
  },
};
