import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21: RoadmapVersionDetail = {
  version: "0.24.21",
  title: "통합 검증 체크포인트",
  status: "verification_pending",
  userSummary: ["고객 테스트 전에 PC, 태블릿, 모바일, 권한, PDF, R2, functions, simulator를 통합 검증한다."],
  visibleChanges: ["Vercel 배포본을 운영이 아닌 실기기 QA 환경으로 보고, 고객 테스트 전 보완 목록을 확정한다."],
  expectedUi: ["수동 확인이 필요한 UI/PDF/responsive 항목은 자동 테스트 PASS와 분리해 표시한다."],
  developmentPurpose: ["PC/iPad mini/Galaxy Tab/mobile 실기기 QA와 권한별 화면/API 접근, workspace/worker/PDF/R2/functions/simulator 통합 검증을 수행한다."],
  developmentUiStructure: ["검증 결과와 보완 목록을 roadmap result와 handoff 문서에 반영한다."],
  scope: ["PC/iPad mini/Galaxy Tab/mobile 실기기 QA", "권한별 화면/API 접근", "workspace/worker/PDF/R2/functions/simulator 통합 검증", "Vercel QA 기준 확인", "고객 테스트 전 보완 목록 확정"],
  outOfScope: ["새 기능 추가", "대형 리팩터링", "운영 전환", "production DB/R2 접근"],
  implementationPrinciples: ["자동 검증과 사용자 수동 검증을 명확히 분리하고 실패/skip 이유를 숨기지 않는다."],
  successConditions: ["필수 자동 검증 PASS", "필수 수동 QA 완료 또는 보완 목록 확정", "권한별 접근 결과 기록", "Vercel QA 기준 확인"],
  failureConditions: ["운영 환경으로 오인", "사용자 확인 전 완료 처리", "검증 실패 은폐"],
  cautions: ["Vercel 배포본은 아직 운영이 아니라 실기기 QA 환경이다."],
  stopConditions: ["production 데이터 접근 필요", "고객 테스트 여부 사용자 결정 필요", "DB/R2 destructive 실행 필요"],
  permissionImpact: "guarded",
  permissionNotes: ["system administrator, customer administrator, general user, worker, unauthenticated 접근 결과를 구분한다."],
  dbImpact: "guarded",
  dbImpactNotes: ["dev/test 승인 범위의 read/smoke만 허용하고 destructive mutation은 금지"],
  r2Impact: "guarded",
  r2ImpactNotes: ["R2 실제 mutation은 별도 승인 필요"],
  migrationRequired: false,
  migrationNotes: "통합 검증 중 migration 필요성이 발견되면 별도 버전으로 분리한다.",
  automaticTests: ["full verify-safe matrix", "E2E", "Smoke", "Permissions", "PDF/R2/functions/simulator contracts"],
  manualTests: ["PC QA", "iPad mini QA", "Galaxy Tab QA", "mobile QA", "role QA", "PDF visual QA", "Vercel QA"],
  expectedChangeAreas: ["tests/*", "docs/productization-roadmap.md", "docs/codex-current-state.md", "lib/internal/roadmap/*"],
  recommendedCommitMessage: "chore: complete pre-customer qa checkpoint",
  nextVersionBoundary: ["이후 버전은 0.24.21 통합 검증 결과와 고객 테스트 전 보완 목록에 따라 결정한다."],
  completionConditions: ["통합 검증 완료", "고객 테스트 전 보완 목록 확정", "사용자 확인 완료", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: true, userConfirmationResult: "미확인" },
};
