import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_34_4: RoadmapVersionDetail = {
  version: "0.24.34.4",
  title: "Workorder Runtime Recovery, Canonical WAFL Size Panel, and Signup Product E2E",
  status: "implemented",
  userSummary: [
    "작업지시서 목록 무한 로딩과 상세 런타임 렌더를 복구한다.",
    "치수 입력은 중앙 본문 중복 영역에서 제거하고 오른쪽 패널과 모바일 related sheet로 정렬한다.",
    "0.24.34.4는 0.24.35를 시작하지 않고 localhost 제품 evidence로 PRODUCT_VERIFIED를 확정한다.",
  ],
  visibleChanges: [
    "작업지시서 상세 중앙 본문에는 치수 패널이 중복 표시되지 않는다.",
    "오른쪽 패널에서 첨부 파일, 공장 전달사항, 사이즈 스펙 순서로 확인할 수 있다.",
    "치수 입력과 수정은 WAFL 공통 modal, button, number input, select, table primitive를 사용한다.",
  ],
  expectedUi: [
    "Desktop: WorkOrderSidePanel 안에서 첨부 파일, 공장 전달사항, 사이즈 스펙 순서로 표시한다.",
    "Mobile/iPad: 관련 정보 sheet에서 사이즈 탭을 제공하고 nested dialog 없이 편집한다.",
    "고객 화면에는 DB, R2, Worker, fake, readiness 같은 구현 단어가 노출되지 않는다.",
  ],
  developmentPurpose: [
    "0.24.34.3.1 제품 완료 기준을 실제 UI 런타임 보정 버전에 적용한다.",
    "정적 구현 보고가 아니라 localhost desktop/mobile/iPad browser evidence로 완료 상태를 판단한다.",
  ],
  developmentUiStructure: [
    "Host component: components/workorder/sidepanel/shared/WorkOrderSidePanelSections.tsx",
    "Forbidden host: components/workorder/detail/views/WorkOrderDetailDesktopSections.tsx central body",
    "Canonical modal: components/common/modal/ModalShell.tsx",
    "Canonical controls: WaflButton, WaflNumberInput, WaflSelect, WaflDataTable*",
  ],
  scope: [
    "APP_VERSION 0.24.34.4 갱신",
    "작업지시서 치수 패널 side panel 이동",
    "중앙 detail duplicate 제거",
    "WAFL 공통 modal/input/select/button/table 적용",
    "loading/error/retry state 계약",
    "public signup product E2E와 UI evidence profile 연결",
    "desktop/mobile/iPad screenshot manifest 산출물 규칙",
  ],
  outOfScope: [
    "0.24.35 Company-wide Export Execution",
    "production DB/R2/Worker mutation",
    "DB migration",
    "actual PG/email provider",
    "Full Reset",
  ],
  implementationPrinciples: [
    "UI 완료는 LEVEL_4_PRODUCT_VERIFIED evidence가 있을 때만 완료로 보고한다.",
    "Full Reset 없이 API, loading state, schema/migration 상태를 먼저 진단한다.",
    "artifacts/ui-qa 산출물은 Git과 source ZIP에서 제외한다.",
  ],
  successConditions: [
    "중앙 WorkOrderDetail body에 WorkOrderSizeSpecPanel mount가 없다.",
    "WorkOrderSidePanelSections와 mobile side panel에는 WorkOrderSizeSpecPanel이 있다.",
    "치수 패널은 ModalShell, WaflButton, WaflNumberInput, WaflSelect, WaflDataTable primitive를 import한다.",
    "direct fixed overlay와 local role=dialog shell이 없다.",
    "product-ui-runtime-verification profile이 version, source, contract, build, browser evidence metadata를 검증한다.",
    "desktop/mobile/iPad browser matrix가 PASS이고 Product Verified가 true다.",
  ],
  failureConditions: [
    "static contract만으로 PRODUCT_VERIFIED를 선언한다.",
    "브라우저 screenshot/manifest가 없는데 완료로 보고한다.",
    "production mutation 또는 Worker 배포가 필요해진다.",
  ],
  cautions: [
    "실제 Google OAuth, 실제 device Safari, actual Vercel session refresh는 별도 수동 QA로 남을 수 있다.",
  ],
  stopConditions: [
    "destructive migration 또는 Full Reset 필요 증거가 발견된다.",
    "browser E2E 같은 단계가 두 번 실패한다.",
    "residual DB/R2가 0이 아니다.",
    "0.24.35 범위가 필요하다.",
  ],
  permissionImpact: "guarded",
  permissionNotes: ["기존 workspace/system-admin 권한 모델 유지"],
  dbImpact: "guarded",
  dbImpactNotes: ["DB fixture mutation 없음"],
  r2Impact: "guarded",
  r2ImpactNotes: ["R2 mutation 없음"],
  migrationRequired: false,
  migrationNotes: "No migration in 0.24.34.4.",
  automaticTests: [
    "product-ui-runtime-verification",
    "workorder product UI runtime contract",
    "public signup authenticated E2E/profile contracts",
    "targeted ESLint",
    "tsc --noEmit",
    "next build",
  ],
  manualTests: [
    "실제 Google OAuth 왕복",
    "실제 iPhone/iPad Safari 파일 선택기와 safe-area",
    "사용자 실기기 최종 시각 판단",
  ],
  expectedChangeAreas: [
    "components/workorder/detail/WorkOrderSizeSpecPanel.tsx",
    "components/workorder/sidepanel/*",
    "lib/workorder/workspace/builders/detailBuilders.ts",
    "tests/*",
    "tools/pipeline/*",
    "docs/*",
    "lib/internal/roadmap/*",
  ],
  recommendedCommitMessage: "0.24.34.4 작업지시서 런타임 복구와 제품 UI 검증 완료",
  nextVersionBoundary: ["0.24.35 Company-wide Export Execution starts only after 0.24.34.4 evidence is complete."],
  completionConditions: [
    "source/contract/build verification",
    "localhost browser evidence manifest",
    "Product Verified true",
    "commit/push",
    "4. Newest 갱신",
  ],
  result: {
    completedSummary: [
      "LEVEL_4_PRODUCT_VERIFIED",
      "Workorder list/detail runtime PASS",
      "Right-side size panel PASS",
      "Desktop/mobile/iPad browser matrix PASS",
      "Public signup browser verification 20/20 PASS",
      "HMR origin mismatch fixed by using localhost consistently",
    ],
    commitHash: "pending",
    verificationResult: "PASS - product-ui-runtime-verification",
    remainingIssues: [],
    userConfirmationRequired: false,
    userConfirmationResult: "PRODUCT_VERIFIED - localhost desktop/mobile/iPad evidence completed",
  },
};
