import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_16: RoadmapVersionDetail = {
  version: "0.24.16",
  title: "WAFL 컴포넌트 적용/공통화 1차",
  status: "planned",
  userSummary: ["반복 UI 구조를 WAFL 공통 컴포넌트로 안전하게 교체한다."],
  visibleChanges: ["page shell, section, button, filter, empty/loading/error 상태가 더 일관되게 보인다."],
  expectedUi: ["큰 화면은 하나씩 적용하며 UI 변경은 실기기 QA 필요 항목으로 남긴다."],
  developmentPurpose: ["0.24.15 감사 결과 중 반복 UI 구조를 WAFL 컴포넌트로 교체해 화면 품질과 유지보수성을 높인다."],
  developmentUiStructure: ["page shell, section, button, filter, empty/loading/error 상태를 기존 WAFL 컴포넌트에 맞춘다."],
  scope: ["반복 UI 구조 WAFL 컴포넌트 교체", "page shell/section/button/filter 공통화", "empty/loading/error 상태 공통화", "큰 화면 단위의 안전한 적용"],
  outOfScope: ["소스 유틸 대형 리팩터링", "PDF/R2 정책", "Functions/Simulator 자동화 확장"],
  implementationPrinciples: ["화면별 blast radius를 작게 유지하고 기존 권한과 데이터 흐름을 바꾸지 않는다."],
  successConditions: ["대상 화면 build/contract PASS", "UI 변경 사항 수동 QA 항목 기록", "권한/API 동작 유지"],
  failureConditions: ["여러 큰 화면을 한 번에 변경", "기능 동작 회귀", "수동 QA 전 완료 처리"],
  cautions: ["시각/반응형 변경은 사용자 확인 필요 상태로 남긴다."],
  stopConditions: ["제품 디자인 선택 필요", "권한 또는 데이터 shape 변경 필요"],
  permissionImpact: "read_only",
  permissionNotes: ["기존 UI affordance와 API guard 의미 유지"],
  dbImpact: "read_only",
  dbImpactNotes: ["기존 read/write 흐름을 변경하지 않는다."],
  r2Impact: "none",
  r2ImpactNotes: ["R2 영향 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["Build", "relevant UI contract tests", "permission guard contract"],
  manualTests: ["변경 화면 PC/tablet/mobile 실기기 QA"],
  expectedChangeAreas: ["app/*", "features/*", "components/common/ui/*", "tests/*"],
  recommendedCommitMessage: "refactor: apply wafl components to repeated screens",
  nextVersionBoundary: ["0.24.17은 코드 util, hardcoding, i18n, 대형 파일 분리를 단계적으로 처리한다."],
  completionConditions: ["대상 화면 적용 완료", "required tests PASS", "사용자 확인 필요 항목 기록", "commit/push 완료"],
  result: { completedSummary: [], commitHash: "", verificationResult: "", remainingIssues: [], userConfirmationRequired: true, userConfirmationResult: "미확인" },
};
