import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_1: RoadmapVersionDetail = {
  version: "0.24.21.1",
  title: "시스템 기본 분류·사이즈 스펙·Seed 계약",
  status: "verification_pending",
  userSummary: ["시스템 관리자 기본 생산품 분류와 제품별 사이즈 스펙, 신규 고객사 provisioning 및 기존 고객사 backfill 기준을 Codex 구현 입력으로 확정한다."],
  visibleChanges: ["사용자 UI나 DB를 바꾸지 않고 시스템 기본 데이터와 안전한 seed/backfill 계약 문서를 추가한다."],
  expectedUi: ["후속 구현에서 시스템 관리자가 1차/2차/3차 분류, 스펙 항목, template version과 적용 상태를 조회한다."],
  developmentPurpose: ["현재 3개 경로뿐인 제품 유형 seed를 실제 의류 운영 범위로 확장하기 전에 데이터 소유권과 안전 경계를 고정한다."],
  developmentUiStructure: ["시스템 기본 catalog, 고객사 enable/custom 값, provisioning, dry-run/backfill, simulator fixture를 분리한다."],
  scope: ["기본 제품 분류 baseline", "사이즈 스펙 catalog", "제품군별 스펙 매핑", "seed/backfill idempotency", "시스템 관리자 요구사항", "Codex DB Sprint 분리"],
  outOfScope: ["SQL 작성/실행", "DB schema/migration", "production mutation", "시스템 관리자 UI 구현", "가입/결제 홈페이지 구현"],
  implementationPrinciples: ["stable code를 사용한다.", "고객사 설정을 덮어쓰지 않는다.", "기존 문서 참조를 보존한다.", "production 적용 전 dry-run evidence를 요구한다."],
  successConditions: ["현재 seed gap이 기록됨", "분류와 스펙 권장 baseline 존재", "신규 고객사 provisioning 순서 존재", "기존 고객사 backfill 안전 계약 존재", "Codex Sprint 경계 존재"],
  failureConditions: ["SQL 또는 DB 실행", "고객사 비활성 설정 덮어쓰기", "stable code 없이 이름만 seed", "schema 변경을 UI Sprint에 혼합"],
  cautions: ["분류와 스펙 목록은 구현 전 현재 schema 중복을 다시 확인한다.", "선택 정책은 Codex가 임의 확정하지 않는다."],
  stopConditions: ["production DB 실행 필요", "destructive migration 필요", "기존 고객사 데이터 의미 변경 필요"],
  permissionImpact: "none",
  permissionNotes: ["문서/roadmap 변경이며 system-admin permission을 변경하지 않는다."],
  dbImpact: "none",
  dbImpactNotes: ["DB 조사 기준만 문서화하며 read/write/seed/migration을 실행하지 않는다."],
  r2Impact: "none",
  r2ImpactNotes: ["R2 영향 없음"],
  migrationRequired: false,
  migrationNotes: "이번 문서 패치는 DB Migration 없음. 후속 조사에서 additive migration 필요 여부를 별도 판단한다.",
  automaticTests: ["TypeScript/build", "roadmap-development-contract", "문서 경로/version 계약", "Flat ZIP 무결성"],
  manualTests: ["docs index의 19번 문서 링크", "/roadmap 현재 0.24.21.1/다음 0.24.21.2 표시", "seed gap과 사용자 결정 항목 검토"],
  expectedChangeAreas: ["docs/project/19-system-default-catalog-and-seed-spec.md", "docs/codex-current-state.md", "lib/constants/version.ts", "lib/internal/roadmap/*", "pending-tests.md"],
  recommendedCommitMessage: "docs: define system catalog and seed contract",
  nextVersionBoundary: ["0.24.21.2에서 고객사 가입 요청, 약관 동의, 승인, Trial provisioning 계약을 정리한다."],
  completionConditions: ["문서 작성", "roadmap/version 동기화", "required checks PASS", "commit/push 완료"],
  result: {
    completedSummary: ["현재 system standards seed의 제품 분류 부족을 확인하고 제품 분류·사이즈 스펙·provisioning·backfill 계약을 작성했다."],
    commitHash: "",
    verificationResult: "수동 패치 생성 완료; 적용 후 roadmap-development-contract와 build 확인 필요",
    remainingIssues: ["실제 schema 조사와 SQL 구현", "사용자 선택 정책", "시스템 관리자 UI와 simulator fixture 구현"],
    userConfirmationRequired: true,
    userConfirmationResult: "기본 활성 분류 범위, 단면/둘레 정책, 고객사 이름 변경 범위, 기존 고객사 자동 enable 정책은 추후 결정 가능",
  },
};
