import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_12: RoadmapVersionDetail = {
  version: "0.24.12",
  title: "일반 사용자 workspace 및 worker 공통화",
  status: "user_test_needed",
  userSummary: [
    "/worker 화면의 크기와 정보 밀도를 줄인다.",
    "태블릿 가로에서 workspace 패널 스크롤을 정상화한다.",
    "작업지시서와 발주서의 화면 구조와 피드백을 통일한다.",
    "저장 중 다른 값이 사라지지 않도록 저장 흐름을 안정화한다.",
  ],
  visibleChanges: [
    "/worker와 일반 사용자 workspace가 더 작은 여백과 낮은 정보 밀도로 표시된다.",
    "작업지시서와 발주서에서 목록, 본문, 보조 패널의 배치 기준이 같아진다.",
    "저장 중에는 대상 항목만 대기 상태가 되고 다른 입력값이나 선택 상태가 사라지지 않는다.",
    "저장 성공, 실패, 대기 상태 toast가 화면마다 다르게 보이지 않는다.",
    "새로고침 뒤에도 마지막 저장 결과가 DB 기준으로 유지되는지 확인할 수 있다.",
  ],
  expectedUi: [
    "PC는 목록, 상세, 보조 정보를 한 화면에 두는 3패널 구조를 기본으로 검토한다.",
    "iPad mini 가로는 2패널 전환이 더 안정적인지 검토하고, 억지 3패널을 만들지 않는다.",
    "큰 태블릿 가로는 최소 폭이 충족될 때 3패널을 허용한다.",
    "모바일과 태블릿 세로는 1패널 중심으로 두고 목록은 drawer 또는 전환 구조로 둔다.",
    "각 패널은 독립 스크롤을 가지며, 한 패널의 긴 내용이 다른 패널의 버튼이나 상단바를 밀지 않는다.",
    "/worker는 큰 카드식 밀도를 줄이고 실제 작업자가 반복해서 보는 정보 위주로 재배치한다.",
  ],
  developmentPurpose: [
    "0.24.12 기능 구현 전에 일반 사용자 workspace, legacy /worker, workorder, material-order의 공통 UI/저장 기준을 확정한다.",
    "작업지시서와 발주서가 서로 다른 shell, toast, 저장 queue를 갖는 문제를 줄인다.",
    "반응형 레이아웃 변경과 저장 안정화가 DB schema 또는 권한 의미 변경으로 번지지 않게 한다.",
  ],
  developmentUiStructure: [
    "workorder/material-order shell 공통화를 우선 검토한다.",
    "workspace layout mode는 PC 3패널, compact tablet 2패널, mobile/portrait 1패널 기준으로 분리한다.",
    "패널 독립 스크롤은 shell 레벨에서 처리하고 개별 화면이 body scroll에 기대지 않게 한다.",
    "toast와 저장 feedback은 공통 hook 또는 presenter로 모으되 기존 기능 의미를 바꾸지 않는다.",
    "modal/focus는 공통 modal 정책을 따르며 개별 화면의 pointer/touch blur workaround를 늘리지 않는다.",
  ],
  scope: [
    "일반 사용자 `/workspace/workorders` 화면 구조와 저장 feedback 정리",
    "일반 사용자 `/workspace/material-orders` 화면 구조와 저장 feedback 정리",
    "legacy `/worker` 화면의 density 축소와 route 정책 검토",
    "PC 3패널, 큰 태블릿 가로 3패널, iPad mini 가로 2패널, 모바일/태블릿 세로 1패널 기준 검증",
    "entity별 single save queue와 stale response 방지",
    "저장 후 refresh persistence 확인",
    "기존 권한 의미 유지",
  ],
  outOfScope: [
    "0.24.12 단계에서 DB Migration을 만들지 않는다.",
    "PDF 생성, R2 저장, supplier/material-order PDF 정책 확정은 roadmap 재배치 후 0.24.19로 넘긴다.",
    "새 권한 체계, tenant isolation 정책 변경, 사용자 데이터 shape 변경은 하지 않는다.",
    "일반 사용자 기능 자체의 신규 업무 범위 확대는 하지 않는다.",
    "modal/focus 전체 재설계는 하지 않고, 저장/반응형 작업에 직접 필요한 공통 정책 적용만 포함한다.",
  ],
  implementationPrinciples: [
    "기존 shared component, layout policy, repository, permission helper를 먼저 사용한다.",
    "화면 density는 줄이되 정보 손실이나 권한 우회가 생기지 않게 한다.",
    "동일 entity에 대한 저장은 single save queue로 직렬화한다.",
    "늦게 도착한 stale response가 최신 입력값을 덮어쓰지 않게 request identity 또는 version 기준을 둔다.",
    "toast 문구와 pending/failed/retry 상태는 workorder와 material-order가 같은 규칙을 따른다.",
    "refresh persistence는 UI state가 아니라 DB/API 응답 기준으로 확인한다.",
  ],
  successConditions: [
    "PC에서 목록, 상세, 보조 패널이 겹치지 않고 독립 스크롤된다.",
    "iPad mini 가로에서 workspace 패널 스크롤이 정상이며 화면 하단 액션이 가려지지 않는다.",
    "큰 태블릿 가로에서 폭이 충분할 때 3패널이 안정적으로 표시된다.",
    "모바일 및 태블릿 세로에서 1패널 흐름이 깨지지 않는다.",
    "workorder와 material-order의 shell, toast, 저장 대기/실패/성공 피드백이 같은 기준으로 보인다.",
    "저장 중 다른 값이 사라지지 않고, stale response가 최신 입력을 덮지 않는다.",
    "새로고침 후 저장된 값이 유지된다.",
    "권한 의미, DB schema, R2 동작은 기존과 같다.",
  ],
  failureConditions: [
    "자동 테스트가 PASS해도 iPad mini 가로 또는 모바일에서 패널/버튼/입력이 겹치면 실패다.",
    "저장 중 이전 값, 다른 필드, 선택 상태가 사라지면 실패다.",
    "늦은 응답이 최신 입력을 되돌리면 실패다.",
    "작업지시서와 발주서가 서로 다른 toast/저장 상태 규칙을 계속 사용하면 실패다.",
    "권한 의미가 바뀌거나 API/server guard가 UI affordance와 달라지면 실패다.",
    "DB Migration이 필요해지면 이 버전 범위를 벗어난 것으로 보고 중단한다.",
  ],
  cautions: [
    "/worker는 현재 session 기반 legacy route 성격이 있으므로 route 정책 변경은 별도 사용자 판단이 필요할 수 있다.",
    "UI/반응형 변경은 사람 눈 검증 전 완료 상태로 전환하지 않는다.",
    "modal/focus 문제는 공통 정책에 직접 닿는 범위만 포함하고, 전체 modal 재설계로 확장하지 않는다.",
    "저장 queue 공통화는 workorder/material-order의 기존 repository contract를 깨지 않아야 한다.",
  ],
  stopConditions: [
    "DB schema 또는 migration이 필요하다고 확인되는 경우",
    "권한 정책 또는 tenant isolation 의미 변경이 필요한 경우",
    "PDF/R2 저장 정책 결정이 선행되어야 하는 구현으로 번지는 경우",
    "iPad mini/모바일 수동 확인 없이는 완료 판단이 불가능한 경우",
    "required build 또는 Mutation Audit이 요청 범위와 무관한 환경 문제 없이 실패하는 경우",
  ],
  permissionImpact: "guarded",
  permissionNotes: [
    "기존 workorder/material-order 권한 의미를 유지한다.",
    "UI 버튼 노출과 API/server handler 검증이 같은 capability 기준을 사용해야 한다.",
    "일반 사용자, 고객 관리자, 권한 없는 사용자, system administrator를 구분해 접근 결과를 확인한다.",
  ],
  dbImpact: "read_only",
  dbImpactNotes: [
    "기본 전제는 DB Migration 없음이다.",
    "기존 저장 API와 repository 계약을 유지하며, 저장 안정화는 호출 순서와 response 처리에서 해결한다.",
    "실제 DB mutation은 기능 검증 환경에서 기존 저장 동작을 확인하는 범위로만 다룬다.",
  ],
  r2Impact: "none",
  r2ImpactNotes: [
    "R2 정책 변경 없음.",
    "PDF/R2 저장, 재생성, 삭제 정책은 R2/Simulator 테스트 기반 0.24.18과 PDF/R2 정책 0.24.19 범위로 넘긴다.",
  ],
  migrationRequired: false,
  migrationNotes: "0.24.12의 기본 전제는 DB Migration 없음이다. Migration이 필요해지면 중단하고 별도 범위로 재정의한다.",
  automaticTests: [
    "roadmap-development-contract",
    "workspace responsive/layout contract",
    "workorder/material-order shell commonization contract",
    "single save queue and stale response contract",
    "toast feedback contract",
    "permission guard contract",
    "Build",
    "Mutation Audit",
  ],
  manualTests: [
    "PC: workorder/material-order 3패널, 독립 스크롤, 저장 feedback 확인",
    "iPad mini 가로: 2패널 검토, 액션 footer, keyboard, 패널 스크롤 확인",
    "큰 태블릿 가로: 3패널 표시 가능성과 overflow 확인",
    "모바일 및 태블릿 세로: 1패널, drawer/sheet, modal/focus 확인",
    "저장 중 반복 클릭, 느린 네트워크, 새로고침 후 persistence 확인",
    "권한 없음 계정에서 버튼/API 차단 확인",
  ],
  expectedChangeAreas: [
    "components/workorder/*",
    "features/workorders/*",
    "features/materials 또는 material-orders 관련 shell",
    "components/workspace/layout/*",
    "responsive layout policy/hooks",
    "save feedback hooks/toast presenter",
    "tests/*workspace* 또는 신규 0.24.12 contract",
  ],
  recommendedCommitMessage: "feat: commonize workspace worker shell and save flow",
  nextVersionBoundary: [
    "0.24.13은 기능 개발을 바로 이어가지 않고 문서/폴더 정리 2차를 다룬다.",
    "0.24.18은 R2/Simulator 테스트 기반을 다루고, 0.24.19는 workorder/material-order PDF, Worker/R2 저장, 임시/최종 PDF 정책을 다룬다.",
    "0.24.19로 supplier/material-order PDF의 금액 표시, 파일명, 재생성, R2 저장 정책과 PDF 화면/PDF 파일 비교를 넘긴다.",
    "0.24.12에서 해결하지 못한 modal/focus 전체 재설계는 별도 정책 결정 후 후속 버전으로 넘긴다.",
  ],
  completionConditions: [
    "구현 완료",
    "실제 verify-safe PASS",
    "commit hash 존재",
    "git push origin master 완료",
    "ahead 0 / behind 0",
    "working tree clean",
    "UI/반응형 사용자 확인이 필요한 항목은 사용자 확인 완료",
  ],
  result: {
    completedSummary: [
      "/worker를 workspace fixed shell 경계에 맞춰 작업지시서 workspace와 같은 density/스크롤 기준을 사용하게 했다.",
      "작업지시서와 발주서의 기존 공통 responsive frame, layout mode, 저장 lock/toast 기준을 0.24.12 계약 테스트로 고정했다.",
      "Codex Optimization Phase 1로 current-state를 짧은 작업 시작 매니페스트로 정리하고 작업 유형별 읽을 파일, 기본 검색 제외, verify profile 선택 기준을 추가했다.",
    ],
    commitHash: "",
    verificationResult: "workspace-commonization 실행 대상",
    remainingIssues: [
      "UI/반응형 수동 확인 전에는 완료로 전환할 수 없다.",
      "PDF/R2 저장 정책과 supplier/material-order PDF는 재배치 후 0.24.18~0.24.19에서 다룬다.",
    ],
    userConfirmationRequired: true,
    userConfirmationResult: "미확인",
  },
};
