import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_3: RoadmapVersionDetail = {
  version: "0.24.21.3",
  title: "공개 홈페이지·도메인·상업 Onboarding 계약",
  status: "verification_pending",
  userSummary: ["WAFL 공개 홈페이지의 사이트맵, 도메인 경계, 기능·요금제·보안 설명, 가입 CTA와 제품 캡처 기준을 Codex 구현 입력으로 확정한다."],
  visibleChanges: ["사용자 UI나 배포를 변경하지 않고 공개 marketing website와 app/system-admin 경계의 canonical 문서를 추가한다."],
  expectedUi: ["후속 구현에서 Home, Features, Pricing, Guide, Security, Terms, Signup, Login이 같은 정보구조와 CTA 계약을 사용한다."],
  developmentPurpose: ["실제 고객 홍보와 가입 요청을 받기 전에 공개 정보, 가격, 정책, 인증, 배포 경계를 고정한다."],
  developmentUiStructure: ["public marketing, customer app, system admin, legal documents, signup request, commercial analytics를 분리한다."],
  scope: ["사이트맵", "도메인 분리안", "페이지별 역할", "가격·Trial 표현", "캡처 요구 목록", "SEO", "analytics 최소수집", "Codex Public Website Sprint"],
  outOfScope: ["public UI 구현", "도메인 구매/DNS", "signup API/UI", "PG/결제", "analytics SDK", "production 배포", "DB/R2 mutation"],
  implementationPrinciples: ["공개 정보는 canonical 정책과 일치한다.", "미구현 기능을 구현 완료처럼 표현하지 않는다.", "system-admin과 고객 데이터는 공개 surface에서 분리한다.", "demo fixture만 캡처한다."],
  successConditions: ["public sitemap 존재", "domain/auth boundary 존재", "pricing/Trial 표시 계약 존재", "screenshot 목록 존재", "SEO/security/public-data 금지 기준 존재", "Codex Sprint 범위 존재"],
  failureConditions: ["실제 고객 데이터 공개", "system-admin route 노출", "미확정 가격 임의 표시", "인증 guard 약화", "production 배포 또는 DNS 변경"],
  cautions: ["법률·가격 문구는 공개 전 최종 검토가 필요하다.", "공개 screenshot은 UI 수정 완료 후 demo fixture로 다시 생성한다."],
  stopConditions: ["도메인 구매 필요", "PG 계약 필요", "production 고객 데이터 접근 필요", "인증 구조 변경 필요"],
  permissionImpact: "none",
  permissionNotes: ["문서/roadmap 변경이며 public/app/system-admin permission code를 변경하지 않는다."],
  dbImpact: "none",
  dbImpactNotes: ["가입·문의 데이터 schema나 write를 구현하지 않는다."],
  r2Impact: "none",
  r2ImpactNotes: ["공개 asset이나 screenshot의 R2 배포를 변경하지 않는다."],
  migrationRequired: false,
  migrationNotes: "이번 문서 패치는 DB Migration 없음.",
  automaticTests: ["TypeScript/build", "roadmap-development-contract", "문서 경로/version 계약", "Flat ZIP 무결성"],
  manualTests: ["docs index의 21번 문서 링크", "/roadmap 현재 0.24.21.3/다음 0.24.21.4 표시", "요금제·Trial 값 기존 정책 일치", "공개 금지 정보 목록 검토"],
  expectedChangeAreas: ["docs/project/21-public-website-commercial-onboarding-spec.md", "docs/codex-current-state.md", "lib/constants/version.ts", "lib/internal/roadmap/*", "pending-tests.md"],
  recommendedCommitMessage: "docs: define public website and commercial onboarding contract",
  nextVersionBoundary: ["0.24.21.4에서 저장소 원통형 UI, 파일 설정 중복 표시, workorder URL 식별자 등 UI·routing remediation 계약을 정리한다."],
  completionConditions: ["문서 작성", "roadmap/version 동기화", "required checks PASS", "commit/push 완료"],
  result: {
    completedSummary: ["공개 홈페이지 사이트맵, 도메인·인증 경계, 요금제·Trial 표시, 제품 캡처, SEO·analytics·공개 금지 기준을 작성했다."],
    commitHash: "",
    verificationResult: "수동 패치 생성 완료; 적용 후 roadmap-development-contract와 build 확인 필요",
    remainingIssues: ["실제 public UI 구현", "도메인 구매/DNS", "가입 API/UI", "가격·브랜드·배포 방식 사용자 결정"],
    userConfirmationRequired: true,
    userConfirmationResult: "최종 브랜드/도메인, 공개 가격, 문의 채널, CTA 문구, 배포 분리 방식은 추후 결정 가능",
  },
};
