import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_2: RoadmapVersionDetail = {
  version: "0.24.21.2",
  title: "고객사 가입·동의·승인·Trial Provisioning 계약",
  status: "verification_pending",
  userSummary: ["공개 홈페이지 가입 요청부터 정책 동의, 시스템 관리자 승인, Trial과 회사 초기 데이터 생성까지의 제품 계약을 확정한다."],
  visibleChanges: ["사용자 UI나 DB를 변경하지 않고 후속 Codex 구현용 가입·승인·provisioning canonical 문서를 추가한다."],
  expectedUi: ["후속 구현에서 공개 가입 요청 폼과 시스템 관리자 요청 Queue가 같은 상태·동의·승인 계약을 사용한다."],
  developmentPurpose: ["공개 서비스 오픈 전에 가입 요청, 정책 동의 증적, 승인과 Trial 생성의 경계를 고정한다."],
  developmentUiStructure: ["public request", "consent evidence", "system-admin review queue", "idempotent provisioning", "Trial/payment follow-up을 분리한다."],
  scope: ["가입 입력 필드", "중복 검증", "정책 동의 증적", "요청 상태", "관리자 Queue", "Trial provisioning 순서", "실패 복구", "Codex Sprint 분리"],
  outOfScope: ["공개 홈페이지 구현", "DB schema/migration", "결제/PG", "production mutation", "가입 API/UI 구현"],
  implementationPrinciples: ["문서 version별 동의를 저장한다.", "승인 provisioning은 idempotent해야 한다.", "부분 성공 회사를 활성화하지 않는다.", "미확정 상업·법무 정책을 임의 구현하지 않는다."],
  successConditions: ["가입 상태 전이 존재", "필수/선택 동의 분리", "동의 evidence 계약 존재", "승인 provisioning 순서 존재", "실패 복구와 감사 기준 존재"],
  failureConditions: ["포괄 체크박스만 저장", "중복 회사/Trial 생성", "부분 성공 활성화", "결제 정책 임의 확정", "production 실행"],
  cautions: ["법적 필수 동의 문구는 공개 전 전문가 검토가 필요하다.", "기존 승인·billing·policy 구조를 대체하지 않고 연결한다."],
  stopConditions: ["실제 PG 계약 필요", "destructive migration 필요", "production 개인정보 접근 필요"],
  permissionImpact: "none",
  permissionNotes: ["문서/roadmap 변경이며 권한 코드를 변경하지 않는다."],
  dbImpact: "none",
  dbImpactNotes: ["후속 구현 계약만 문서화하며 DB write/migration을 실행하지 않는다."],
  r2Impact: "none",
  r2ImpactNotes: ["사업자등록증 저장 계약은 후속 구현 대상이며 이번 패치에서 R2를 변경하지 않는다."],
  migrationRequired: false,
  migrationNotes: "이번 문서 패치는 DB Migration 없음. 후속 Codex가 schema gap 조사 후 별도 migration 계획을 제시한다.",
  automaticTests: ["TypeScript/build", "roadmap-development-contract", "문서 경로/version 계약", "Flat ZIP 무결성"],
  manualTests: ["docs index의 20번 문서 링크", "/roadmap 현재 0.24.21.2/다음 0.24.21.3 표시", "기존 정책과 Trial 값 일치 확인"],
  expectedChangeAreas: ["docs/project/20-customer-signup-consent-approval-trial-spec.md", "docs/codex-current-state.md", "lib/constants/version.ts", "lib/internal/roadmap/*", "pending-tests.md"],
  recommendedCommitMessage: "docs: define customer signup and trial provisioning contract",
  nextVersionBoundary: ["0.24.21.3에서 공개 홈페이지·요금제·도메인·상업 onboarding 정보구조를 정리한다."],
  completionConditions: ["문서 작성", "roadmap/version 동기화", "required checks PASS", "commit/push 완료"],
  result: {
    completedSummary: ["기존 정책·승인·Trial 기준을 조사해 공개 가입 요청부터 초기 회사 provisioning까지 연결 계약을 작성했다."],
    commitHash: "",
    verificationResult: "수동 패치 생성 완료; 적용 후 roadmap-development-contract와 build 확인 필요",
    remainingIssues: ["실제 schema/API/UI 구현", "PG/결제", "사용자 결정 대기 정책", "법률 검토"],
    userConfirmationRequired: true,
    userConfirmationResult: "사업자등록증 필수, 인증 수준, 카드 없는 Trial, 보존기간, 복수 회사 정책은 추후 결정 가능",
  },
};
