import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_34: RoadmapVersionDetail = {
  version: "0.24.34",
  title: "Workorder Size Specification and Incomplete/Final PDF",
  status: "planned",
  userSummary: [
    "Connects the existing system size-set/POM foundations to real workorder editing, storage, copy/reproduction, and PDF output.",
    "Adds separate incomplete and final workorder PDF products while preserving the existing supplier order-request PDF and private R2 lifecycle.",
  ],
  visibleChanges: [
    "Workorders can select a size set and edit POM rows by size in cm or inch, including supported 1/8-inch values.",
    "Users can generate an incomplete workorder PDF with an explicit watermark, status badge, and missing-item list.",
    "Users can generate a final workorder PDF only when the canonical completion rules are satisfied, with size/POM pages included.",
  ],
  expectedUi: [
    "Desktop uses a bounded editable size table with shared WAFL section, table, empty, loading, error, and action components.",
    "Tablet and mobile use responsive cards or horizontally scrollable size grids without losing save, validation, or PDF actions.",
    "Incomplete/final/supplier PDF actions are clearly separated and never presented as the same document type.",
  ],
  developmentPurpose: [
    "Close the largest remaining gap in the core workorder authoring and customer-deliverable workflow.",
    "Convert 0.24.27 size/POM and 0.24.28 PDF/R2 foundations into complete product paths instead of repeating foundation-only work.",
  ],
  developmentUiStructure: [
    "Reuse the existing workorder editor and shared WAFL form/table primitives.",
    "Use system/company size-set and POM activation data as defaults, then store an immutable workorder snapshot suitable for copy/reproduction and PDF generation.",
    "Reuse the generated-document repository and private R2 lifecycle with distinct document types for incomplete, final, and supplier PDFs.",
  ],
  scope: [
    "Canonical roadmap/current-state/audit synchronization for the 0.24.34 execution boundary.",
    "Workorder size-set selection and POM rows derived from active company/system defaults.",
    "Size-by-POM value editing, validation, cm/inch unit handling, and deterministic 1/8-inch representation.",
    "Company default measurement templates and workorder overrides where supported by current policy.",
    "Copy/reproduction preservation of the workorder size/POM snapshot.",
    "Incomplete workorder PDF with watermark, status badge, missing-item list, and current saved snapshot.",
    "Final workorder PDF with canonical generation eligibility, latest-only retention, size/POM pages, and failure-safe replacement.",
    "Explicit separation from supplier order-request PDF.",
    "Contracts, additive dev/test migration if required, PDF/R2 integration, visual PDF verification, responsive browser tests, commit/push, and final handoff.",
  ],
  outOfScope: [
    "Actual PG provider, merchant credentials, production charge/refund/webhook, or actual email delivery.",
    "Company-wide Export execution, termination/deletion scheduler execution, or launch monitoring/CI work reserved for later versions.",
    "Production DB/R2 mutation, production PDF generation, broad R2 prefix deletion, or Worker deployment without separate approval.",
    "Changing settled catalog, size, POM, PDF retention, billing, or deletion policy.",
  ],
  implementationPrinciples: [
    "Read final owner policy, the integrated master plan, and the 0.24.33.1 unimplemented-feature audit before implementation; do not re-ask confirmed policy.",
    "Treat 0.24.27 and 0.24.28 as completed foundations, not proof that workorder size editing or incomplete/final PDF product paths already exist.",
    "Store money and measurement values deterministically; do not use floating-point values for canonical 1/8-inch persistence.",
    "Keep document types, storage keys, authorization, quota accounting, replacement, trash, restore, purge, and reconciliation explicit and exact-key scoped.",
    "If regeneration fails, keep the previous normal PDF available and record safe retry/operator evidence.",
  ],
  successConditions: [
    "Workorder size/POM editing persists and reloads across desktop, tablet, and mobile paths.",
    "Copy/reproduction preserves the intended size/POM snapshot without cross-company leakage.",
    "Incomplete PDF clearly shows watermark, status, and missing items; final PDF obeys completion rules and includes size/POM pages.",
    "Incomplete/final/supplier PDFs are separate generated-document types with latest-only and failure-safe behavior verified.",
    "Required contracts, targeted ESLint, tsc --noEmit, next build, mutation audit, PDF/R2 integration, visual PDF checks, and residual audits pass.",
  ],
  failureConditions: [
    "The feature requires destructive schema change, production data mutation, or an unapproved Worker deployment.",
    "Canonical size/POM or PDF policy conflicts cannot be resolved from final owner documents.",
    "PDF replacement can delete the previous normal file before the new file is durably committed.",
    "Residual dev/test DB or R2 fixtures remain after integration.",
  ],
  cautions: [
    "This is a broad core-product version. Keep implementation bounded to size/POM editing and incomplete/final workorder PDF delivery.",
    "Visual PDF output requires direct rendered-page inspection; build/contracts alone are not sufficient.",
    "Do not silently reinterpret body circumference defaults as finished-garment flat measurements; preserve the canonical distinction.",
  ],
  stopConditions: [
    "Production DB/R2/Worker access is detected.",
    "A destructive migration, actual customer backfill, or broad delete is required.",
    "Worker source change or deployment is required before the existing app-side integration can be verified.",
    "A second bounded PDF/R2 or browser integration run fails after an in-scope fix.",
  ],
  permissionImpact: "guarded",
  permissionNotes: [
    "Workorder view/edit and PDF actions remain company-scoped and permission-checked on the server.",
    "System-admin does not gain customer-content access beyond existing explicit approval/support boundaries.",
  ],
  dbImpact: "guarded",
  dbImpactNotes: [
    "An additive migration may be required for workorder size/POM snapshots, values, unit settings, and generated-document type metadata.",
    "No destructive migration or automatic existing-company backfill is allowed.",
  ],
  r2Impact: "guarded",
  r2ImpactNotes: [
    "Dev/test PDF fixtures may create exact-key R2 objects and must clean residual objects to 0.",
    "Reuse R2 Upload Worker 0.13.71 and PDF Generator Worker 0.16.1.1 unless source evidence proves a separately approved change is required.",
  ],
  migrationRequired: true,
  migrationNotes: "Likely additive dev/test migration for workorder size/POM snapshots and distinct incomplete/final generated-document types; inspect existing schema before creating it.",
  automaticTests: [
    "canonical roadmap reconciliation contract",
    "workorder size/POM schema and repository contracts",
    "measurement unit and 1/8-inch contract",
    "workorder copy/reproduction size snapshot contract",
    "incomplete/final/supplier PDF type contract",
    "PDF eligibility, latest-only, failure-safe replacement, and quota contracts",
    "PDF/R2 integration with residual DB/R2 0",
    "responsive Playwright workorder-size and PDF-action scenarios",
    "targeted ESLint",
    "tsc --noEmit",
    "next build",
    "mutation audit",
    "git diff checks",
  ],
  manualTests: [
    "Rendered incomplete/final PDF visual inspection for Korean text, watermark, pagination, size table, images, and POM guidance.",
    "PC, iPad, iPhone, Galaxy, and Galaxy Tab size-table editing and PDF download/share QA.",
    "KakaoTalk file-forwarding behavior on actual mobile devices.",
  ],
  expectedChangeAreas: [
    "db/migrations/*0_24_34*",
    "lib/workorder/*",
    "features/workorder/*",
    "components/workorders/*",
    "lib/catalog/*",
    "lib/generated-documents/*",
    "app/api/workorders/*",
    "workers/pdf-generator/* if separately approved",
    "tests/*size*",
    "tests/*pdf*",
    "tools/pipeline/*",
    "docs/*",
  ],
  futureDependencies: [
    "0.24.35 Company-wide Export Execution consumes current PDFs and attachments.",
    "0.24.36 Termination/Recovery/Automatic Deletion consumes final Export and exact document manifests.",
    "Actual PG/email/production launch work remains deferred or separately approved.",
  ],
  recommendedCommitMessage: "0.24.34 작업지시서 치수표와 미완성·최종 PDF 완성",
  nextVersionBoundary: [
    "0.24.35 - Company-wide Export Execution.",
    "Do not start Export until size/POM and incomplete/final PDF persistence and lifecycle are verified.",
  ],
  completionConditions: [
    "APP_VERSION 0.24.34 and roadmap/current-state are synchronized.",
    "Workorder size/POM persistence, copy/reproduction, and responsive editing are complete.",
    "Incomplete/final/supplier document types and canonical generation rules are complete.",
    "PDF/R2 integration and visual checks pass with residual DB/R2 0.",
    "Commit/push complete and 4. Newest contains exactly the latest ZIP and matching repo-state.",
  ],
  result: {
    completedSummary: [],
    commitHash: "",
    verificationResult: "NOT_STARTED",
    remainingIssues: [
      "Implementation has not started.",
      "Manual rendered-PDF and real-device download/share QA will be required before final completion.",
    ],
    userConfirmationRequired: false,
    userConfirmationResult: "NOT_STARTED",
  },
};
