import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_14: RoadmapVersionDetail = {
  version: "0.24.21.14",
  title: "DB Read-only Audit Result Classification Fix",
  status: "verification_pending",
  userSummary: ["DB 감사 메뉴 31·32가 정상 결과를 실패로 판정하던 모드별 종료 코드 로직을 수정했다."],
  visibleChanges: ["PowerShell 메뉴 30~32의 성공·실패 파일명이 실제 검사 의미와 일치한다."],
  expectedUi: ["/roadmap에 0.24.21.14 판정 수정 항목 표시"],
  developmentPurpose: ["constraint 결과의 issue_count 합계와 index 보고서 조회 성공을 각각 올바르게 판정한다."],
  developmentUiStructure: ["감사 실행기와 roadmap 메타데이터만 수정"],
  scope: ["mode-specific audit exit code", "constraint issue aggregation", "index report success classification", "version bump"],
  outOfScope: ["DB 변경", "migration", "인덱스 추가·삭제", "R2 변경"],
  implementationPrinciples: ["reconciliation은 결과 행 수로 판정한다.", "constraints는 issue_count 합계로 판정한다.", "indexes는 조회 성공 자체를 성공으로 판정한다."],
  successConditions: ["메뉴 30 정상 DB에서 OK", "메뉴 31 issue_count 전부 0이면 OK", "메뉴 32 보고서 행 존재 시에도 OK"],
  failureConditions: ["constraint 요약 행 수만으로 실패", "index 보고서 행 수만으로 실패", "DB mutation"],
  cautions: ["SSL mode 경고는 이번 실패 원인이 아니며 운영 연결 문자열 정비 TODO로 유지한다."],
  stopConditions: ["실제 issue_count가 1 이상이면 제약조건 적용을 중단한다."],
  permissionImpact: "none",
  permissionNotes: ["기존 dev/test DB guard와 fingerprint 검증 유지"],
  dbImpact: "read_only",
  dbImpactNotes: ["SELECT/READ ONLY 감사 판정만 수정", "DB 데이터 변경 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근·변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["db-readonly-audit-menu-contract", "mode-specific result-classification static contract"],
  manualTests: ["PowerShell 메뉴 30·31·32 재실행", "npm run build", "/roadmap 버전 확인"],
  expectedChangeAreas: ["scripts/run-readonly-db-audit.mjs", "tests/db-readonly-audit-menu-contract.mjs", "lib/internal/roadmap/*", "lib/constants/version.ts"],
  recommendedCommitMessage: "fix: classify DB audit results by mode",
  nextVersionBoundary: ["30~32 메뉴와 build 통과 후 0.24.22 Codex Sprint A 시작"],
  completionConditions: ["메뉴 30~32 모두 의미에 맞게 OK/Failed 판정", "사용자 로컬 build 통과", "commit/push 완료"],
  result: {
    completedSummary: ["정상 constraint 요약과 index 통계 보고서를 실패로 오판하던 종료 코드 로직을 분리했다."],
    commitHash: "",
    verificationResult: "정적 계약 검사 완료; 사용자 로컬 메뉴·build 재확인 필요",
    remainingIssues: ["SSL connection string warning follow-up", "사용자 로컬 30~32 재실행"],
    userConfirmationRequired: true,
    userConfirmationResult: "정상 DB 결과가 Failed 파일로 저장된 로그를 기준으로 수정 요청됨",
  },
};
