import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_21_15: RoadmapVersionDetail = {
  version: "0.24.21.15",
  title: "Pre-Codex Final Policy Reconciliation",
  status: "verification_pending",
  userSummary: [
    "가입·결제·Export·PDF·자동삭제·사업자등록증·분류 정책을 최종 확정하고 충돌 문서를 정리했다.",
    "Codex Sprint A 전에 사용할 canonical 정책과 후속 Master TODO를 최신화했다.",
  ],
  visibleChanges: ["/roadmap에 0.24.21.15 정책 정합성 정리 결과 표시"],
  expectedUi: ["고객 업무 UI 변경 없음", "문서와 roadmap 기준만 최신화"],
  developmentPurpose: ["Codex가 과거 provisional 문장을 따라 잘못 구현하지 않도록 제품 정책 source of truth를 고정한다."],
  developmentUiStructure: ["canonical policy docs", "conflict reconciliation register", "read-only roadmap metadata"],
  scope: ["policy reconciliation", "docs conflict cleanup", "master TODO refresh", "version sync"],
  outOfScope: ["runtime feature implementation", "DB migration", "DB/R2/PG mutation", "Codex Sprint A UI changes"],
  implementationPrinciples: ["확정 정책은 직접 문서에 반영한다.", "과거 충돌은 precedence 문구만 남기지 않고 핵심 문장을 수정한다.", "보류 항목은 DEFERRED로 명시한다."],
  successConditions: ["09·19·20·21·23·26 문서가 최신 정책과 일치", "30번 reconciliation 문서 존재", "APP_VERSION/roadmap/docs index 일치"],
  failureConditions: ["카드 optional 문구 잔존", "PDF superseded 보존 문구 잔존", "속옷·액세서리 미결정 표기 잔존", "자동 삭제 기본 OFF 표기 잔존"],
  cautions: ["법률·세무·PG·국외이전 문구는 production launch 전 최신 검토가 필요하다."],
  stopConditions: ["runtime 구현 또는 schema 변경이 필요하면 별도 버전으로 분리"],
  permissionImpact: "none",
  permissionNotes: ["권한 구현 변경 없음"],
  dbImpact: "none",
  dbImpactNotes: ["DB 접근·변경 없음"],
  r2Impact: "none",
  r2ImpactNotes: ["R2 접근·변경 없음"],
  migrationRequired: false,
  migrationNotes: "DB Migration 없음",
  automaticTests: ["document policy conflict scan", "roadmap type contract", "unicode encoding contract"],
  manualTests: ["docs/project/26 및 30 검토", "/roadmap 현재 0.24.21.15·다음 0.24.22 확인", "npm run build"],
  expectedChangeAreas: ["docs/project/09,19,20,21,23,26,30", "docs/README.md", "docs/codex-current-state.md", "docs/productization-roadmap.md", "lib/internal/roadmap/*", "lib/constants/version.ts"],
  recommendedCommitMessage: "docs: reconcile final pre-Codex product policies",
  nextVersionBoundary: ["검증과 push 완료 후 0.24.22 Codex Sprint A 시작"],
  completionConditions: ["문서 충돌 정리", "build/contract PASS", "commit/push 완료"],
  result: {
    completedSummary: ["최종 정책 반영과 핵심 충돌 문서 정리를 완료했다."],
    commitHash: "",
    verificationResult: "정적 문서 정합성 검사 완료; 사용자 로컬 build/contract 확인 필요",
    remainingIssues: ["PG/analytics/cookie/Instagram/legal provider details are deferred"],
    userConfirmationRequired: true,
    userConfirmationResult: "사용자가 확정한 정책을 기준으로 문서 최신화 요청",
  },
};
