import type { RoadmapVersionDetail } from "./types";

export const ROADMAP_0_24_30: RoadmapVersionDetail = {
  version: "0.24.30",
  title: "Storage Capacity Profiles",
  status: "completed",
  userSummary: [
    "Connects Trial 100MB and paid plan storage limits to the company subscription snapshot used by workspace storage screens and upload preflight checks.",
    "Adds quota states and 0%-110% profile evidence so QA can distinguish actual usage from visually clamped meter display.",
  ],
  visibleChanges: [
    "Workspace storage cards use subscription-backed usage totals instead of only company file policy values.",
    "Workorder attachment upload, attachment completion, and generated PDF creation are blocked before storage when projected usage exceeds the company quota.",
    "Existing text reads and delete/trash/purge paths remain available when storage is full; this version does not add automatic deletion.",
  ],
  expectedUi: [
    "Trial companies show 100MB storage and 3 member policy through the existing subscription surfaces.",
    "Usage meters display a clamped bar up to 100% while keeping actual over-limit percent available in API data.",
    "Upload attempts over quota receive a safe storage quota message instead of exposing DB, R2, Worker, or signed URL details.",
  ],
  developmentPurpose: [
    "Align plan constants, full-reset seed data, company usage aggregation, and upload guards with the final storage policy.",
    "Prepare deterministic storage capacity scenarios before the 0.24.31 PG billing sprint.",
  ],
  developmentUiStructure: [
    "Reuse the existing workspace file summary, admin dashboard summary, and shared WAFL storage meter.",
    "Keep the customer dashboard and /workers screen outside this storage checkpoint.",
  ],
  scope: [
    "APP_VERSION 0.24.30 and roadmap/current-state synchronization.",
    "Trial, Lite, Flow, Studio, and Custom storage/member limits from final policy.",
    "Company usage aggregation across active workorder attachments, recoverable trash, company files, onboarding files, and approved signup certificates without double-counting promoted certificate files.",
    "Quota preflight for workorder attachment upload request, upload completion, and generated PDF storage.",
    "Actual usage percent, display-clamped percent, remaining bytes, reserved bytes, and capacity state contract.",
    "Storage capacity scenarios for 0%, <1%, 10%, 20%, 30%, 40%, 50%, 60%, 70%, 80%, 90%, 100%, and 110%.",
    "Mutation audit and static contract coverage; no production mutation.",
  ],
  outOfScope: [
    "PG billing and subscription operations.",
    "Payment method or raw card handling.",
    "Notification email sending.",
    "Kakao external API sending.",
    "Automatic deletion, grace-period lifecycle execution, or termination jobs.",
    "Customer dashboard redesign or /workers density redesign.",
    "Worker source change or Worker redeployment.",
    "0.24.31 or later feature implementation.",
  ],
  implementationPrinciples: [
    "Block quota-increasing writes before R2 upload or DB metadata commit whenever the projected total exceeds the company limit.",
    "Keep reads, existing text edits, delete/trash/restore/purge cleanup paths, and other non-growth operations outside quota blocking.",
    "Use company subscription limits first; use fallback defaults only when a subscription row is unavailable.",
    "Do not change existing company data or run broad backfills in this checkpoint.",
  ],
  successConditions: [
    "Trial 7 days/100MB/3 members remains the signup provisioning default.",
    "Plan policy, full-reset seed data, subscription snapshot, storage summary, upload preflight, and PDF generation guards agree on capacity limits.",
    "Storage usage inclusion/exclusion and no-double-count rules are covered by contracts.",
    "ESLint, typecheck, build, mutation audit, git diff checks, commit, push, and 4. Newest handoff complete.",
  ],
  failureConditions: [
    "A destructive DB migration or existing company auto-backfill is required.",
    "Production DB/R2/Worker mutation is required or detected.",
    "Residual dev/test fixture DB/R2 state is nonzero after an executed integration.",
    "Storage enforcement requires PG billing implementation from 0.24.31.",
  ],
  cautions: [
    "This version enforces storage quota on app upload paths, not billing collection.",
    "Actual R2 lifecycle and PDF Worker behavior are inherited from 0.24.28 unless source changes prove a minimal regression is needed.",
  ],
  stopConditions: [
    "Migration is required for non-additive schema behavior.",
    "Worker source or deployment must change.",
    "A production mutation path remains after mutation audit.",
  ],
  permissionImpact: "guarded",
  permissionNotes: [
    "Workspace quota guards continue to use effective company session and tenant-scoped workorder checks.",
    "System-admin actual/effective boundary remains unchanged.",
  ],
  dbImpact: "guarded",
  dbImpactNotes: [
    "No DB migration is required.",
    "Full-reset seed source is updated, but no DB reset or migration is executed by the version implementation.",
    "Dev/test fixture mutation is allowed only through existing guarded rollback/cleanup runners if executed.",
  ],
  r2Impact: "guarded",
  r2ImpactNotes: [
    "No Worker source change or deployment is required.",
    "Quota checks run before new R2 upload for workorder attachments and generated PDFs.",
  ],
  migrationRequired: false,
  migrationNotes: "No schema migration is required for the storage capacity checkpoint.",
  automaticTests: [
    "storage capacity profile contract",
    "storage usage inclusion contract",
    "storage quota upload guard contract",
    "storage usage meter contract",
    "trial policy contract",
    "roadmap 0.24.30 contract",
    "roadmap development contract",
    "mutation audit",
    "targeted ESLint",
    "tsc --noEmit",
    "next build",
    "git diff --check",
  ],
  manualTests: [
    "Vercel QA with Trial company near 0%, 80%, 100%, and over-limit storage.",
    "Upload attachment and generated PDF over-quota negative checks.",
    "Delete/trash/purge cleanup recovery from full storage.",
  ],
  expectedChangeAreas: [
    "lib/billing/*",
    "app/api/workorders/attachments/upload/*",
    "app/api/workorders/[workOrderId]/generated/order-request-pdf/route.ts",
    "app/api/admin/files/snapshot/route.ts",
    "lib/admin/dashboard/adminPlanStorageSummary.ts",
    "db/schema/full_reset.sql",
    "lib/internal/roadmap/*",
    "docs/codex-current-state.md",
    "docs/productization-roadmap.md",
    "tests/*storage*",
  ],
  futureDependencies: ["0.24.31 PG Billing and Subscription Operations uses these plan capacities without introducing raw card storage."],
  recommendedCommitMessage: "0.24.30 저장공간 용량 프로필과 업로드 쿼터 가드 완료",
  nextVersionBoundary: ["0.24.31 - PG Billing and Subscription Operations."],
  completionConditions: [
    "APP_VERSION 0.24.30",
    "Storage capacity contracts and required regression checks pass.",
    "Mutation audit high-risk 0 is recorded.",
    "Commit/push complete and 4. Newest contains exactly the latest source ZIP and matching repo-state.",
  ],
  result: {
    completedSummary: [
      "Plan and Trial capacity constants were aligned to 100MB/500MB/1.5GB/5GB policy.",
      "Subscription-backed storage usage now includes active attachments, recoverable trash, company files, onboarding files, and approved signup certificates.",
      "Workorder attachment and generated PDF growth paths now use server-side quota preflight before storage writes.",
    ],
    commitHash: "recorded in final report after commit",
    verificationResult: "PASS: storage capacity contracts, related authorization/PDF/R2 contracts, targeted ESLint, tsc --noEmit, mutation audit high-risk 0, next build, and git diff --check.",
    remainingIssues: ["Manual storage edge-case QA remains pending user validation."],
    userConfirmationRequired: true,
    userConfirmationResult: "PENDING_USER_QA",
  },
};
