import { formatRecentKstDateTime } from "@/lib/workorder/presentation/dateTimePresentation";
import { buildAttachmentPanelSections } from "@/lib/workorder/presentation/workOrderWorkspacePresentation";
import type { DetailProps, DetailViewModelArgs, SidePanelProps, SidePanelViewModelArgs } from "@/lib/workorder/workspace/viewModelTypes";

export function buildDetailProps({
  selectedWorkOrder,
  hasVisibleWorkOrders,
  currentWorkflowState,
  saveStatus,
  lastSavedAt,
  currentUser,
  currentRole,
  canChangeManager,
  canSeeProductionSections,
  canSeeCostSections,
  canOpenInventoryEditor,
  currentDisplayStage,
  currentInventoryQuantity,
  fabricTotal,
  subsidiaryTotal,
  outsourcingTotal,
  totalCost,
  unitCost,
  basicInfoOpen,
  materialOpen,
  outsourcingOpen,
  canRenameTitle,
  isReviewRequestLocked,
  visibleStages,
  availableActions,
  workflowProcessingLabel,
  isWorkspaceWriteLocked,
  workspaceWriteLockMessage,
  onSave,
  onWorkflowAction,
  onUpdateSelectedWorkOrder,
  onRenameWorkOrderTitle,
  onCompleteInspection,
  onOpenManagerAssignModal,
  onSetBasicInfoOpen,
  onSetMaterialOpen,
  onSetOutsourcingOpen,
  onSetInventoryEditorOpen,
}: DetailViewModelArgs): DetailProps {
  return {
    workOrder: selectedWorkOrder,
    isEmpty: !hasVisibleWorkOrders,
    currentWorkflowState,
    saveStatus,
    lastSavedAt: formatRecentKstDateTime(lastSavedAt),
    currentInventoryQuantity,
    currentUserName: currentUser.name,
    currentUserRole: currentRole,
    canRenameTitle,
    canEditInventory: canOpenInventoryEditor,
    canChangeManager,
    onOpenManagerAssignModal,
    canSeeProductionSections,
    canSeeCostSections,
    fabricTotal,
    subsidiaryTotal,
    outsourcingTotal,
    totalCost,
    unitCost,
    basicInfoOpen,
    materialOpen,
    outsourcingOpen,
    onSave,
    onOpenInventoryEditor: () => onSetInventoryEditorOpen(true),
    isReviewRequestLocked,
    onToggleBasicInfo: () => onSetBasicInfoOpen((prev) => !prev),
    onToggleMaterial: () => onSetMaterialOpen((prev) => !prev),
    onToggleOutsourcing: () => onSetOutsourcingOpen((prev) => !prev),
    onSetMaterialOpen,
    onSetOutsourcingOpen,
    visibleStages,
    currentDisplayStage,
    actions: availableActions,
    workflowProcessingLabel,
    isWorkspaceWriteLocked,
    workspaceWriteLockMessage,
    onAction: onWorkflowAction,
    onUpdateWorkOrder: onUpdateSelectedWorkOrder,
    onRenameWorkOrderTitle,
    onCompleteInspection,
  };
}

export function buildSidePanelProps({
  hasVisibleWorkOrders,
  canSeeAttachments,
  canUploadOfficialAttachments,
  canEditMemo,
  designAttachments,
  officialAttachments,
  currentRole,
  selectedWorkOrder,
  currentUser,
  i18n,
  isWorkspaceWriteLocked,
  workspaceWriteLockMessage,
  getAttachmentPermissions,
  onOpenAttachmentPicker,
  onUploadAttachmentFiles,
  onRequestDeleteAttachment,
  onSetPrimaryDesignAttachment,
  onCreateMemoThread,
  onCreateMemoReply,
  onUpdateMemoThread,
  onDeleteMemoThread,
  onUpdateMemoReply,
  onDeleteMemoReply,
}: SidePanelViewModelArgs): SidePanelProps {
  return {
    isEmpty: !hasVisibleWorkOrders,
    canSeeAttachments,
    canManageAttachments: canUploadOfficialAttachments,
    canEditMemo,
    writeLocked: Boolean(isWorkspaceWriteLocked),
    writeLockMessage: workspaceWriteLockMessage,
    attachmentSections: buildAttachmentPanelSections({
      designTitle: i18n.workorder.ui.attachmentPanel.designTitle,
      designEmptyText: i18n.workorder.ui.attachmentPanel.designEmpty,
      designAddButtonLabel: i18n.workorder.ui.attachmentPanel.designAddButton,
      officialTitle: i18n.workorder.ui.attachmentPanel.title,
      officialEmptyText: i18n.workorder.ui.attachmentPanel.empty,
      officialAddButtonLabel: i18n.workorder.ui.attachmentPanel.addButton,
      designAttachments,
      officialAttachments,
      getAttachmentPermissions,
    }),
    onOpenAttachmentPicker,
    onUploadAttachmentFiles,
    onPreviewAttachment: () => undefined,
    onDeleteAttachment: onRequestDeleteAttachment,
    onSetPrimaryDesignAttachment,
    currentRole,
    workOrder: selectedWorkOrder,
    currentUserName: currentUser.name,
    currentUserId: currentUser.id,
    onCreateMemoThread,
    onCreateMemoReply,
    onUpdateMemoThread,
    onDeleteMemoThread,
    onUpdateMemoReply,
    onDeleteMemoReply,
  };
}

export function applySidePanelPreviewHandler(
  sidePanelProps: SidePanelProps,
  onSetAttachmentPreviewId: (next: string | null) => void,
): SidePanelProps {
  return {
    ...sidePanelProps,
    onPreviewAttachment: onSetAttachmentPreviewId,
  };
}
