import { buildAttachmentPanelItems } from "@/lib/workorder/presentation/workOrderWorkspacePresentation";
import type { DetailProps, DetailViewModelArgs, SidePanelProps, SidePanelViewModelArgs } from "@/lib/workorder/workspace/viewModelTypes";

export function buildDetailProps({
  selectedWorkOrder,
  hasVisibleWorkOrders,
  currentWorkflowState,
  saveStatus,
  lastSavedAt,
  currentUser,
  currentRole,
  canChangeManager,
  canSeeProductionSections,
  canSeeCostSections,
  canOpenInventoryEditor,
  currentDisplayStage,
  currentInventoryQuantity,
  fabricTotal,
  subsidiaryTotal,
  outsourcingTotal,
  totalCost,
  unitCost,
  basicInfoOpen,
  materialOpen,
  outsourcingOpen,
  isAdmin,
  isReviewRequestLocked,
  visibleStages,
  availableActions,
  onSave,
  onWorkflowAction,
  onUpdateSelectedWorkOrder,
  onRenameWorkOrderTitle,
  onCompleteInspection,
  onOpenManagerAssignModal,
  onSetBasicInfoOpen,
  onSetMaterialOpen,
  onSetOutsourcingOpen,
  onSetInventoryEditorOpen,
}: DetailViewModelArgs): DetailProps {
  return {
    workOrder: selectedWorkOrder,
    isEmpty: !hasVisibleWorkOrders,
    currentWorkflowState,
    saveStatus,
    lastSavedAt,
    currentInventoryQuantity,
    currentUserName: currentUser.name,
    currentUserRole: currentRole,
    canRenameTitle: isAdmin,
    canEditInventory: canOpenInventoryEditor,
    canChangeManager,
    onOpenManagerAssignModal,
    canSeeProductionSections,
    canSeeCostSections,
    fabricTotal,
    subsidiaryTotal,
    outsourcingTotal,
    totalCost,
    unitCost,
    basicInfoOpen,
    materialOpen,
    outsourcingOpen,
    onSave,
    onOpenInventoryEditor: () => onSetInventoryEditorOpen(true),
    isReviewRequestLocked,
    onToggleBasicInfo: () => onSetBasicInfoOpen((prev) => !prev),
    onToggleMaterial: () => onSetMaterialOpen((prev) => !prev),
    onToggleOutsourcing: () => onSetOutsourcingOpen((prev) => !prev),
    onSetMaterialOpen,
    onSetOutsourcingOpen,
    visibleStages,
    currentDisplayStage,
    actions: availableActions,
    onAction: onWorkflowAction,
    onUpdateWorkOrder: onUpdateSelectedWorkOrder,
    onRenameWorkOrderTitle,
    onCompleteInspection,
  };
}

export function buildSidePanelProps({
  hasVisibleWorkOrders,
  canSeeAttachments,
  canUploadOfficialAttachments,
  designAttachments,
  officialAttachments,
  currentRole,
  selectedWorkOrder,
  currentUser,
  getAttachmentPermissions,
  onOpenAttachmentPicker,
  onRequestDeleteAttachment,
  onCreateMemoThread,
  onCreateMemoReply,
  onPromoteMemoAttachment,
}: SidePanelViewModelArgs): SidePanelProps {
  return {
    isEmpty: !hasVisibleWorkOrders,
    canSeeAttachments,
    canUploadOfficialAttachments,
    designAttachments: buildAttachmentPanelItems(designAttachments, getAttachmentPermissions),
    attachments: buildAttachmentPanelItems(officialAttachments, getAttachmentPermissions),
    onOpenAttachmentPicker,
    onPreviewAttachment: () => undefined,
    onDeleteAttachment: onRequestDeleteAttachment,
    currentRole,
    workOrder: selectedWorkOrder,
    currentUserName: currentUser.name,
    onCreateMemoThread,
    onCreateMemoReply,
    canPromoteMemoAttachment: canUploadOfficialAttachments,
    onPromoteMemoAttachment,
  };
}

export function applySidePanelPreviewHandler(
  sidePanelProps: SidePanelProps,
  onSetAttachmentPreviewId: (next: string | null) => void,
): SidePanelProps {
  return {
    ...sidePanelProps,
    onPreviewAttachment: onSetAttachmentPreviewId,
  };
}
