import type { ModalProps, ModalViewModelArgs } from "@/lib/workorder/workspace/viewModelTypes";

export function buildModalProps({
  i18n,
  isAdmin,
  inventoryEditorOpen,
  permissionModalOpen,
  createWorkOrderModalOpen,
  managerAssignModalOpen,
  inventoryLogModalOpen,
  orderRequestConfirmOpen,
  workflowValidationModal,
  rejectReviewReasonModal,
  users,
  currentUserId,
  permissionTargetUserId,
  historyFilter,
  currentRole,
  selectedWorkOrder,
  currentInventoryQuantity,
  filteredHistoryLogs,
  inventoryLogs,
  selectedAttachment,
  pendingAttachmentDelete,
  getAttachmentPermissions,
  onSetInventoryEditorOpen,
  onSetPermissionModalOpen,
  onSetCreateWorkOrderModalOpen,
  onSetInventoryLogModalOpen,
  onSetAttachmentPreviewId,
  onSetPermissionTargetUserId,
  onSetCurrentUserId,
  showUserSwitchingTools = false,
  onSetHistoryFilter,
  onCreateWorkOrder,
  onConfirmOrderRequest,
  onCloseOrderRequestConfirm,
  onInventoryApply,
  onApplyRoles,
  onCloseManagerAssignModal,
  onChangeManager,
  onRequestDeleteAttachment,
  onAttachmentDeleteConfirmClose,
  onAttachmentDeleteConfirm,
}: ModalViewModelArgs): ModalProps {
  const attachmentPermissions = getAttachmentPermissions(selectedAttachment);

  return {
    workflowValidation: workflowValidationModal,
    rejectReviewReason: {
      ...rejectReviewReasonModal,
      title: i18n.common.ui.modal.rejectReviewReason.title,
      description: i18n.common.ui.modal.rejectReviewReason.description,
      fieldLabel: i18n.common.ui.modal.rejectReviewReason.fieldLabel,
      placeholder: i18n.common.ui.modal.rejectReviewReason.placeholder,
      cancelLabel: i18n.common.ui.modal.rejectReviewReason.cancelLabel,
      confirmLabel: i18n.common.ui.modal.rejectReviewReason.confirmLabel,
    },
    orderRequestConfirm: {
      open: orderRequestConfirmOpen,
      workOrder: selectedWorkOrder,
      onClose: onCloseOrderRequestConfirm,
      onConfirm: onConfirmOrderRequest,
    },
    attachmentPreview: {
      attachment: selectedAttachment,
      canDownload: attachmentPermissions.canDownload,
      onClose: () => onSetAttachmentPreviewId(null),
    },
    attachmentDeleteConfirm: {
      open: pendingAttachmentDelete !== null,
      attachment: pendingAttachmentDelete,
      onClose: onAttachmentDeleteConfirmClose,
      onConfirm: onAttachmentDeleteConfirm,
    },
    inventoryLog: {
      open: inventoryLogModalOpen && isAdmin,
      onClose: () => onSetInventoryLogModalOpen(false),
      logs: filteredHistoryLogs,
      role: currentRole,
      filter: historyFilter,
    },
    managerAssign: {
      open: managerAssignModalOpen,
      onClose: onCloseManagerAssignModal,
      users,
      currentManagerId: selectedWorkOrder.managerId ?? null,
      currentManagerName: selectedWorkOrder.manager,
      onSelectManager: onChangeManager,
    },
    inventoryEditor: {
      open: inventoryEditorOpen,
      onClose: () => onSetInventoryEditorOpen(false),
      currentStock: currentInventoryQuantity,
      currentUserName: users.find((user) => user.id === currentUserId)?.name ?? "-",
      logs: inventoryLogs,
      showRecentLogs: isAdmin,
      onApply: onInventoryApply,
    },
    createWorkOrder: {
      open: createWorkOrderModalOpen,
      onClose: () => onSetCreateWorkOrderModalOpen(false),
      onCreate: onCreateWorkOrder,
    },
    permission: {
      open: permissionModalOpen && showUserSwitchingTools,
      onClose: () => onSetPermissionModalOpen(false),
      users,
      currentUserId,
      selectedUserId: permissionTargetUserId,
      onSelectedUserChange: onSetPermissionTargetUserId,
      onApplyRoles,
      onCurrentUserChange: onSetCurrentUserId,
    },
  };
}
