import type { PbpThemeDefinition } from "../themeTypes";
import { DEFAULT_LIGHT_THEME } from "./defaultLight";

export const BEIGE_ATELIER_THEME_ID = "beige-atelier" as const;

export const BEIGE_ATELIER_THEME: PbpThemeDefinition = {
  id: BEIGE_ATELIER_THEME_ID,
  name: "Beige Atelier",
  description:
    "따뜻한 베이지와 브라운 계열을 중심으로 작업지시서와 관리자 화면의 semantic token을 검증하기 위한 1차 테스트 테마입니다.",
  tone: "light",
  cssVariables: {
    ...DEFAULT_LIGHT_THEME.cssVariables,
    "--background": "#f7f0e6",
    "--foreground": "#241a12",
    "--pbp-surface": "#fffdf8",
    "--pbp-surface-muted": "#fbf4ea",
    "--pbp-surface-soft": "#f3e5d3",
    "--pbp-border": "#e7d6bd",
    "--pbp-border-strong": "#c9aa7a",
    "--pbp-text-primary": "#241a12",
    "--pbp-text-muted": "#7c6548",
    "--pbp-text-subtle": "#a38b68",
    "--pbp-accent": "#8a5a2b",
    "--pbp-accent-soft": "#fff4df",
    "--pbp-accent-border": "#d7b77f",
    "--pbp-focus-ring": "#b7791f",
    "--pbp-action-primary-surface": "#2b2118",
    "--pbp-action-primary-surface-hover": "#443223",
    "--pbp-action-primary-text": "#fffaf2",
    "--pbp-action-secondary-surface": "#fffaf2",
    "--pbp-action-secondary-surface-hover": "#f4e6d2",
    "--pbp-action-secondary-text": "#4b3622",
    "--pbp-action-add-surface": "#fffaf2",
    "--pbp-action-add-border": "#d8c1a0",
    "--pbp-action-add-text": "#5f4328",
    "--pbp-action-add-surface-hover": "#f8ead6",
    "--pbp-action-ghost-surface-hover": "#f4e6d2",
    "--pbp-action-ghost-text": "#6c4f32",
    "--pbp-selected-surface": "#f7dfb7",
    "--pbp-selected-surface-soft": "#f2cf94",
    "--pbp-selected-text": "#241a12",
    "--pbp-selected-muted-text": "#6c4f32",
    "--pbp-selected-border": "#b98945",
    "--pbp-field-editable-surface": "#fff9ed",
    "--pbp-field-editable-surface-strong": "#fff1d8",
    "--pbp-field-editable-border": "#e8d1ad",
    "--pbp-field-editable-border-strong": "#b98945",
    "--pbp-field-selectable-surface": "#fffdf8",
    "--pbp-field-selectable-border": "#e2cba7",
    "--pbp-field-search-surface": "#fffdf8",
    "--pbp-field-search-border": "#d8c1a0",
    "--pbp-field-filter-active-surface": "#fff4df",
    "--pbp-field-filter-active-border": "#d7b77f",
    "--pbp-field-filter-active-text": "#8a5a2b",
    "--pbp-field-calculated-surface": "#f7efe4",
    "--pbp-field-calculated-border": "#ead8bf",
    "--pbp-field-calculated-text": "#6c4f32",
    "--pbp-empty-state-surface": "#fbf4ea",
    "--pbp-empty-state-border": "#e7d6bd",
    "--pbp-sidepanel-item-surface": "#fbf4ea",
    "--pbp-sidepanel-item-border": "#e7d6bd",
    "--pbp-sidepanel-item-surface-hover": "#fffdf8",
    "--pbp-sidepanel-preview-surface": "#fffaf2",
    "--pbp-sidepanel-upload-surface": "#fbf4ea",
    "--pbp-sidepanel-upload-surface-hover": "#fffdf8",
    "--pbp-sidepanel-upload-border": "#d8c1a0",
    "--pbp-sidepanel-upload-active-surface": "#fffaf2",
    "--pbp-sidepanel-upload-active-border": "#d7b77f",
    "--pbp-sidepanel-count-surface": "#f4e6d2",
    "--pbp-sidepanel-count-text": "#6c4f32",
    "--pbp-modal-overlay": "rgba(36, 26, 18, 0.48)",
    "--pbp-modal-overlay-soft": "rgba(36, 26, 18, 0.34)",
    "--pbp-modal-surface": "#fffdf8",
    "--pbp-modal-chrome": "#fffdf8",
    "--pbp-modal-body": "#fffdf8",
    "--pbp-modal-section-surface": "#fffaf2",
    "--pbp-modal-section-border": "#e7d6bd",
    "--pbp-modal-section-muted": "#fbf4ea",
    "--pbp-toggle-on-surface": "#2b2118",
    "--pbp-toggle-on-border": "#2b2118",
    "--pbp-toggle-off-surface": "#ead8bf",
    "--pbp-toggle-off-border": "#d8c1a0",
    "--pbp-toast-background": "#241a12",
    "--pbp-toast-foreground": "#fffaf2",
    "--pbp-shadow-card": "0 1px 3px rgba(36, 26, 18, 0.09), 0 1px 2px rgba(36, 26, 18, 0.05)",
    "--pbp-shadow-elevated": "0 18px 55px rgba(36, 26, 18, 0.24)",
  },
};
