import type { PbpThemeDefinition } from "../themeTypes";
import { DEFAULT_LIGHT_THEME } from "./defaultLight";

export const BLACK_AND_WHITE_THEME_ID = "black-and-white" as const;

export const BLACK_AND_WHITE_THEME: PbpThemeDefinition = {
  id: BLACK_AND_WHITE_THEME_ID,
  name: "Black & White",
  description:
    "명도 대비와 경계선을 더 강하게 두어 작업지시서와 관리자 화면의 고대비 접근성을 점검하기 위한 라이트 테마입니다.",
  tone: "light",
  cssVariables: {
    ...DEFAULT_LIGHT_THEME.cssVariables,
    "--background": "#f1f1f1",
    "--foreground": "#050505",
    "--pbp-surface": "#ffffff",
    "--pbp-surface-muted": "#f6f6f6",
    "--pbp-surface-soft": "#e9e9e9",
    "--pbp-border": "#c7c7c7",
    "--pbp-border-strong": "#7a7a7a",
    "--pbp-text-primary": "#050505",
    "--pbp-text-muted": "#4c4c4c",
    "--pbp-text-subtle": "#757575",
    "--pbp-accent": "#111111",
    "--pbp-accent-soft": "#eeeeee",
    "--pbp-accent-border": "#9b9b9b",
    "--pbp-focus-ring": "#111111",
    "--pbp-action-primary-surface": "#050505",
    "--pbp-action-primary-surface-hover": "#2c2c2c",
    "--pbp-action-primary-text": "#ffffff",
    "--pbp-action-secondary-surface": "#ffffff",
    "--pbp-action-secondary-surface-hover": "#ededed",
    "--pbp-action-secondary-text": "#111111",
    "--pbp-action-add-surface": "#ffffff",
    "--pbp-action-add-border": "#999999",
    "--pbp-action-add-text": "#111111",
    "--pbp-action-add-surface-hover": "#ededed",
    "--pbp-action-ghost-surface-hover": "#e5e5e5",
    "--pbp-action-ghost-text": "#333333",
    "--pbp-selected-surface": "#e5e5e5",
    "--pbp-selected-surface-soft": "#d4d4d4",
    "--pbp-selected-text": "#050505",
    "--pbp-selected-muted-text": "#333333",
    "--pbp-selected-border": "#666666",
    "--pbp-chart-1": "#050505",
    "--pbp-chart-2": "#7a7a7a",
    "--pbp-chart-3": "#d4d4d4",
    "--pbp-chart-4": "#3f3f46",
    "--pbp-chart-5": "#a3a3a3",
    "--pbp-chart-6": "#525252",
    "--pbp-workorder-status-draft-bg": "#f4f4f4",
    "--pbp-workorder-status-draft-text": "#525252",
    "--pbp-workorder-status-draft-dot": "#7a7a7a",
    "--pbp-workorder-status-review-requested-bg": "#eeeeee",
    "--pbp-workorder-status-review-requested-text": "#333333",
    "--pbp-workorder-status-review-requested-dot": "#666666",
    "--pbp-workorder-status-review-completed-bg": "#e5e5e5",
    "--pbp-workorder-status-review-completed-text": "#262626",
    "--pbp-workorder-status-review-completed-dot": "#525252",
    "--pbp-workorder-status-request-order-bg": "#f5f5f5",
    "--pbp-workorder-status-request-order-text": "#3f3f46",
    "--pbp-workorder-status-request-order-dot": "#737373",
    "--pbp-workorder-status-inspection-bg": "#ededed",
    "--pbp-workorder-status-inspection-text": "#111111",
    "--pbp-workorder-status-inspection-dot": "#3f3f46",
    "--pbp-workorder-status-completed-bg": "#050505",
    "--pbp-workorder-status-completed-text": "#ffffff",
    "--pbp-workorder-status-completed-dot": "#ffffff",
    "--pbp-workorder-status-rejected-bg": "#f4f4f4",
    "--pbp-workorder-status-rejected-text": "#111111",
    "--pbp-workorder-status-rejected-dot": "#050505",
    "--pbp-field-editable-surface": "#ffffff",
    "--pbp-field-editable-surface-strong": "#f4f4f4",
    "--pbp-field-editable-border": "#a7a7a7",
    "--pbp-field-editable-border-strong": "#333333",
    "--pbp-field-selectable-surface": "#ffffff",
    "--pbp-field-selectable-border": "#a7a7a7",
    "--pbp-field-search-surface": "#ffffff",
    "--pbp-field-search-border": "#999999",
    "--pbp-field-filter-active-surface": "#eeeeee",
    "--pbp-field-filter-active-border": "#666666",
    "--pbp-field-filter-active-text": "#050505",
    "--pbp-field-calculated-surface": "#f5f5f5",
    "--pbp-field-calculated-border": "#c7c7c7",
    "--pbp-field-calculated-text": "#333333",
    "--pbp-field-disabled-surface": "#e8e8e8",
    "--pbp-field-disabled-text": "#777777",
    "--pbp-empty-state-surface": "#f6f6f6",
    "--pbp-empty-state-border": "#c7c7c7",
    "--pbp-sidepanel-item-surface": "#f6f6f6",
    "--pbp-sidepanel-item-border": "#c7c7c7",
    "--pbp-sidepanel-item-surface-hover": "#ffffff",
    "--pbp-sidepanel-preview-surface": "#ffffff",
    "--pbp-sidepanel-upload-surface": "#f6f6f6",
    "--pbp-sidepanel-upload-surface-hover": "#ffffff",
    "--pbp-sidepanel-upload-border": "#999999",
    "--pbp-sidepanel-upload-active-surface": "#ffffff",
    "--pbp-sidepanel-upload-active-border": "#666666",
    "--pbp-sidepanel-count-surface": "#e5e5e5",
    "--pbp-sidepanel-count-text": "#333333",
    "--pbp-modal-overlay": "rgba(5, 5, 5, 0.56)",
    "--pbp-modal-overlay-soft": "rgba(5, 5, 5, 0.38)",
    "--pbp-modal-surface": "#ffffff",
    "--pbp-modal-chrome": "#ffffff",
    "--pbp-modal-body": "#ffffff",
    "--pbp-modal-section-surface": "#f6f6f6",
    "--pbp-modal-section-border": "#c7c7c7",
    "--pbp-modal-section-muted": "#ededed",
    "--pbp-toggle-on-surface": "#050505",
    "--pbp-toggle-on-border": "#050505",
    "--pbp-toggle-off-surface": "#d4d4d4",
    "--pbp-toggle-off-border": "#9b9b9b",
    "--pbp-toast-background": "#050505",
    "--pbp-toast-foreground": "#ffffff",
    "--pbp-shadow-card": "0 1px 3px rgba(5, 5, 5, 0.12), 0 1px 2px rgba(5, 5, 5, 0.08)",
    "--pbp-shadow-elevated": "0 18px 55px rgba(5, 5, 5, 0.28)",
  },
};
