import type { PbpThemeDefinition } from "../themeTypes";
import { DEFAULT_LIGHT_THEME } from "./defaultLight";

export const COLD_WINTER_THEME_ID = "cold-winter" as const;

export const COLD_WINTER_THEME: PbpThemeDefinition = {
  id: COLD_WINTER_THEME_ID,
  name: "Cold Winter",
  description:
    "차가운 블루 그레이와 잉크 계열을 중심으로 작업지시서와 관리자 화면의 semantic token 대비를 검증하기 위한 2차 테스트 테마입니다.",
  tone: "light",
  cssVariables: {
    ...DEFAULT_LIGHT_THEME.cssVariables,
    "--background": "#f3f7fb",
    "--foreground": "#111827",
    "--pbp-surface": "#ffffff",
    "--pbp-surface-muted": "#f6f9fc",
    "--pbp-surface-soft": "#eaf2f8",
    "--pbp-border": "#d7e3ee",
    "--pbp-border-strong": "#9fb7cf",
    "--pbp-text-primary": "#102033",
    "--pbp-text-muted": "#526579",
    "--pbp-text-subtle": "#8aa0b4",
    "--pbp-accent": "#1d4ed8",
    "--pbp-accent-soft": "#eaf2ff",
    "--pbp-accent-border": "#b7cffc",
    "--pbp-focus-ring": "#3b82f6",
    "--pbp-action-primary-surface": "#102033",
    "--pbp-action-primary-surface-hover": "#1f334a",
    "--pbp-action-primary-text": "#f8fbff",
    "--pbp-action-secondary-surface": "#ffffff",
    "--pbp-action-secondary-surface-hover": "#edf4fb",
    "--pbp-action-secondary-text": "#24364a",
    "--pbp-action-add-surface": "#ffffff",
    "--pbp-action-add-border": "#c7d7e6",
    "--pbp-action-add-text": "#26435f",
    "--pbp-action-add-surface-hover": "#edf4fb",
    "--pbp-action-ghost-surface-hover": "#eaf2f8",
    "--pbp-action-ghost-text": "#42566b",
    "--pbp-selected-surface": "#dceaff",
    "--pbp-selected-surface-soft": "#cfe1fb",
    "--pbp-selected-text": "#102033",
    "--pbp-selected-muted-text": "#42566b",
    "--pbp-selected-border": "#8fb4e8",
    "--pbp-field-editable-surface": "#fbfdff",
    "--pbp-field-editable-surface-strong": "#eef6ff",
    "--pbp-field-editable-border": "#ccdeef",
    "--pbp-field-editable-border-strong": "#7aa8d7",
    "--pbp-field-selectable-surface": "#f8fbff",
    "--pbp-field-selectable-border": "#c6d9eb",
    "--pbp-field-search-surface": "#ffffff",
    "--pbp-field-search-border": "#c6d9eb",
    "--pbp-field-filter-active-surface": "#eaf2ff",
    "--pbp-field-filter-active-border": "#b7cffc",
    "--pbp-field-filter-active-text": "#1d4ed8",
    "--pbp-field-calculated-surface": "#eef3f8",
    "--pbp-field-calculated-border": "#d8e4ee",
    "--pbp-field-calculated-text": "#42566b",
    "--pbp-field-disabled-surface": "#eaf0f6",
    "--pbp-field-disabled-text": "#8aa0b4",
    "--pbp-empty-state-surface": "#f6f9fc",
    "--pbp-empty-state-border": "#d7e3ee",
    "--pbp-sidepanel-item-surface": "#f6f9fc",
    "--pbp-sidepanel-item-border": "#d7e3ee",
    "--pbp-sidepanel-item-surface-hover": "#ffffff",
    "--pbp-sidepanel-preview-surface": "#ffffff",
    "--pbp-sidepanel-upload-surface": "#f6f9fc",
    "--pbp-sidepanel-upload-surface-hover": "#ffffff",
    "--pbp-sidepanel-upload-border": "#c7d7e6",
    "--pbp-sidepanel-upload-active-surface": "#eef6ff",
    "--pbp-sidepanel-upload-active-border": "#8fb4e8",
    "--pbp-sidepanel-count-surface": "#eaf2f8",
    "--pbp-sidepanel-count-text": "#42566b",
    "--pbp-modal-overlay": "rgba(16, 32, 51, 0.5)",
    "--pbp-modal-overlay-soft": "rgba(16, 32, 51, 0.34)",
    "--pbp-modal-surface": "#ffffff",
    "--pbp-modal-chrome": "#ffffff",
    "--pbp-modal-body": "#ffffff",
    "--pbp-modal-section-surface": "#f8fbff",
    "--pbp-modal-section-border": "#d7e3ee",
    "--pbp-modal-section-muted": "#f6f9fc",
    "--pbp-toggle-on-surface": "#102033",
    "--pbp-toggle-on-border": "#102033",
    "--pbp-toggle-off-surface": "#d8e4ee",
    "--pbp-toggle-off-border": "#c7d7e6",
    "--pbp-toast-background": "#102033",
    "--pbp-toast-foreground": "#f8fbff",
    "--pbp-shadow-card": "0 1px 3px rgba(16, 32, 51, 0.08), 0 1px 2px rgba(16, 32, 51, 0.04)",
    "--pbp-shadow-elevated": "0 18px 55px rgba(16, 32, 51, 0.24)",
  },
};
