import type { PbpThemeDefinition } from "../themeTypes";

export const DEFAULT_LIGHT_THEME_ID = "default-light" as const;

export const DEFAULT_LIGHT_THEME: PbpThemeDefinition = {
  id: DEFAULT_LIGHT_THEME_ID,
  name: "Default Light",
  description:
    "현재 작업지시서 semantic token 기준을 그대로 담은 기본 라이트 테마입니다. CSS 변수와 값은 app/globals.css의 :root 기본값과 동기화해야 합니다.",
  tone: "light",
  cssVariables: {
    "--background": "#f5f5f4",
    "--foreground": "#171717",
    "--pbp-surface": "#ffffff",
    "--pbp-surface-muted": "#fafaf9",
    "--pbp-surface-soft": "#f5f5f4",
    "--pbp-border": "#e7e5e4",
    "--pbp-border-strong": "#d6d3d1",
    "--pbp-text-primary": "#1c1917",
    "--pbp-text-muted": "#78716c",
    "--pbp-text-subtle": "#a8a29e",
    "--pbp-accent": "#065f46",
    "--pbp-accent-soft": "#ecfdf5",
    "--pbp-accent-border": "#a7f3d0",
    "--pbp-focus-ring": "#10b981",
    "--pbp-action-primary-surface": "#1c1917",
    "--pbp-action-primary-surface-hover": "#292524",
    "--pbp-action-primary-text": "#ffffff",
    "--pbp-action-danger-surface": "#e11d48",
    "--pbp-action-danger-surface-hover": "#be123c",
    "--pbp-action-danger-text": "#ffffff",
    "--pbp-action-ghost-surface": "transparent",
    "--pbp-action-ghost-surface-hover": "#f5f5f4",
    "--pbp-action-ghost-text": "#57534e",
    "--pbp-action-secondary-surface": "#ffffff",
    "--pbp-action-secondary-surface-hover": "#f5f5f4",
    "--pbp-action-secondary-text": "#44403c",
    "--pbp-action-add-surface": "#ffffff",
    "--pbp-action-add-border": "#d6d3d1",
    "--pbp-action-add-text": "#44403c",
    "--pbp-action-add-surface-hover": "#fafaf9",
    "--pbp-action-danger-soft-surface": "#fff7f7",
    "--pbp-action-danger-soft-border": "#fecdd3",
    "--pbp-action-danger-soft-text": "#e11d48",
    "--pbp-selected-surface": "#fff8e8",
    "--pbp-selected-surface-soft": "#f7ecd4",
    "--pbp-selected-text": "#1c1917",
    "--pbp-selected-muted-text": "#78716c",
    "--pbp-selected-border": "#d6c2a2",
    "--pbp-danger": "#dc2626",
    "--pbp-danger-soft": "#fef2f2",
    "--pbp-warning": "#d97706",
    "--pbp-warning-soft": "#fffbeb",
    "--pbp-status-success": "#059669",
    "--pbp-status-success-soft": "#ecfdf5",
    "--pbp-status-warning": "#d97706",
    "--pbp-status-warning-soft": "#fffbeb",
    "--pbp-status-danger": "#dc2626",
    "--pbp-status-danger-soft": "#fef2f2",
    "--pbp-status-neutral": "#57534e",
    "--pbp-status-neutral-soft": "#f5f5f4",
    "--pbp-chart-1": "#111827",
    "--pbp-chart-2": "#d97706",
    "--pbp-chart-3": "#059669",
    "--pbp-chart-4": "#2563eb",
    "--pbp-chart-5": "#7c3aed",
    "--pbp-chart-6": "#64748b",
    "--pbp-workorder-status-draft-bg": "#f5f5f4",
    "--pbp-workorder-status-draft-text": "#57534e",
    "--pbp-workorder-status-draft-dot": "#78716c",
    "--pbp-workorder-status-review-requested-bg": "#f5f3ff",
    "--pbp-workorder-status-review-requested-text": "#6d28d9",
    "--pbp-workorder-status-review-requested-dot": "#8b5cf6",
    "--pbp-workorder-status-review-completed-bg": "#fdf4ff",
    "--pbp-workorder-status-review-completed-text": "#a21caf",
    "--pbp-workorder-status-review-completed-dot": "#d946ef",
    "--pbp-workorder-status-request-order-bg": "#fffbeb",
    "--pbp-workorder-status-request-order-text": "#b45309",
    "--pbp-workorder-status-request-order-dot": "#f59e0b",
    "--pbp-workorder-status-inspection-bg": "#ecfdf5",
    "--pbp-workorder-status-inspection-text": "#047857",
    "--pbp-workorder-status-inspection-dot": "#10b981",
    "--pbp-workorder-status-completed-bg": "#292524",
    "--pbp-workorder-status-completed-text": "#ffffff",
    "--pbp-workorder-status-completed-dot": "#ffffff",
    "--pbp-workorder-status-rejected-bg": "#fef2f2",
    "--pbp-workorder-status-rejected-text": "#be123c",
    "--pbp-workorder-status-rejected-dot": "#f43f5e",
    "--pbp-field-editable-surface": "#fffefa",
    "--pbp-field-editable-surface-strong": "#fffaf0",
    "--pbp-field-editable-border": "#eee3cf",
    "--pbp-field-editable-border-strong": "#bda36f",
    "--pbp-field-selectable-surface": "#fbfdfc",
    "--pbp-field-selectable-border": "#dcebe4",
    "--pbp-field-search-surface": "#ffffff",
    "--pbp-field-search-border": "#d6d3d1",
    "--pbp-field-filter-active-surface": "#ecfdf5",
    "--pbp-field-filter-active-border": "#a7f3d0",
    "--pbp-field-filter-active-text": "#065f46",
    "--pbp-field-calculated-surface": "#faf9f7",
    "--pbp-field-calculated-border": "#eee9df",
    "--pbp-field-calculated-text": "#57534e",
    "--pbp-field-disabled-surface": "#f5f5f4",
    "--pbp-field-disabled-text": "#a8a29e",
    "--pbp-empty-state-surface": "#fafaf9",
    "--pbp-empty-state-border": "#e7e5e4",
    "--pbp-sidepanel-item-surface": "#fafaf9",
    "--pbp-sidepanel-item-border": "#e7e5e4",
    "--pbp-sidepanel-item-surface-hover": "#ffffff",
    "--pbp-sidepanel-preview-surface": "#ffffff",
    "--pbp-sidepanel-upload-surface": "#fafaf9",
    "--pbp-sidepanel-upload-surface-hover": "#ffffff",
    "--pbp-sidepanel-upload-border": "#d6d3d1",
    "--pbp-sidepanel-upload-active-surface": "#ffffff",
    "--pbp-sidepanel-upload-active-border": "#a7f3d0",
    "--pbp-sidepanel-count-surface": "#f5f5f4",
    "--pbp-sidepanel-count-text": "#57534e",
    "--pbp-modal-overlay": "rgba(28, 25, 23, 0.48)",
    "--pbp-modal-overlay-soft": "rgba(28, 25, 23, 0.34)",
    "--pbp-modal-surface": "#ffffff",
    "--pbp-modal-chrome": "#ffffff",
    "--pbp-modal-body": "#ffffff",
    "--pbp-modal-section-surface": "#ffffff",
    "--pbp-modal-section-border": "#e7e5e4",
    "--pbp-modal-section-muted": "#fafaf9",
    "--pbp-toggle-on-surface": "#1c1917",
    "--pbp-toggle-on-border": "#1c1917",
    "--pbp-toggle-off-surface": "#e7e5e4",
    "--pbp-toggle-off-border": "#d6d3d1",
    "--pbp-toggle-thumb-surface": "#ffffff",
    "--pbp-toast-background": "#171717",
    "--pbp-toast-foreground": "#ffffff",
    "--pbp-shadow-card": "0 1px 3px rgba(28, 25, 23, 0.08), 0 1px 2px rgba(28, 25, 23, 0.04)",
    "--pbp-shadow-elevated": "0 18px 55px rgba(28, 25, 23, 0.22)",
  },
};
