import type { PbpThemeDefinition } from "../themeTypes";
import { DEFAULT_LIGHT_THEME } from "./defaultLight";

export const SOFT_EMERALD_THEME_ID = "soft-emerald" as const;

export const SOFT_EMERALD_THEME: PbpThemeDefinition = {
  id: SOFT_EMERALD_THEME_ID,
  name: "Soft Emerald",
  description:
    "default-light보다 녹색 계열을 더 분명하게 적용해 브랜드 accent와 업무 화면 surface의 확장성을 확인하기 위한 라이트 테마입니다.",
  tone: "light",
  cssVariables: {
    ...DEFAULT_LIGHT_THEME.cssVariables,
    "--background": "#edf8f3",
    "--foreground": "#09251d",
    "--pbp-surface": "#fbfffd",
    "--pbp-surface-muted": "#f0faf5",
    "--pbp-surface-soft": "#dff3ea",
    "--pbp-border": "#c2e2d3",
    "--pbp-border-strong": "#7fb99d",
    "--pbp-text-primary": "#09251d",
    "--pbp-text-muted": "#4d6f61",
    "--pbp-text-subtle": "#83a495",
    "--pbp-accent": "#047857",
    "--pbp-accent-soft": "#dff8ec",
    "--pbp-accent-border": "#98e4c3",
    "--pbp-focus-ring": "#10b981",
    "--pbp-action-primary-surface": "#073b2d",
    "--pbp-action-primary-surface-hover": "#0b4e3c",
    "--pbp-action-primary-text": "#fbfffd",
    "--pbp-action-secondary-surface": "#fbfffd",
    "--pbp-action-secondary-surface-hover": "#e5f5ee",
    "--pbp-action-secondary-text": "#214f40",
    "--pbp-action-add-surface": "#fbfffd",
    "--pbp-action-add-border": "#9dceba",
    "--pbp-action-add-text": "#1f5f4b",
    "--pbp-action-add-surface-hover": "#e5f5ee",
    "--pbp-action-ghost-surface-hover": "#dff3ea",
    "--pbp-action-ghost-text": "#386757",
    "--pbp-selected-surface": "#d6f4e5",
    "--pbp-selected-surface-soft": "#c4ead9",
    "--pbp-selected-text": "#09251d",
    "--pbp-selected-muted-text": "#386757",
    "--pbp-selected-border": "#7fb99d",
    "--pbp-chart-1": "#073b2d",
    "--pbp-chart-2": "#d97706",
    "--pbp-chart-3": "#059669",
    "--pbp-chart-4": "#2563eb",
    "--pbp-chart-5": "#7c3aed",
    "--pbp-chart-6": "#5f6f52",
    "--pbp-field-editable-surface": "#fbfffd",
    "--pbp-field-editable-surface-strong": "#effbf6",
    "--pbp-field-editable-border": "#b8ddcc",
    "--pbp-field-editable-border-strong": "#62a88b",
    "--pbp-field-selectable-surface": "#fbfffd",
    "--pbp-field-selectable-border": "#b8ddcc",
    "--pbp-field-search-surface": "#fbfffd",
    "--pbp-field-search-border": "#a7cfbd",
    "--pbp-field-filter-active-surface": "#dff8ec",
    "--pbp-field-filter-active-border": "#98e4c3",
    "--pbp-field-filter-active-text": "#047857",
    "--pbp-field-calculated-surface": "#f1f8f4",
    "--pbp-field-calculated-border": "#d1e7dc",
    "--pbp-field-calculated-text": "#386757",
    "--pbp-field-disabled-surface": "#e7f2ed",
    "--pbp-field-disabled-text": "#83a495",
    "--pbp-empty-state-surface": "#f0faf5",
    "--pbp-empty-state-border": "#cde5d9",
    "--pbp-sidepanel-item-surface": "#f0faf5",
    "--pbp-sidepanel-item-border": "#cde5d9",
    "--pbp-sidepanel-item-surface-hover": "#fbfffd",
    "--pbp-sidepanel-preview-surface": "#fbfffd",
    "--pbp-sidepanel-upload-surface": "#f0faf5",
    "--pbp-sidepanel-upload-surface-hover": "#fbfffd",
    "--pbp-sidepanel-upload-border": "#a7cfbd",
    "--pbp-sidepanel-upload-active-surface": "#effbf6",
    "--pbp-sidepanel-upload-active-border": "#7fb99d",
    "--pbp-sidepanel-count-surface": "#dff3ea",
    "--pbp-sidepanel-count-text": "#386757",
    "--pbp-modal-overlay": "rgba(9, 37, 29, 0.5)",
    "--pbp-modal-overlay-soft": "rgba(9, 37, 29, 0.34)",
    "--pbp-modal-surface": "#fbfffd",
    "--pbp-modal-chrome": "#fbfffd",
    "--pbp-modal-body": "#fbfffd",
    "--pbp-modal-section-surface": "#f0faf5",
    "--pbp-modal-section-border": "#cde5d9",
    "--pbp-modal-section-muted": "#e7f2ed",
    "--pbp-toggle-on-surface": "#073b2d",
    "--pbp-toggle-on-border": "#073b2d",
    "--pbp-toggle-off-surface": "#c2e2d3",
    "--pbp-toggle-off-border": "#9dceba",
    "--pbp-toast-background": "#09251d",
    "--pbp-toast-foreground": "#fbfffd",
    "--pbp-shadow-card": "0 1px 3px rgba(9, 37, 29, 0.1), 0 1px 2px rgba(9, 37, 29, 0.05)",
    "--pbp-shadow-elevated": "0 18px 55px rgba(9, 37, 29, 0.24)",
  },
};
