export const WORKORDER_PDF_LABELS = {
  documentTitle: "작업지시서",
  orderRequestTitle: "발주요청서",
  workOrderTitle: "작업지시서명",
  internalCode: "작업번호",
  partner: "거래처",
  factory: "공장",
  dueDate: "납기일",
  season: "시즌",
  category: "분류",
  materials: "원단 / 부자재",
  outsourcing: "외주 공정",
  attachments: "첨부파일",
  memo: "메모",
  quantity: "수량",
  unitPrice: "단가",
  amount: "금액",
} as const;
