export const WAFL_WORKSPACE_PANEL_PADDING_CLASS = "p-3.5 sm:p-4";
export const WAFL_WORKSPACE_SECTION_PADDING_CLASS = "p-3.5 sm:p-4";
export const WAFL_WORKSPACE_SECTION_GAP_CLASS = "gap-3";
export const WAFL_WORKSPACE_PANEL_GAP_CLASS = "gap-3";
