import {
  WAFL_FIELD_INPUT_CLASS,
  WAFL_FIELD_TEXTAREA_CLASS,
} from "@/components/common/ui";

export const MODAL_INPUT_CLASS = WAFL_FIELD_INPUT_CLASS;

export const MODAL_SELECT_CLASS = WAFL_FIELD_INPUT_CLASS;

export const MODAL_TEXTAREA_CLASS = WAFL_FIELD_TEXTAREA_CLASS;
