import "server-only";

import { performance } from "perf_hooks";

import { withWaflV2TenantReadOnlyTransaction, withWaflV2TenantWriteTransaction, type DbQueryResultRow } from "@/lib/db/client";
import { installTenantClaims } from "@/lib/domain/work-orders/command/commandRepository";
import type { ReorderAssetCopyPlan } from "@/lib/domain/work-orders/command/reorderCommandRepository";
import type { CreateWorkOrderCopyResult, EntityVersion, TenantMemberScope, WorkOrderId, WorkOrderRevisionId } from "@/lib/domain/work-orders/contracts";
import { serializePostgresDateOnly } from "@/lib/domain/work-orders/dateOnly.mjs";
import { resolveWorkOrderCopyProductName } from "@/lib/domain/work-orders/command/copyProductNamePolicy";

export const WORK_ORDER_COPY_CREATE_COMMAND_CODE = "work_order.create_copy";
type Receipt = DbQueryResultRow & { readonly request_sha256: string; readonly work_order_id: string | null; readonly result_revision_id: string | null; readonly result_entity_version: number | string | null };
type ResultRow = DbQueryResultRow & { readonly work_order_id: string; readonly revision_id: string; readonly product_name: string; readonly product_type_code: string | null; readonly season_code: string | null; readonly item_code: string | null; readonly due_date: string | null; readonly total_quantity: number | string; readonly memo: string | null; readonly factory_delivery_memo: string | null; readonly is_sample: boolean };
export class CopyCommandRepositoryError extends Error { constructor(readonly reason: "not_found" | "idempotency_conflict" | "idempotency_incomplete") { super(reason); } }
const RESULT_SQL = `SELECT w.id work_order_id,r.id revision_id,w.product_name,w.product_type_code,w.season_code,w.item_code,w.due_date::text due_date,w.total_quantity,r.memo,r.factory_delivery_memo,w.is_sample FROM work_orders w JOIN work_order_revisions r ON r.company_id=w.company_id AND r.id=w.current_revision_id WHERE w.company_id=$1 AND w.id=$2::uuid AND r.id=$3::uuid`;
function map(row: ResultRow): CreateWorkOrderCopyResult { return { workOrderId: row.work_order_id as WorkOrderId, revisionId: row.revision_id as WorkOrderRevisionId, revisionNumber: 0 as never, status: "draft", revisionStatus: "draft", displayDocumentNumber: null, productName: row.product_name, productTypeCode: row.product_type_code, seasonCode: row.season_code, itemCode: row.item_code, dueDate: serializePostgresDateOnly(row.due_date, "COPY_INVALID_DUE_DATE"), totalQuantity: Number(row.total_quantity), memo: row.memo, factoryDeliveryMemo: row.factory_delivery_memo, isSample: row.is_sample, derivationKind: "original", reorderRound: 0 }; }

export async function readCompletedWorkOrderCopyReplay(input: { readonly scope: TenantMemberScope; readonly keyHash: string; readonly requestHash: string }) {
  return withWaflV2TenantReadOnlyTransaction(async (client) => { await installTenantClaims(client, input.scope); const receipt = (await client.query<Receipt>(`SELECT request_sha256,work_order_id,result_revision_id,result_entity_version FROM work_order_command_receipts WHERE company_id=$1 AND command_code=$2 AND idempotency_key=$3`, [input.scope.companyId, WORK_ORDER_COPY_CREATE_COMMAND_CODE, input.keyHash])).rows[0]; if (!receipt) return null; if (receipt.request_sha256 !== input.requestHash) throw new CopyCommandRepositoryError("idempotency_conflict"); if (!receipt.work_order_id || !receipt.result_revision_id || receipt.result_entity_version === null) throw new CopyCommandRepositoryError("idempotency_incomplete"); const row = (await client.query<ResultRow>(RESULT_SQL, [input.scope.companyId, receipt.work_order_id, receipt.result_revision_id])).rows[0]; if (!row) throw new CopyCommandRepositoryError("idempotency_incomplete"); return map(row); });
}

export async function createWorkOrderCopyV2(input: { readonly scope: TenantMemberScope; readonly sourceWorkOrderId: WorkOrderId; readonly targetWorkOrderId: WorkOrderId; readonly targetRevisionId: WorkOrderRevisionId; readonly targetSizeSpecId: string; readonly keyHash: string; readonly requestHash: string; readonly clientRequestId: string; readonly assets: ReorderAssetCopyPlan }) {
  const started = performance.now(); let statementCount = 0;
  const value = await withWaflV2TenantWriteTransaction(async (client) => {
    await installTenantClaims(client, input.scope); statementCount += 1;
    const reserved = await client.query<Receipt>(`INSERT INTO work_order_command_receipts(company_id,command_code,idempotency_key,request_sha256,correlation_id) VALUES($1,$2,$3,$4,$5) ON CONFLICT(company_id,command_code,idempotency_key) DO NOTHING RETURNING request_sha256`, [input.scope.companyId, WORK_ORDER_COPY_CREATE_COMMAND_CODE, input.keyHash, input.requestHash, input.scope.correlationId]); statementCount += 1;
    if (!reserved.rows[0]) { const replay = (await client.query<Receipt>(`SELECT request_sha256,work_order_id,result_revision_id,result_entity_version FROM work_order_command_receipts WHERE company_id=$1 AND command_code=$2 AND idempotency_key=$3`, [input.scope.companyId, WORK_ORDER_COPY_CREATE_COMMAND_CODE, input.keyHash])).rows[0]; statementCount += 1; if (!replay || replay.request_sha256 !== input.requestHash) throw new CopyCommandRepositoryError("idempotency_conflict"); if (!replay.work_order_id || !replay.result_revision_id) throw new CopyCommandRepositoryError("idempotency_incomplete"); const row = (await client.query<ResultRow>(RESULT_SQL, [input.scope.companyId, replay.work_order_id, replay.result_revision_id])).rows[0]; statementCount += 1; if (!row) throw new CopyCommandRepositoryError("idempotency_incomplete"); return { row, replay: true }; }
    const source = (await client.query<DbQueryResultRow & { readonly revision_id: string; readonly product_name_snapshot: string }>(`SELECT w.current_revision_id revision_id,r.product_name_snapshot FROM work_orders w JOIN work_order_revisions r ON r.company_id=w.company_id AND r.id=w.current_revision_id WHERE w.company_id=$1 AND w.id=$2::uuid AND w.deleted_at IS NULL FOR SHARE`, [input.scope.companyId, input.sourceWorkOrderId])).rows[0]; statementCount += 1; if (!source) throw new CopyCommandRepositoryError("not_found");
    const copyProductName = resolveWorkOrderCopyProductName(source.product_name_snapshot);
    await client.query(`INSERT INTO work_orders(id,company_id,product_name,product_type_code,season_code,item_code,status,due_date,total_quantity,created_by_member_id,entity_version,is_sample,derivation_kind,reorder_round) SELECT $3::uuid,$1,$6,r.product_type_code_snapshot,r.season_code_snapshot,r.item_code_snapshot,'draft',r.due_date_snapshot,r.total_quantity_snapshot,$4,1,w.is_sample,'original',0 FROM work_orders w JOIN work_order_revisions r ON r.company_id=w.company_id AND r.id=$2::uuid WHERE w.company_id=$1 AND w.id=$5::uuid`, [input.scope.companyId, source.revision_id, input.targetWorkOrderId, input.scope.companyMemberId, input.sourceWorkOrderId, copyProductName]); statementCount += 1;
    await client.query(`INSERT INTO work_order_revisions(id,company_id,work_order_id,revision_no,revision_status,source_revision_id,company_code_snapshot,season_code_snapshot,item_code_snapshot,product_name_snapshot,product_type_code_snapshot,due_date_snapshot,total_quantity_snapshot,unit_price,memo,factory_delivery_memo,author_member_id,entity_version) SELECT $3::uuid,$1,$2::uuid,0,'draft',NULL,company_code_snapshot,season_code_snapshot,item_code_snapshot,$6,product_type_code_snapshot,due_date_snapshot,total_quantity_snapshot,unit_price,memo,factory_delivery_memo,$4,1 FROM work_order_revisions WHERE company_id=$1 AND id=$5::uuid`, [input.scope.companyId, input.targetWorkOrderId, input.targetRevisionId, input.scope.companyMemberId, source.revision_id, copyProductName]); statementCount += 1;
    await client.query(`INSERT INTO work_order_colors(id,company_id,revision_id,color_code,display_name,hex_value,display_order) SELECT gen_random_uuid(),$1,$2::uuid,color_code,display_name,hex_value,display_order FROM work_order_colors WHERE company_id=$1 AND revision_id=$3::uuid`, [input.scope.companyId, input.targetRevisionId, source.revision_id]); statementCount += 1;
    await client.query(`INSERT INTO work_order_sizes(id,company_id,revision_id,size_code,display_label,display_order) SELECT gen_random_uuid(),$1,$2::uuid,size_code,display_label,display_order FROM work_order_sizes WHERE company_id=$1 AND revision_id=$3::uuid`, [input.scope.companyId, input.targetRevisionId, source.revision_id]); statementCount += 1;
    await client.query(`INSERT INTO color_size_quantities(company_id,revision_id,color_id,size_id,quantity) SELECT $1,$2::uuid,tc.id,ts.id,q.quantity FROM color_size_quantities q JOIN work_order_colors sc ON sc.id=q.color_id JOIN work_order_sizes ss ON ss.id=q.size_id JOIN work_order_colors tc ON tc.company_id=$1 AND tc.revision_id=$2::uuid AND tc.color_code=sc.color_code JOIN work_order_sizes ts ON ts.company_id=$1 AND ts.revision_id=$2::uuid AND ts.size_code=ss.size_code WHERE q.company_id=$1 AND q.revision_id=$3::uuid`, [input.scope.companyId, input.targetRevisionId, source.revision_id]); statementCount += 1;
    const sourceSpec = (await client.query<DbQueryResultRow & { readonly id: string }>(`SELECT id FROM work_order_size_specs WHERE company_id=$1 AND revision_id=$2::uuid`, [input.scope.companyId, source.revision_id])).rows[0]; statementCount += 1;
    if (sourceSpec) { await client.query(`INSERT INTO work_order_size_specs(id,company_id,revision_id,gender_code,category_code,measurement_unit,source_template_id,source_template_version) SELECT $3::uuid,$1,$2::uuid,gender_code,category_code,measurement_unit,source_template_id,source_template_version FROM work_order_size_specs WHERE company_id=$1 AND id=$4::uuid`, [input.scope.companyId, input.targetRevisionId, input.targetSizeSpecId, sourceSpec.id]); statementCount += 1; await client.query(`INSERT INTO work_order_size_spec_sizes(id,company_id,revision_id,size_spec_id,size_code,display_label,display_order) SELECT gen_random_uuid(),$1,$2::uuid,$3::uuid,size_code,display_label,display_order FROM work_order_size_spec_sizes WHERE company_id=$1 AND size_spec_id=$4::uuid`, [input.scope.companyId, input.targetRevisionId, input.targetSizeSpecId, sourceSpec.id]); statementCount += 1; await client.query(`INSERT INTO work_order_size_spec_poms(id,company_id,revision_id,size_spec_id,pom_code,display_name,measurement_type,instruction,display_order) SELECT gen_random_uuid(),$1,$2::uuid,$3::uuid,pom_code,display_name,measurement_type,instruction,display_order FROM work_order_size_spec_poms WHERE company_id=$1 AND size_spec_id=$4::uuid`, [input.scope.companyId, input.targetRevisionId, input.targetSizeSpecId, sourceSpec.id]); statementCount += 1; await client.query(`INSERT INTO work_order_size_spec_values(company_id,revision_id,size_spec_id,size_row_id,pom_column_id,decimal_value,display_fraction) SELECT $1,$2::uuid,$3::uuid,ts.id,tp.id,v.decimal_value,v.display_fraction FROM work_order_size_spec_values v JOIN work_order_size_spec_sizes ss ON ss.id=v.size_row_id JOIN work_order_size_spec_poms sp ON sp.id=v.pom_column_id JOIN work_order_size_spec_sizes ts ON ts.company_id=$1 AND ts.size_spec_id=$3::uuid AND ts.size_code=ss.size_code JOIN work_order_size_spec_poms tp ON tp.company_id=$1 AND tp.size_spec_id=$3::uuid AND tp.pom_code=sp.pom_code WHERE v.company_id=$1 AND v.size_spec_id=$4::uuid`, [input.scope.companyId, input.targetRevisionId, input.targetSizeSpecId, sourceSpec.id]); statementCount += 1; }
    await client.query(`INSERT INTO work_order_material_lines(id,company_id,revision_id,material_id,material_type,name,color_option,supplier_partner_id,required_quantity,allowance_quantity,inventory_usage_quantity,order_quantity,unit_code,unit_price,amount,overage_disposition,status,memo,display_order,image_id,entity_version,usage_area,supplier_name_snapshot) SELECT gen_random_uuid(),$1,$2::uuid,material_id,material_type,name,color_option,supplier_partner_id,required_quantity,allowance_quantity,inventory_usage_quantity,order_quantity,unit_code,unit_price,amount,overage_disposition,'editing',memo,display_order,NULL,1,usage_area,supplier_name_snapshot FROM work_order_material_lines WHERE company_id=$1 AND revision_id=$3::uuid AND archived_at IS NULL`, [input.scope.companyId, input.targetRevisionId, source.revision_id]); statementCount += 1;
    await client.query(`INSERT INTO work_order_processes(id,company_id,revision_id,process_type_code,process_name_snapshot,partner_id,partner_name_snapshot,quantity,due_date,unit_code,unit_price,amount,memo,status,display_order,entity_version,application_area,application_color_target) SELECT gen_random_uuid(),$1,$2::uuid,process_type_code,process_name_snapshot,partner_id,partner_name_snapshot,quantity,due_date,unit_code,unit_price,amount,memo,'ready',display_order,1,application_area,application_color_target FROM work_order_processes WHERE company_id=$1 AND revision_id=$3::uuid`, [input.scope.companyId, input.targetRevisionId, source.revision_id]); statementCount += 1;
    for (const image of input.assets.images) { await client.query(`INSERT INTO work_order_images(id,company_id,work_order_id,storage_object_key,thumbnail_object_key,original_filename,mime_type,size_bytes,content_sha256,title,display_order,is_current_representative,created_by_member_id) SELECT $4::uuid,$1,$2::uuid,$5,$6,original_filename,mime_type,size_bytes,content_sha256,title,display_order,$7,$8 FROM work_order_images WHERE company_id=$1 AND work_order_id=$3::uuid AND id=$9::uuid AND deleted_at IS NULL`, [input.scope.companyId,input.targetWorkOrderId,input.sourceWorkOrderId,image.targetImageId,image.storageObjectKey,image.thumbnailObjectKey,image.isRepresentative,input.scope.companyMemberId,image.sourceImageId]); statementCount += 1; await client.query(`INSERT INTO work_order_revision_images(company_id,revision_id,image_id,display_order,is_representative,output_include,filename_snapshot,mime_type_snapshot,storage_object_key_snapshot) SELECT $1,$2::uuid,$3::uuid,display_order,$7,$8,filename_snapshot,mime_type_snapshot,$4 FROM work_order_revision_images WHERE company_id=$1 AND revision_id=$5::uuid AND image_id=$6::uuid`, [input.scope.companyId,input.targetRevisionId,image.targetImageId,image.storageObjectKey,source.revision_id,image.sourceImageId,image.isRepresentative,image.outputInclude]); statementCount += 1; }
    for (const attachment of input.assets.attachments) { await client.query(`INSERT INTO work_order_attachments(id,company_id,work_order_id,attachment_kind,storage_object_key,original_filename,mime_type,size_bytes,content_sha256,output_include_default,created_by_member_id) SELECT $4::uuid,$1,$2::uuid,attachment_kind,$5,original_filename,mime_type,size_bytes,content_sha256,$8,$6 FROM work_order_attachments WHERE company_id=$1 AND work_order_id=$3::uuid AND id=$7::uuid AND deleted_at IS NULL`, [input.scope.companyId,input.targetWorkOrderId,input.sourceWorkOrderId,attachment.targetAttachmentId,attachment.storageObjectKey,input.scope.companyMemberId,attachment.sourceAttachmentId,attachment.outputInclude]); statementCount += 1; await client.query(`INSERT INTO work_order_revision_attachments(company_id,revision_id,attachment_id,display_order,output_include,filename_snapshot,mime_type_snapshot,storage_object_key_snapshot) SELECT $1,$2::uuid,$3::uuid,display_order,$7,filename_snapshot,mime_type_snapshot,$4 FROM work_order_revision_attachments WHERE company_id=$1 AND revision_id=$5::uuid AND attachment_id=$6::uuid`, [input.scope.companyId,input.targetRevisionId,attachment.targetAttachmentId,attachment.storageObjectKey,source.revision_id,attachment.sourceAttachmentId,attachment.outputInclude]); statementCount += 1; }
    await client.query(`UPDATE work_orders SET current_revision_id=$3::uuid,representative_image_id=$4::uuid,updated_at=now() WHERE company_id=$1 AND id=$2::uuid`, [input.scope.companyId,input.targetWorkOrderId,input.targetRevisionId,input.assets.image?.targetImageId??null]); statementCount += 1;
    await client.query(`INSERT INTO domain_events(company_id,entity_type,entity_id,command_code,actor_member_id,correlation_id,change_summary,metadata,schema_version) VALUES($1,'work_order',$2,$3,$4,$5,'독립 작업지시서 초안 복사',$6::jsonb,1)`, [input.scope.companyId,input.targetWorkOrderId,WORK_ORDER_COPY_CREATE_COMMAND_CODE,input.scope.companyMemberId,input.scope.correlationId,JSON.stringify({clientRequestId:input.clientRequestId,sourceWorkOrderId:input.sourceWorkOrderId,lineageCopied:false})]); statementCount += 1;
    await client.query(`UPDATE work_order_command_receipts SET work_order_id=$4::uuid,result_revision_id=$5::uuid,result_entity_version=1 WHERE company_id=$1 AND command_code=$2 AND idempotency_key=$3`, [input.scope.companyId,WORK_ORDER_COPY_CREATE_COMMAND_CODE,input.keyHash,input.targetWorkOrderId,input.targetRevisionId]); statementCount += 1;
    const row=(await client.query<ResultRow>(RESULT_SQL,[input.scope.companyId,input.targetWorkOrderId,input.targetRevisionId])).rows[0]; statementCount += 1; if(!row)throw new Error("COPY_RESULT_MISSING"); return {row,replay:false};
  });
  return { result: map(value.row), nextVersion: 1 as EntityVersion, idempotentReplay: value.replay, statementCount, transactionCount: 1 as const, dbMs: Number((performance.now()-started).toFixed(2)) };
}
