import "server-only";

import { performance } from "perf_hooks";
import type { CompanyMemberId, EntityVersion, ProcessId, ProcessPatch, TenantMemberScope, WorkOrderId } from "@/lib/domain/work-orders/contracts";
import { withWaflV2TenantWriteTransaction, type DbQueryResultRow } from "@/lib/db/client";
import { installTenantClaims } from "@/lib/domain/work-orders/command/commandRepository";

export type ProcessFailure = "not_found" | "conflict" | "locked" | "revision_mismatch";
export class ProcessCommandRepositoryError extends Error { constructor(readonly reason: ProcessFailure, readonly entityVersion: number | null = null) { super(reason); } }
const own = (value: object, key: string) => Object.prototype.hasOwnProperty.call(value, key);

export async function patchProcessV2(input: { readonly scope: TenantMemberScope; readonly assignedCompanyMemberId: CompanyMemberId | null; readonly workOrderId: WorkOrderId; readonly processId: ProcessId; readonly expectedVersion: EntityVersion; readonly clientRequestId: string; readonly patch: ProcessPatch }) {
  const started = performance.now(); let statementCount = 0;
  const data = await withWaflV2TenantWriteTransaction(async (client) => {
    await installTenantClaims(client, input.scope); statementCount += 1;
    const selected = await client.query<DbQueryResultRow>(`SELECT w.id work_order_id,w.status work_order_status,w.entity_version work_order_version,r.id revision_id,r.revision_no,r.revision_status,p.id process_id,p.entity_version process_version,p.process_name_snapshot,p.partner_id,p.quantity,p.due_date,p.unit_code,p.unit_price,p.memo,p.application_area,p.application_color_target FROM work_orders w JOIN work_order_revisions r ON r.company_id=w.company_id AND r.id=w.current_revision_id JOIN work_order_processes p ON p.company_id=w.company_id AND p.revision_id=r.id WHERE w.company_id=$1 AND w.id=$2::uuid AND p.id=$3::uuid AND w.deleted_at IS NULL AND ($4::text IS NULL OR w.assignee_member_id=$4) FOR UPDATE OF w,r,p`, [input.scope.companyId,input.workOrderId,input.processId,input.assignedCompanyMemberId]); statementCount += 1;
    const row=selected.rows[0]; if(!row) throw new ProcessCommandRepositoryError("not_found"); const version=Number(row.work_order_version);
    if(version!==input.expectedVersion) throw new ProcessCommandRepositoryError("conflict",version);
    if(row.work_order_status!=="draft") throw new ProcessCommandRepositoryError("locked",version);
    if(row.revision_status!=="draft") throw new ProcessCommandRepositoryError("revision_mismatch",version);
    const p=input.patch; const changed=["processName","partnerId","quantity","dueDate","unitCode","unitPrice","memo","applicationArea","applicationColorTarget"].filter((field)=>own(p,field));
    if(changed.length===0) return { workOrderId:input.workOrderId,revisionId:String(row.revision_id),processId:input.processId,nextVersion:version,lineVersion:Number(row.process_version),changedFields:changed };
    const updated=await client.query<DbQueryResultRow>(`UPDATE work_order_processes SET process_name_snapshot=CASE WHEN $4 THEN $5 ELSE process_name_snapshot END,partner_id=CASE WHEN $6 THEN $7 ELSE partner_id END,quantity=CASE WHEN $8 THEN $9::numeric ELSE quantity END,due_date=CASE WHEN $10 THEN $11::date ELSE due_date END,unit_code=CASE WHEN $12 THEN $13 ELSE unit_code END,unit_price=CASE WHEN $14 THEN $15::numeric ELSE unit_price END,amount=round((CASE WHEN $8 THEN $9::numeric ELSE quantity END)*(CASE WHEN $14 THEN $15::numeric ELSE unit_price END),2),memo=CASE WHEN $16 THEN $17 ELSE memo END,application_area=CASE WHEN $18 THEN $19 ELSE application_area END,application_color_target=CASE WHEN $20 THEN $21 ELSE application_color_target END,entity_version=entity_version+1,updated_at=now() WHERE company_id=$1 AND id=$2::uuid AND revision_id=$3::uuid AND entity_version=$22 RETURNING entity_version`,[input.scope.companyId,input.processId,row.revision_id,own(p,"processName"),p.processName??null,own(p,"partnerId"),p.partnerId??null,own(p,"quantity"),p.quantity??null,own(p,"dueDate"),p.dueDate??null,own(p,"unitCode"),p.unitCode??null,own(p,"unitPrice"),p.unitPrice??null,own(p,"memo"),p.memo??null,own(p,"applicationArea"),p.applicationArea??null,own(p,"applicationColorTarget"),p.applicationColorTarget??null,row.process_version]); statementCount+=1; if(!updated.rows[0]) throw new ProcessCommandRepositoryError("conflict",version);
    const parent=await client.query<DbQueryResultRow>(`WITH totals AS (SELECT COALESCE(sum(amount),0)::numeric(14,2) total FROM work_order_processes WHERE company_id=$1 AND revision_id=$4::uuid),wo AS (UPDATE work_orders SET entity_version=entity_version+1,updated_at=now() WHERE company_id=$1 AND id=$2::uuid AND entity_version=$3 AND status='draft' RETURNING entity_version),rev AS (UPDATE work_order_revisions r SET entity_version=entity_version+1,process_total=t.total,estimated_total=r.fabric_total+r.accessory_total+t.total,updated_at=now() FROM totals t WHERE r.company_id=$1 AND r.id=$4::uuid AND r.revision_status='draft' RETURNING r.id) SELECT entity_version FROM wo WHERE EXISTS(SELECT 1 FROM rev)`,[input.scope.companyId,input.workOrderId,input.expectedVersion,row.revision_id]); statementCount+=1; const next=Number(parent.rows[0]?.entity_version); if(!next) throw new ProcessCommandRepositoryError("conflict",version);
    await client.query(`INSERT INTO domain_events(company_id,entity_type,entity_id,command_code,actor_member_id,correlation_id,change_summary,metadata,schema_version) VALUES($1,'work_order',$2,'work_order.process.patch',$3,$4,'제작 공정 수정',$5::jsonb,1)`,[input.scope.companyId,input.workOrderId,input.scope.companyMemberId,input.scope.correlationId,JSON.stringify({processId:input.processId,revisionId:row.revision_id,clientRequestId:input.clientRequestId,changedFields:changed,versionTransition:{from:version,to:next}})]); statementCount+=1;
    return {workOrderId:input.workOrderId,revisionId:String(row.revision_id),processId:input.processId,nextVersion:next,lineVersion:Number(updated.rows[0].entity_version),changedFields:changed};
  });
  return {data,statementCount,transactionCount:1 as const,dbMs:Number((performance.now()-started).toFixed(2))};
}
