import type { MaterialKind, MaterialMockItem, MaterialSummaryItem } from "@/lib/materials/types";

export const MATERIAL_SUMMARY_ITEMS: MaterialSummaryItem[] = [
  {
    label: "원단 기준",
    value: "4",
    description: "작업지시서 연결 전 원단 기본 정보를 검토합니다.",
  },
  {
    label: "부자재 기준",
    value: "4",
    description: "부속, 라벨, 포장재 등 생산 구성 후보를 분리합니다.",
  },
  {
    label: "DB 연결",
    value: "대기",
    description: "0.16.18에서 companyId 기준 repository/API 연결 예정입니다.",
  },
];

export const MATERIAL_MOCK_ITEMS: MaterialMockItem[] = [
  {
    id: "fabric-cotton-twill",
    kind: "fabric",
    name: "코튼 트윌",
    code: "FAB-CT-001",
    category: "면직물",
    supplierName: "거래처 연결 예정",
    unit: "yd",
    stockLabel: "샘플 기준",
    statusLabel: "목업",
    memo: "셔츠, 팬츠류 기본 원단 후보입니다.",
  },
  {
    id: "fabric-poly-span",
    kind: "fabric",
    name: "폴리 스판",
    code: "FAB-PS-002",
    category: "합섬",
    supplierName: "거래처 연결 예정",
    unit: "yd",
    stockLabel: "샘플 기준",
    statusLabel: "목업",
    memo: "활동성이 필요한 제품군의 후보입니다.",
  },
  {
    id: "fabric-linen-blend",
    kind: "fabric",
    name: "린넨 혼방",
    code: "FAB-LB-003",
    category: "마/혼방",
    supplierName: "거래처 연결 예정",
    unit: "yd",
    stockLabel: "샘플 기준",
    statusLabel: "목업",
    memo: "여름 제품군의 질감 확인용 후보입니다.",
  },
  {
    id: "fabric-nylon-ripstop",
    kind: "fabric",
    name: "나일론 립스탑",
    code: "FAB-NR-004",
    category: "기능성",
    supplierName: "거래처 연결 예정",
    unit: "yd",
    stockLabel: "샘플 기준",
    statusLabel: "목업",
    memo: "가방, 아우터류 테스트 후보입니다.",
  },
  {
    id: "submaterial-button-basic",
    kind: "submaterial",
    name: "기본 단추",
    code: "SUB-BT-001",
    category: "단추",
    supplierName: "거래처 연결 예정",
    unit: "개",
    stockLabel: "샘플 기준",
    statusLabel: "목업",
    memo: "셔츠, 자켓 공통 사용 후보입니다.",
  },
  {
    id: "submaterial-zipper-metal",
    kind: "submaterial",
    name: "금속 지퍼",
    code: "SUB-ZP-002",
    category: "지퍼",
    supplierName: "거래처 연결 예정",
    unit: "개",
    stockLabel: "샘플 기준",
    statusLabel: "목업",
    memo: "팬츠, 아우터류 연결 후보입니다.",
  },
  {
    id: "submaterial-care-label",
    kind: "submaterial",
    name: "케어라벨",
    code: "SUB-LB-003",
    category: "라벨",
    supplierName: "거래처 연결 예정",
    unit: "장",
    stockLabel: "샘플 기준",
    statusLabel: "목업",
    memo: "브랜드/혼용률 표기 연결 전 기준입니다.",
  },
  {
    id: "submaterial-polybag",
    kind: "submaterial",
    name: "폴리백",
    code: "SUB-PK-004",
    category: "포장재",
    supplierName: "거래처 연결 예정",
    unit: "장",
    stockLabel: "샘플 기준",
    statusLabel: "목업",
    memo: "출고 포장 구성 연결 후보입니다.",
  },
];
