import "server-only";

import { randomUUID } from "crypto";
import { createWaflApiSuccess } from "@/lib/api/waflApiServer";
import { startWaflRouteTiming } from "@/lib/api/waflPerformanceTiming";
import { requireWorkspaceApiGuard } from "@/lib/auth/apiRouteGuards";
import { createCommandErrorResponse, mapCommandGuardFailureStatus, readBoundedCommandJson } from "@/lib/domain/work-orders/command/commandRoute";
import { WorkOrderCommandRequestError } from "@/lib/domain/work-orders/command/commandService";
import { getWorkOrderV2MeasurementMutationRuntimeGuard } from "@/lib/domain/work-orders/command/runtimeGuard";
import { runMeasurementCommand } from "@/lib/domain/work-orders/measurement/measurementCommandService";
import type { MeasurementCommandKind } from "@/lib/domain/work-orders/measurement/measurementCommandRepository";
import type { CorrelationId } from "@/lib/domain/work-orders/contracts";

const KINDS: readonly MeasurementCommandKind[]=["apply-template","set-unit","set-cell","set-cells","add-pom","rename-pom","remove-pom","reorder-poms","set-pom-selection","save-company-template","update-company-template"];
export async function handleMeasurementCommand(request:Request,workOrderId:string) { const correlationId=randomUUID() as CorrelationId;const timing=startWaflRouteTiming(); if(!getWorkOrderV2MeasurementMutationRuntimeGuard().ok)return createCommandErrorResponse({code:"FORBIDDEN",message:"승인된 dev/test Runtime에서만 완성 스펙을 변경할 수 있습니다.",status:403,correlationId}); const guard=await requireWorkspaceApiGuard({permissionCode:"workorder.update"});timing.markGuardComplete();if(!guard.ok)return createCommandErrorResponse({...mapCommandGuardFailureStatus(guard.response.status),correlationId});try {const raw=await readBoundedCommandJson(request);if(!raw||typeof raw!=="object"||Array.isArray(raw))return createCommandErrorResponse({code:"VALIDATION_ERROR",message:"완성 스펙 변경 요청을 확인해 주세요.",status:400,correlationId});const body=raw as Record<string,unknown>;const kind=body.kind;if(typeof kind!=="string"||!KINDS.includes(kind as MeasurementCommandKind))return createCommandErrorResponse({code:"VALIDATION_ERROR",message:"지원하지 않는 완성 스펙 변경 요청입니다.",status:400,correlationId});const result=await runMeasurementCommand({workOrderId,kind:kind as MeasurementCommandKind,body,idempotencyKey:request.headers.get("Idempotency-Key"),scope:guard.scope,companyMemberId:guard.session.companyMemberId,correlationId});return createWaflApiSuccess({result:{workOrderId:result.workOrderId,revisionId:result.revisionId,nextVersion:result.nextVersion,changedFields:result.changedFields},nextVersion:result.nextVersion},{status:result.idempotentReplay?200:201,headers:{"Cache-Control":"no-store","X-WAFL-Correlation-Id":correlationId,"X-WAFL-Command-Statement-Count":String(result.statementCount),"X-WAFL-Command-Transaction-Count":String(result.transactionCount),"X-WAFL-Command-DB-Ms":String(result.dbMs),"X-WAFL-Idempotent-Replay":result.idempotentReplay?"1":"0",...timing.headers(result.dbMs)}});}catch(error){if(error instanceof WorkOrderCommandRequestError)return createCommandErrorResponse({code:error.code,message:error.message,status:error.status,correlationId,fieldErrors:error.fieldErrors,entityVersion:error.entityVersion});const db=error&&typeof error==="object"?error as {code?:unknown;table?:unknown;column?:unknown;constraint?:unknown;detail?:unknown;hint?:unknown;message?:unknown}:null;const safe=(value:unknown)=>typeof value==="string"?value.replace(/[\r\n\t]+/g," ").slice(0,240):undefined;console.error("[WORK_ORDER_V2_MEASUREMENT_COMMAND_FAILED]",{correlationId,errorName:error instanceof Error?error.name:"Unknown",sqlState:safe(db?.code),table:safe(db?.table),column:safe(db?.column),constraint:safe(db?.constraint),message:safe(db?.message),detail:safe(db?.detail),hint:safe(db?.hint)});return createCommandErrorResponse({code:"INTERNAL_ERROR",message:"완성 스펙 변경을 처리하지 못했습니다.",status:500,correlationId,retryable:true});}}
