export const WAFL_THEME = {
  color: {
    paper: "#fffdf8",
    paperMuted: "#f3eee4",
    deepNavy: "#17263d",
    navyInk: "#23375a",
    brickOrange: "#9b4a27",
    fabricBeige: "#f7f0e5",
    olive: "#667052",
    border: "#dfd5c8",
    disabled: "#8f857b",
    readOnly: "#75695d",
    editActive: "#8b5e3c",
    error: "#a13933",
    focus: "#23375a",
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32 },
  layout: {
    screenGutterPhone: 16,
    screenGutterTablet: 24,
    cardPadding: 12,
    compactCardPadding: 8,
    sectionGap: 12,
    sectionGapLarge: 16,
    controlGap: 8,
    actionTileGap: 6,
    tightGap: 4,
    actionTileMinWidth: 72,
    actionTilePreferredWidth: 88,
    actionTileMaxWidth: 112,
    metricGridGap: 8,
    metricGridMinColumnWidth: 136,
    metricGridMinimumColumns: 2,
    metricGridMaximumColumns: 4,
    metricCellMinHeight: 64,
    metricValueSurfaceMinHeight: 30,
    metricValueSurfaceInset: 8,
    tabBodyTopInset: 12,
    definitionRowInset: 9,
    contentSummaryVisibleLimit: 6,
    frozenTableVisibleRowLimit: 5,
    frozenTableLabelWidth: 116,
    frozenTableCellWidth: 82,
    frozenTableEditableValueWidth: 60,
    frozenTableEditableValueHeight: 34,
    frozenTableRowHeight: 44,
    frozenTableFullBodyMaxHeight: 440,
    sheetMaxWidth: 520,
  },
  radius: {
    field: 10,
    actionTile: 10,
    card: 10,
    cardMajor: 14,
    cardCompact: 10,
    sheet: 18,
    pill: 999,
  },
  touch: {
    minimum: 44,
    actionTileMinHeight: 54,
    inlineControlMinHeight: 44,
    tabRailMinHeight: 48,
  },
  sheet: {
      mediumDetentRatio: 0.68,
      expandedDetentRatio: 0.94,
      fullViewDetentRatio: 0.97,
      contentFitMinHeight: 220,
      contentFitMaxRatio: 0.72,
      dismissDistance: 96,
      dismissVelocity: 1.15,
      flickVelocity: 0.45,
      velocityProjectionMs: 72,
      maxVelocityProjection: 88,
      dragZoneMinHeight: 44,
      dragHandleHeight: 4,
      dragHandleWidth: 42,
      bodyEndGap: 12,
      focusRevealGap: 12,
      focusRevealContext: 56,
      numericFocusRevealContext: 112,
      initialBodyViewportMinHeight: 120,
      entranceDurationMs: 260,
      exitDurationMs: 200,
    },
  icon: { small: 18, standard: 20, large: 24 },
  border: { hairline: 1, active: 2 },
  badge: {
    fabric: { background: "#f7f0e5", border: "#cfa789", foreground: "#7b452d" },
    accessory: { background: "#edf0e8", border: "#aab395", foreground: "#4d583c" },
  },
  typography: {
    caption: 10,
    body: 13,
    title: 17,
    productTitle: { fontSize: 20, lineHeight: 26 },
    productTitleCompact: { fontSize: 18, lineHeight: 24 },
    sectionTitle: { fontSize: 15, lineHeight: 20 },
    cardTitle: { fontSize: 13, lineHeight: 18 },
    bodyStrong: { fontSize: 13, lineHeight: 18 },
    bodyText: { fontSize: 12, lineHeight: 18 },
    fieldLabel: { fontSize: 11, lineHeight: 16 },
    meta: { fontSize: 10, lineHeight: 15 },
    actionLabel: { fontSize: 10, lineHeight: 14 },
    badge: { fontSize: 9, lineHeight: 13 },
    textInput: { fontSize: 16, lineHeight: 20 },
  },
} as const;
