import {
  WAFL_LIST_CLEAR_BUTTON_CLASS,
  WAFL_LIST_SEARCH_INPUT_CLASS,
  WAFL_LIST_SEARCH_ROW_CLASS,
  WAFL_LIST_SELECT_TRIGGER_CLASS,
} from "@/components/common/ui/waflListControlSet";
import { WAFL_WORKSPACE_SECTION_CARD_CLASS, WAFL_WORKSPACE_SECTION_GAP_CLASS } from "@/components/common/ui";

export const MATERIAL_ORDER_PANEL_LIST_CLASS =
  "flex min-h-0 flex-col space-y-3";

export const MATERIAL_ORDER_PANEL_FILTER_FIELD_CLASS =
  WAFL_LIST_SEARCH_INPUT_CLASS;

export const MATERIAL_ORDER_LIST_SEARCH_ROW_CLASS = WAFL_LIST_SEARCH_ROW_CLASS;

export const MATERIAL_ORDER_LIST_SELECT_TRIGGER_CLASS =
  WAFL_LIST_SELECT_TRIGGER_CLASS;

export const MATERIAL_ORDER_LIST_CLEAR_BUTTON_CLASS =
  WAFL_LIST_CLEAR_BUTTON_CLASS;

export const MATERIAL_ORDER_SECTION_GAP_CLASS = WAFL_WORKSPACE_SECTION_GAP_CLASS;

export const MATERIAL_ORDER_SECTION_CARD_CLASS = WAFL_WORKSPACE_SECTION_CARD_CLASS;

export const MATERIAL_ORDER_LIST_CARD_BASE_CLASS = "group w-full";

export const MATERIAL_ORDER_LIST_CARD_DEFAULT_CLASS = "pbp-workorder-list-card";

export const MATERIAL_ORDER_NESTED_ROW_CLASS =
  "grid grid-cols-[minmax(0,1fr)_auto] items-center gap-2 px-3 py-2.5";
