import { APP_VERSION } from "@/lib/constants/app";
import {
  applySidePanelPreviewHandler,
  buildDetailProps,
  buildMobileDrawerProps,
  buildMobileTopBarProps,
  buildModalProps,
  buildSidebarListProps,
  buildSidePanelProps,
} from "@/lib/workorder/workspace/workspaceViewModelBuilders";
import type {
  BuildWorkspaceViewModelArgs,
  WorkspaceViewModel,
} from "@/lib/workorder/workspace/viewModelTypes";

export function buildWorkspaceViewModel(
  args: BuildWorkspaceViewModelArgs,
): WorkspaceViewModel {
  const version = APP_VERSION;
  const companyName = args.companyName ?? "";
  const isWorkspaceWriteLocked = Boolean(
    args.isWorkspaceWriteLocked || args.workflowProcessingLabel,
  );
  const processingFormat = args.i18n.workorder.ui.actionSection.processingFormat;
  const workspaceWriteLockMessage =
    args.workspaceWriteLockMessage ??
    (args.workflowProcessingLabel
      ? processingFormat.replace("{label}", args.workflowProcessingLabel.replace(/\s+/g, ""))
      : undefined);

  const sidebarListProps = buildSidebarListProps({
    companyName,
    version,
    currentUser: args.currentUser,
    workOrders: args.workOrders,
    selectedId: args.selectedId,
    workflowStateById: args.workflowStateById,
    canDeleteWorkOrder: args.canDeleteWorkOrder,
    canCreateWorkOrder: args.canCreateWorkOrder,
    searchQuery: args.searchQuery,
    listStatusFilter: args.listStatusFilter,
    listSort: args.listSort,
    onSelectWorkOrder: args.onSelectWorkOrder,
    onSetCreateWorkOrderModalOpen: args.onSetCreateWorkOrderModalOpen,
    onSetPermissionModalOpen: args.onSetPermissionModalOpen,
    onReorderWorkOrder: args.onReorderWorkOrder,
    onDeleteWorkOrder: args.onDeleteWorkOrder,
    onReworkWorkOrder: args.onReworkWorkOrder,
    onSetSearchQuery: args.onSetSearchQuery,
    onSetListStatusFilter: args.onSetListStatusFilter,
    onSetListSort: args.onSetListSort,
    onResetListControls: args.onResetListControls,
    dbConnectionStatus: args.dbConnectionStatus,
    showRepositoryBadges: args.showRepositoryBadges,
    showUserSwitchingTools: args.showUserSwitchingTools,
    writeLocked: isWorkspaceWriteLocked,
    writeLockMessage: workspaceWriteLockMessage,
  });

  const detailProps = buildDetailProps({
    version,
    i18n: args.i18n,
    currentUser: args.currentUser,
    users: args.users,
    currentRole: args.currentRole,
    selectedWorkOrder: args.selectedWorkOrder,
    hasVisibleWorkOrders: args.hasVisibleWorkOrders,
    currentWorkflowState: args.currentWorkflowState,
    canCreateWorkOrder: args.canCreateWorkOrder,
    canSeeAttachments: args.canSeeAttachments,
    canUploadOfficialAttachments: args.canUploadOfficialAttachments,
    canEditMemo: args.canEditMemo,
    canRenameTitle: args.canRenameTitle,
    canEditSideDraftContent: args.canEditSideDraftContent,
    isAdmin: args.isAdmin,
    isReviewRequestLocked: args.isReviewRequestLocked,
    canChangeManager: args.canChangeManager,
    canSeeProductionSections: args.canSeeProductionSections,
    canSeeCostSections: args.canSeeCostSections,
    canOpenInventoryEditor: args.canOpenInventoryEditor,
    currentDisplayStage: args.currentDisplayStage,
    currentInventoryQuantity: args.currentInventoryQuantity,
    designAttachments: args.designAttachments,
    officialAttachments: args.officialAttachments,
    selectedAttachment: args.selectedAttachment,
    fabricTotal: args.fabricTotal,
    subsidiaryTotal: args.subsidiaryTotal,
    outsourcingTotal: args.outsourcingTotal,
    totalCost: args.totalCost,
    unitCost: args.unitCost,
    saveStatus: args.saveStatus,
    lastSavedAt: args.lastSavedAt,
    availableActions: args.availableActions,
    visibleStages: args.visibleStages,
    workflowProcessingLabel: args.workflowProcessingLabel,
    isWorkspaceWriteLocked,
    workspaceWriteLockMessage,
    getAttachmentPermissions: args.getAttachmentPermissions,
    onSave: args.onSave,
    onWorkflowAction: args.onWorkflowAction,
    onUpdateSelectedWorkOrder: args.onUpdateSelectedWorkOrder,
    onRenameWorkOrderTitle: args.onRenameWorkOrderTitle,
    onCompleteInspection: args.onCompleteInspection,
    onOpenManagerAssignModal: args.onOpenManagerAssignModal,
    onOpenAttachmentPicker: args.onOpenAttachmentPicker,
    onUploadAttachmentFiles: args.onUploadAttachmentFiles,
    onRequestDeleteAttachment: args.onRequestDeleteAttachment,
    onSetPrimaryDesignAttachment: args.onSetPrimaryDesignAttachment,
    onCreateMemoThread: args.onCreateMemoThread,
    onCreateMemoReply: args.onCreateMemoReply,
    onUpdateMemoThread: args.onUpdateMemoThread,
    onDeleteMemoThread: args.onDeleteMemoThread,
    onUpdateMemoReply: args.onUpdateMemoReply,
    onDeleteMemoReply: args.onDeleteMemoReply,
    basicInfoOpen: args.basicInfoOpen,
    materialOpen: args.materialOpen,
    outsourcingOpen: args.outsourcingOpen,
    onSetBasicInfoOpen: args.onSetBasicInfoOpen,
    onSetMaterialOpen: args.onSetMaterialOpen,
    onSetOutsourcingOpen: args.onSetOutsourcingOpen,
    onSetInventoryEditorOpen: args.onSetInventoryEditorOpen,
  });

  const sidePanelProps = applySidePanelPreviewHandler(
    buildSidePanelProps({
      version,
      currentUser: args.currentUser,
      users: args.users,
      currentRole: args.currentRole,
      selectedWorkOrder: args.selectedWorkOrder,
      hasVisibleWorkOrders: args.hasVisibleWorkOrders,
      currentWorkflowState: args.currentWorkflowState,
      canCreateWorkOrder: args.canCreateWorkOrder,
      canSeeAttachments: args.canSeeAttachments,
      canUploadOfficialAttachments: args.canUploadOfficialAttachments,
      canEditMemo: args.canEditMemo,
      canRenameTitle: args.canRenameTitle,
      canEditSideDraftContent: args.canEditSideDraftContent,
      isAdmin: args.isAdmin,
      isReviewRequestLocked: args.isReviewRequestLocked,
      canChangeManager: args.canChangeManager,
      canSeeProductionSections: args.canSeeProductionSections,
      canSeeCostSections: args.canSeeCostSections,
      canOpenInventoryEditor: args.canOpenInventoryEditor,
      currentDisplayStage: args.currentDisplayStage,
      currentInventoryQuantity: args.currentInventoryQuantity,
      designAttachments: args.designAttachments,
      officialAttachments: args.officialAttachments,
      selectedAttachment: args.selectedAttachment,
      fabricTotal: args.fabricTotal,
      subsidiaryTotal: args.subsidiaryTotal,
      outsourcingTotal: args.outsourcingTotal,
      totalCost: args.totalCost,
      unitCost: args.unitCost,
      saveStatus: args.saveStatus,
      lastSavedAt: args.lastSavedAt,
      availableActions: args.availableActions,
      visibleStages: args.visibleStages,
      workflowProcessingLabel: args.workflowProcessingLabel,
      isWorkspaceWriteLocked,
      workspaceWriteLockMessage,
      getAttachmentPermissions: args.getAttachmentPermissions,
      i18n: args.i18n,
      onSave: args.onSave,
      onWorkflowAction: args.onWorkflowAction,
      onUpdateSelectedWorkOrder: args.onUpdateSelectedWorkOrder,
      onRenameWorkOrderTitle: args.onRenameWorkOrderTitle,
      onCompleteInspection: args.onCompleteInspection,
      onOpenManagerAssignModal: args.onOpenManagerAssignModal,
      onOpenAttachmentPicker: args.onOpenAttachmentPicker,
      onUploadAttachmentFiles: args.onUploadAttachmentFiles,
      onRequestDeleteAttachment: args.onRequestDeleteAttachment,
      onSetPrimaryDesignAttachment: args.onSetPrimaryDesignAttachment,
      onCreateMemoThread: args.onCreateMemoThread,
      onCreateMemoReply: args.onCreateMemoReply,
      onUpdateMemoThread: args.onUpdateMemoThread,
      onDeleteMemoThread: args.onDeleteMemoThread,
      onUpdateMemoReply: args.onUpdateMemoReply,
      onDeleteMemoReply: args.onDeleteMemoReply,
    }),
    args.onSetAttachmentPreviewId,
  );

  const modalProps = buildModalProps({
    i18n: args.i18n,
    isAdmin: args.isAdmin,
    inventoryEditorOpen: args.inventoryEditorOpen,
    permissionModalOpen: args.permissionModalOpen,
    createWorkOrderModalOpen: args.createWorkOrderModalOpen,
    managerAssignModalOpen: args.managerAssignModalOpen,
    inventoryLogModalOpen: args.inventoryLogModalOpen,
    orderRequestConfirmOpen: args.orderRequestConfirmOpen,
    workflowValidationModal: args.workflowValidationModal,
    rejectReviewReasonModal: args.rejectReviewReasonModal,
    users: args.users,
    currentUserId: args.currentUserId,
    permissionTargetUserId: args.permissionTargetUserId,
    historyFilter: args.historyFilter,
    currentRole: args.currentRole,
    selectedWorkOrder: args.selectedWorkOrder,
    currentInventoryQuantity: args.currentInventoryQuantity,
    filteredHistoryLogs: args.filteredHistoryLogs,
    inventoryLogs: args.inventoryLogs,
    selectedAttachment: args.selectedAttachment,
    pendingAttachmentDelete: args.pendingAttachmentDelete,
    getAttachmentPermissions: args.getAttachmentPermissions,
    onSetInventoryEditorOpen: args.onSetInventoryEditorOpen,
    onSetPermissionModalOpen: args.onSetPermissionModalOpen,
    onSetCreateWorkOrderModalOpen: args.onSetCreateWorkOrderModalOpen,
    onSetInventoryLogModalOpen: args.onSetInventoryLogModalOpen,
    onSetAttachmentPreviewId: args.onSetAttachmentPreviewId,
    onSetPermissionTargetUserId: args.onSetPermissionTargetUserId,
    onSetCurrentUserId: args.onSetCurrentUserId,
    showUserSwitchingTools: args.showUserSwitchingTools,
    onSetHistoryFilter: args.onSetHistoryFilter,
    onCreateWorkOrder: args.onCreateWorkOrder,
    onConfirmOrderRequest: args.onConfirmOrderRequest,
    onCloseOrderRequestConfirm: args.onCloseOrderRequestConfirm,
    onInventoryApply: args.onInventoryApply,
    onApplyRoles: args.onApplyRoles,
    onCloseManagerAssignModal: args.onCloseManagerAssignModal,
    onChangeManager: args.onChangeManager,
    onRequestDeleteAttachment: args.onRequestDeleteAttachment,
    onAttachmentDeleteConfirmClose: args.onAttachmentDeleteConfirmClose,
    onAttachmentDeleteConfirm: args.onAttachmentDeleteConfirm,
  });

  const mobileTopBarProps = buildMobileTopBarProps({
    companyName,
    version,
    onSetDrawerOpen: args.onSetDrawerOpen,
    onSetPermissionModalOpen: args.onSetPermissionModalOpen,
    dbConnectionStatus: args.dbConnectionStatus,
    showRepositoryBadges: args.showRepositoryBadges,
    showUserSwitchingTools: args.showUserSwitchingTools,
  });

  const mobileDrawerProps = buildMobileDrawerProps({
    drawerOpen: args.drawerOpen,
    sidebarListProps,
    onSetDrawerOpen: args.onSetDrawerOpen,
    onReorderWorkOrder: args.onReorderWorkOrder,
    onReworkWorkOrder: args.onReworkWorkOrder,
  });

  return {
    sidebarListProps,
    detailProps,
    sidePanelProps,
    modalProps,
    mobileTopBarProps,
    mobileDrawerProps,
  };
}
