import type { UploadableAttachmentScopeValue } from "@/lib/constants/workorderIdentity";
import type { ComponentProps } from "react";
import type { getI18n } from "@/lib/i18n";
import SidebarContent from "@/components/layout/SidebarContent";
import MobileDrawer from "@/components/layout/MobileDrawer";
import MobileTopBar from "@/components/layout/MobileTopBar";
import WorkOrderDetail from "@/components/workorder/WorkOrderDetail";
import WorkOrderOverlay from "@/components/workorder/WorkOrderOverlay";
import WorkOrderSidePanel from "@/components/workorder/WorkOrderSidePanel";
import type { AttachmentPermissionState } from "@/lib/workorder/attachments/attachmentPermissions";
import type { DbConnectionStatus } from "@/lib/repositories/dbConnectionStatusStore";
import type { Attachment, HistoryFilter, InventoryLog, RoleType, UserProfile, WorkOrder, WorkflowAction, WorkflowState } from "@/types/workorder";
import type { WorkOrderListSort, WorkOrderListStatusFilter } from "@/lib/workorder/list/workOrderListControls";

export type SidebarListProps = ComponentProps<typeof SidebarContent>;
export type DetailProps = ComponentProps<typeof WorkOrderDetail>;
export type SidePanelProps = ComponentProps<typeof WorkOrderSidePanel>;
export type MobileTopBarProps = Omit<ComponentProps<typeof MobileTopBar>, "homeNavigation">;
export type MobileDrawerProps = ComponentProps<typeof MobileDrawer>;
export type ModalProps = ComponentProps<typeof WorkOrderOverlay>["modalProps"];
export type GetAttachmentPermissions = (attachment: Attachment | null) => AttachmentPermissionState;

export type BuildWorkspaceViewModelArgs = {
  companyName?: string | null;
  drawerOpen: boolean;
  basicInfoOpen: boolean;
  materialOpen: boolean;
  outsourcingOpen: boolean;
  inventoryEditorOpen: boolean;
  permissionModalOpen: boolean;
  createWorkOrderModalOpen: boolean;
  managerAssignModalOpen: boolean;
  inventoryLogModalOpen: boolean;
  orderRequestConfirmOpen: boolean;
  users: UserProfile[];
  currentUserId: string;
  permissionTargetUserId: string;
  historyFilter: HistoryFilter;
  searchQuery: string;
  listStatusFilter: WorkOrderListStatusFilter;
  listSort: WorkOrderListSort;
  workOrders: SidebarListProps["workOrders"];
  hasVisibleWorkOrders: boolean;
  workflowStateById: Record<string, string>;
  selectedId: string;
  selectedWorkOrder: WorkOrder;
  currentWorkflowState: WorkflowState;
  currentUser: UserProfile;
  currentRole: RoleType;
  isAdmin: boolean;
  canCreateWorkOrder: boolean;
  canSeeAttachments: boolean;
  canUploadOfficialAttachments: boolean;
  canEditMemo: boolean;
  canRenameTitle: boolean;
  isReviewRequestLocked: boolean;
  canEditSideDraftContent: boolean;
  canChangeManager: boolean;
  canSeeProductionSections: boolean;
  canSeeCostSections: boolean;
  canOpenInventoryEditor: boolean;
  currentDisplayStage: DetailProps["currentDisplayStage"];
  currentInventoryQuantity: number;
  filteredHistoryLogs: ModalProps["inventoryLog"]["logs"];
  inventoryLogs: InventoryLog[];
  designAttachments: Attachment[];
  officialAttachments: Attachment[];
  selectedAttachment: Attachment | null;
  outsourcingTotal: number;
  fabricTotal: number;
  subsidiaryTotal: number;
  totalCost: number;
  unitCost: number;
  saveStatus: DetailProps["saveStatus"];
  lastSavedAt: string | null;
  availableActions: WorkflowAction[];
  visibleStages: DetailProps["visibleStages"];
  workflowProcessingLabel?: string | null;
  isWorkspaceWriteLocked?: boolean;
  workspaceWriteLockMessage?: string;
  pendingAttachmentDelete: Attachment | null;
  canDeleteWorkOrder: SidebarListProps["canDelete"];
  getAttachmentPermissions: GetAttachmentPermissions;
  i18n: ReturnType<typeof getI18n>;
  onSetDrawerOpen: (next: boolean) => void;
  onSetBasicInfoOpen: (updater: (prev: boolean) => boolean) => void;
  onSetMaterialOpen: (next: boolean | ((prev: boolean) => boolean)) => void;
  onSetOutsourcingOpen: (next: boolean | ((prev: boolean) => boolean)) => void;
  onSetInventoryEditorOpen: (next: boolean) => void;
  onSetPermissionModalOpen: (next: boolean) => void;
  onSetCreateWorkOrderModalOpen: (next: boolean) => void;
  onSetInventoryLogModalOpen: (next: boolean) => void;
  onSetAttachmentPreviewId: (next: string | null) => void;
  onSetPermissionTargetUserId: (next: string) => void;
  onSetCurrentUserId: (next: string) => void;
  onSetSearchQuery: (next: string) => void;
  onSetListStatusFilter: (next: WorkOrderListStatusFilter) => void;
  onSetListSort: (next: WorkOrderListSort) => void;
  onResetListControls: () => void;
  dbConnectionStatus?: DbConnectionStatus;
  showRepositoryBadges?: boolean;
  showUserSwitchingTools?: boolean;
  onSetHistoryFilter: (next: HistoryFilter) => void;
  onSave: () => void;
  onSelectWorkOrder: (id: string) => void;
  onCreateWorkOrder: ModalProps["createWorkOrder"]["onCreate"];
  onDeleteWorkOrder: (id: string) => void;
  onReorderWorkOrder: (id: string) => void;
  onReworkWorkOrder: (id: string) => void;
  onWorkflowAction: (action: WorkflowAction) => void;
  onUpdateSelectedWorkOrder: (patch: Partial<WorkOrder>) => void;
  onRenameWorkOrderTitle: (nextTitle: string) => void;
  onConfirmOrderRequest: (payload: { factoryName: string; quantity: number }) => void;
  onCloseOrderRequestConfirm: () => void;
  onInventoryApply: ModalProps["inventoryEditor"]["onApply"];
  onCompleteInspection: DetailProps["onCompleteInspection"];
  onApplyRoles: ModalProps["permission"]["onApplyRoles"];
  onOpenManagerAssignModal: () => void;
  onCloseManagerAssignModal: () => void;
  onChangeManager: (managerId: string) => void;
  onOpenAttachmentPicker: (scope?: UploadableAttachmentScopeValue) => void;
  onUploadAttachmentFiles: (scope: UploadableAttachmentScopeValue, files: File[]) => void;
  onRequestDeleteAttachment: (attachmentId: string) => void;
  onSetPrimaryDesignAttachment: (attachmentId: string) => void;
  onAttachmentDeleteConfirmClose: () => void;
  onAttachmentDeleteConfirm: () => void;
  onCreateMemoThread: SidePanelProps["onCreateMemoThread"];
  onCreateMemoReply: SidePanelProps["onCreateMemoReply"];
  onUpdateMemoThread: SidePanelProps["onUpdateMemoThread"];
  onDeleteMemoThread: SidePanelProps["onDeleteMemoThread"];
  onUpdateMemoReply: SidePanelProps["onUpdateMemoReply"];
  onDeleteMemoReply: SidePanelProps["onDeleteMemoReply"];
};

export type WorkspaceViewModel = {
  sidebarListProps: SidebarListProps;
  detailProps: DetailProps;
  sidePanelProps: SidePanelProps;
  modalProps: ModalProps;
  mobileTopBarProps: MobileTopBarProps;
  mobileDrawerProps: MobileDrawerProps;
};

export type BaseWorkspaceViewModelArgs = {
  version: string;
  currentUser: UserProfile;
  currentRole: RoleType;
  selectedWorkOrder: WorkOrder;
  hasVisibleWorkOrders: boolean;
  currentWorkflowState: WorkflowState;
  canCreateWorkOrder: boolean;
  canSeeAttachments: boolean;
  canUploadOfficialAttachments: boolean;
  canEditMemo: boolean;
  canRenameTitle: boolean;
  isAdmin: boolean;
  isReviewRequestLocked: boolean;
  canEditSideDraftContent: boolean;
  canChangeManager: boolean;
  canSeeProductionSections: boolean;
  canSeeCostSections: boolean;
  canOpenInventoryEditor: boolean;
  currentDisplayStage: DetailProps["currentDisplayStage"];
  currentInventoryQuantity: number;
  designAttachments: Attachment[];
  officialAttachments: Attachment[];
  selectedAttachment: Attachment | null;
  fabricTotal: number;
  subsidiaryTotal: number;
  outsourcingTotal: number;
  totalCost: number;
  unitCost: number;
  saveStatus: DetailProps["saveStatus"];
  lastSavedAt: string | null;
  availableActions: WorkflowAction[];
  visibleStages: DetailProps["visibleStages"];
  workflowProcessingLabel?: string | null;
  isWorkspaceWriteLocked?: boolean;
  workspaceWriteLockMessage?: string;
  getAttachmentPermissions: GetAttachmentPermissions;
  i18n: ReturnType<typeof getI18n>;
  onSave: () => void;
  onWorkflowAction: (action: WorkflowAction) => void;
  onUpdateSelectedWorkOrder: (patch: Partial<WorkOrder>) => void;
  onRenameWorkOrderTitle: (nextTitle: string) => void;
  onCompleteInspection: DetailProps["onCompleteInspection"];
  onOpenManagerAssignModal: () => void;
  onOpenAttachmentPicker: (scope?: UploadableAttachmentScopeValue) => void;
  onUploadAttachmentFiles: (scope: UploadableAttachmentScopeValue, files: File[]) => void;
  onRequestDeleteAttachment: (attachmentId: string) => void;
  onSetPrimaryDesignAttachment: (attachmentId: string) => void;
  onCreateMemoThread: SidePanelProps["onCreateMemoThread"];
  onCreateMemoReply: SidePanelProps["onCreateMemoReply"];
  onUpdateMemoThread: SidePanelProps["onUpdateMemoThread"];
  onDeleteMemoThread: SidePanelProps["onDeleteMemoThread"];
  onUpdateMemoReply: SidePanelProps["onUpdateMemoReply"];
  onDeleteMemoReply: SidePanelProps["onDeleteMemoReply"];
};

export type SidebarViewModelArgs = {
  companyName: string;
  version: string;
  currentUser: UserProfile;
  workOrders: SidebarListProps["workOrders"];
  selectedId: string;
  workflowStateById: Record<string, string>;
  canDeleteWorkOrder: SidebarListProps["canDelete"];
  canCreateWorkOrder: boolean;
  searchQuery: string;
  listStatusFilter: WorkOrderListStatusFilter;
  listSort: WorkOrderListSort;
  onSelectWorkOrder: (id: string) => void;
  onSetCreateWorkOrderModalOpen: (next: boolean) => void;
  onSetPermissionModalOpen: (next: boolean) => void;
  onReorderWorkOrder: (id: string) => void;
  onDeleteWorkOrder: (id: string) => void;
  onReworkWorkOrder: (id: string) => void;
  onSetSearchQuery: (next: string) => void;
  onSetListStatusFilter: (next: WorkOrderListStatusFilter) => void;
  onSetListSort: (next: WorkOrderListSort) => void;
  onResetListControls: () => void;
  dbConnectionStatus?: DbConnectionStatus;
  showRepositoryBadges?: boolean;
  showUserSwitchingTools?: boolean;
  writeLocked?: boolean;
  writeLockMessage?: string;
};

export type DetailViewModelArgs = BaseWorkspaceViewModelArgs & {
  basicInfoOpen: boolean;
  materialOpen: boolean;
  outsourcingOpen: boolean;
  onSetBasicInfoOpen: (updater: (prev: boolean) => boolean) => void;
  onSetMaterialOpen: (next: boolean | ((prev: boolean) => boolean)) => void;
  onSetOutsourcingOpen: (next: boolean | ((prev: boolean) => boolean)) => void;
  onSetInventoryEditorOpen: (next: boolean) => void;
};

export type SidePanelViewModelArgs = BaseWorkspaceViewModelArgs;

export type ModalViewModelArgs = {
  isAdmin: boolean;
  inventoryEditorOpen: boolean;
  permissionModalOpen: boolean;
  createWorkOrderModalOpen: boolean;
  managerAssignModalOpen: boolean;
  inventoryLogModalOpen: boolean;
  orderRequestConfirmOpen: boolean;
  users: UserProfile[];
  currentUserId: string;
  permissionTargetUserId: string;
  historyFilter: HistoryFilter;
  currentRole: RoleType;
  selectedWorkOrder: WorkOrder;
  currentInventoryQuantity: number;
  filteredHistoryLogs: ModalProps["inventoryLog"]["logs"];
  inventoryLogs: InventoryLog[];
  selectedAttachment: Attachment | null;
  pendingAttachmentDelete: Attachment | null;
  getAttachmentPermissions: GetAttachmentPermissions;
  onSetInventoryEditorOpen: (next: boolean) => void;
  onSetPermissionModalOpen: (next: boolean) => void;
  onSetCreateWorkOrderModalOpen: (next: boolean) => void;
  onSetInventoryLogModalOpen: (next: boolean) => void;
  onSetAttachmentPreviewId: (next: string | null) => void;
  onSetPermissionTargetUserId: (next: string) => void;
  onSetCurrentUserId: (next: string) => void;
  showUserSwitchingTools?: boolean;
  onSetHistoryFilter: (next: HistoryFilter) => void;
  onCreateWorkOrder: ModalProps["createWorkOrder"]["onCreate"];
  onConfirmOrderRequest: (payload: { factoryName: string; quantity: number }) => void;
  onCloseOrderRequestConfirm: () => void;
  onInventoryApply: ModalProps["inventoryEditor"]["onApply"];
  onApplyRoles: ModalProps["permission"]["onApplyRoles"];
  onCloseManagerAssignModal: () => void;
  onChangeManager: (managerId: string) => void;
  onRequestDeleteAttachment: (attachmentId: string) => void;
  onAttachmentDeleteConfirmClose: () => void;
  onAttachmentDeleteConfirm: () => void;
};

export type MobileViewModelArgs = {
  companyName: string;
  version: string;
  drawerOpen: boolean;
  dbConnectionStatus?: DbConnectionStatus;
  showRepositoryBadges?: boolean;
  showUserSwitchingTools?: boolean;
  sidebarListProps: SidebarListProps;
  onSetDrawerOpen: (next: boolean) => void;
  onSetPermissionModalOpen: (next: boolean) => void;
  onReorderWorkOrder: (id: string) => void;
  onReworkWorkOrder: (id: string) => void;
};
